#ifndef KS_SMART_CHAR_HANAKO_H
#define KS_SMART_CHAR_HANAKO_H

#include "smart_character_bg.h"

namespace ks::smart_characters::hanako {

extern const tileset_data tileset;

// Per-group bodies (one per pose × outfit × close).
extern const body hanagown_basic_body;
extern const body hanagown_stock_body;
extern const body hanagown_basic_close_body;
extern const body hanagown_stock_close_body;
extern const body hanako_basic_cas_body;
extern const body hanako_basic_body;
extern const body hanako_cover_cas_body;
extern const body hanako_cover_body;
extern const body hanako_def_cas_body;
extern const body hanako_def_body;
extern const body hanako_defarms_cas_body;
extern const body hanako_defarms_body;
extern const body hanako_emb_cas_body;
extern const body hanako_emb_body;
extern const body hanako_basic_cas_close_body;
extern const body hanako_basic_close_body;
extern const body hanako_cover_cas_close_body;
extern const body hanako_cover_close_body;
extern const body hanako_def_cas_close_body;
extern const body hanako_def_close_body;
extern const body hanako_defarms_cas_close_body;
extern const body hanako_defarms_close_body;
extern const body hanako_emb_cas_close_body;
extern const body hanako_emb_close_body;
extern const body hanako_basic_silhouette_body;

// Per-(group × emotion) variants.
extern const variant hanagown_basic_drunkgiggle;
extern const variant hanagown_basic_normalblush;
extern const variant hanagown_basic_distantblush;
extern const variant hanagown_basic_worry;
extern const variant hanagown_basic_drunkpout;
extern const variant hanagown_basic_worryblush;
extern const variant hanagown_basic_smile;
extern const variant hanagown_basic_drunksmile;
extern const variant hanagown_basic_drunknormal;
extern const variant hanagown_basic_drunksad;
extern const variant hanagown_basic_irritated;
extern const variant hanagown_basic_drunkdistant;
extern const variant hanagown_basic_distant;
extern const variant hanagown_basic_normal;
extern const variant hanagown_stock_distantblush;
extern const variant hanagown_stock_normalblush;
extern const variant hanagown_basic_close_drunkworry;
extern const variant hanagown_basic_close_smile;
extern const variant hanagown_basic_close_drunknormal;
extern const variant hanagown_basic_close_drunkgiggle;
extern const variant hanagown_basic_close_normal;
extern const variant hanagown_basic_close_distant;
extern const variant hanagown_basic_close_drunksmile;
extern const variant hanagown_basic_close_drunkpout;
extern const variant hanagown_basic_close_worry;
extern const variant hanagown_stock_close_worryblush;
extern const variant hanako_basic_cas_worry;
extern const variant hanako_basic_cas_normal;
extern const variant hanako_basic_cas_smile;
extern const variant hanako_basic_cas_distant;
extern const variant hanako_basic_cas_bashful;
extern const variant hanako_basic_smile;
extern const variant hanako_basic_normal;
extern const variant hanako_basic_worry;
extern const variant hanako_basic_distant;
extern const variant hanako_basic_bashful;
extern const variant hanako_cover_cas_bashful;
extern const variant hanako_cover_cas_worry;
extern const variant hanako_cover_cas_distant;
extern const variant hanako_cover_worry;
extern const variant hanako_cover_smile;
extern const variant hanako_cover_distant;
extern const variant hanako_cover_bashful;
extern const variant hanako_def_cas_worry;
extern const variant hanako_def_cas_strain;
extern const variant hanako_def_shock;
extern const variant hanako_def_worry;
extern const variant hanako_def_strain;
extern const variant hanako_defarms_cas_shock;
extern const variant hanako_defarms_cas_worry;
extern const variant hanako_defarms_cas_strain;
extern const variant hanako_defarms_strain;
extern const variant hanako_defarms_worry;
extern const variant hanako_defarms_shock;
extern const variant hanako_emb_cas_smile;
extern const variant hanako_emb_cas_downsmile;
extern const variant hanako_emb_cas_downsad;
extern const variant hanako_emb_cas_timid;
extern const variant hanako_emb_cas_downtimid;
extern const variant hanako_emb_cas_emb;
extern const variant hanako_emb_cas_blushing;
extern const variant hanako_emb_cas_sad;
extern const variant hanako_emb_downsad;
extern const variant hanako_emb_blushtimid;
extern const variant hanako_emb_emb;
extern const variant hanako_emb_blushing;
extern const variant hanako_emb_timid;
extern const variant hanako_emb_downsmile;
extern const variant hanako_emb_downtimid;
extern const variant hanako_emb_smile;
extern const variant hanako_emb_sad;
extern const variant hanako_basic_cas_close_worry;
extern const variant hanako_basic_cas_close_smile;
extern const variant hanako_basic_cas_close_bashful;
extern const variant hanako_basic_cas_close_distant;
extern const variant hanako_basic_cas_close_normal;
extern const variant hanako_basic_close_smile;
extern const variant hanako_basic_close_bashful;
extern const variant hanako_basic_close_distant;
extern const variant hanako_basic_close_worry;
extern const variant hanako_basic_close_normal;
extern const variant hanako_cover_cas_close_bashful;
extern const variant hanako_cover_cas_close_distant;
extern const variant hanako_cover_cas_close_worry;
extern const variant hanako_cover_cas_close_smile;
extern const variant hanako_cover_close_smile;
extern const variant hanako_cover_close_worry;
extern const variant hanako_cover_close_bashful;
extern const variant hanako_cover_close_distant;
extern const variant hanako_def_cas_close_worry;
extern const variant hanako_def_cas_close_strain;
extern const variant hanako_def_close_worry;
extern const variant hanako_def_close_shock;
extern const variant hanako_defarms_cas_close_strain;
extern const variant hanako_defarms_cas_close_worry;
extern const variant hanako_defarms_close_shock;
extern const variant hanako_defarms_close_strain;
extern const variant hanako_emb_cas_close_downtimid;
extern const variant hanako_emb_cas_close_timid;
extern const variant hanako_emb_cas_close_downsad;
extern const variant hanako_emb_cas_close_downsmile;
extern const variant hanako_emb_cas_close_smile;
extern const variant hanako_emb_cas_close_sad;
extern const variant hanako_emb_cas_close_emb;
extern const variant hanako_emb_cas_close_blushtimid;
extern const variant hanako_emb_close_downsad;
extern const variant hanako_emb_close_sad;
extern const variant hanako_emb_close_downsmile;
extern const variant hanako_emb_close_blushing;
extern const variant hanako_emb_close_blushtimid;
extern const variant hanako_emb_close_downtimid;
extern const variant hanako_emb_close_smile;
extern const variant hanako_emb_close_timid;
extern const variant hanako_emb_close_emb;
extern const variant hanako_basic_silhouette_bashful;

}  // namespace ks::smart_characters::hanako

#endif  // KS_SMART_CHAR_HANAKO_H
