#ifndef KS_SMART_CHAR_RIN_H
#define KS_SMART_CHAR_RIN_H

#include "smart_character_bg.h"

namespace ks::smart_characters::rin {

extern const tileset_data tileset;

// Per-group bodies (one per pose × outfit × close).
extern const body rin_basic_cas_body;
extern const body rin_negative_cas_body;
extern const body rin_relaxed_cas_body;
extern const body rin_basic_body;
extern const body rin_negative_body;
extern const body rin_relaxed_body;
extern const body rin_back_body;
extern const body rin_basic_cas_close_body;
extern const body rin_negative_cas_close_body;
extern const body rin_relaxed_cas_close_body;
extern const body rin_basic_close_body;
extern const body rin_negative_close_body;
extern const body rin_relaxed_close_body;
extern const body rin_relaxed_silhouette_body;
extern const body rinpan_basic_body;
extern const body rinpan_relaxed_body;
extern const body rinpan_basic_close_body;
extern const body rinpan_relaxed_close_body;

// Per-(group × emotion) variants.
extern const variant rin_basic_cas_deadpanupset;
extern const variant rin_basic_cas_deadpancontemplation;
extern const variant rin_basic_cas_deadpan;
extern const variant rin_basic_cas_surprised;
extern const variant rin_basic_cas_deadpannormal;
extern const variant rin_basic_cas_awayabsent;
extern const variant rin_basic_cas_sad;
extern const variant rin_basic_cas_absent;
extern const variant rin_basic_cas_lucid;
extern const variant rin_negative_cas_spaciness;
extern const variant rin_negative_cas_annoyed;
extern const variant rin_negative_cas_sad;
extern const variant rin_negative_cas_worried;
extern const variant rin_negative_cas_confused;
extern const variant rin_negative_cas_angry;
extern const variant rin_relaxed_cas_sleepy;
extern const variant rin_relaxed_cas_doubt;
extern const variant rin_relaxed_cas_nonchalant;
extern const variant rin_basic_delight;
extern const variant rin_basic_sad;
extern const variant rin_basic_deadpannormal;
extern const variant rin_basic_surprised;
extern const variant rin_basic_deadpandelight;
extern const variant rin_basic_upset;
extern const variant rin_basic_deadpanamused;
extern const variant rin_basic_absent;
extern const variant rin_basic_amused;
extern const variant rin_basic_deadpanupset;
extern const variant rin_basic_deadpancontemplation;
extern const variant rin_basic_lucid;
extern const variant rin_basic_crying;
extern const variant rin_basic_awayabsent;
extern const variant rin_basic_deadpansurprised;
extern const variant rin_basic_deadpan;
extern const variant rin_negative_angry;
extern const variant rin_negative_crying;
extern const variant rin_negative_confused;
extern const variant rin_negative_sad;
extern const variant rin_negative_annoyed;
extern const variant rin_negative_worried;
extern const variant rin_negative_spaciness;
extern const variant rin_relaxed_doubt;
extern const variant rin_relaxed_surprised;
extern const variant rin_relaxed_boredom;
extern const variant rin_relaxed_nonchalant;
extern const variant rin_relaxed_disgust;
extern const variant rin_relaxed_sleepy;
extern const variant rin_back_cas;
extern const variant rin_basic_cas_close_awayabsent;
extern const variant rin_basic_cas_close_sad;
extern const variant rin_basic_cas_close_lucid;
extern const variant rin_basic_cas_close_deadpansurprised;
extern const variant rin_basic_cas_close_deadpanupset;
extern const variant rin_basic_cas_close_deadpanamused;
extern const variant rin_basic_cas_close_deadpan;
extern const variant rin_basic_cas_close_deadpannormal;
extern const variant rin_basic_cas_close_surprised;
extern const variant rin_basic_cas_close_absent;
extern const variant rin_negative_cas_close_sad;
extern const variant rin_negative_cas_close_confused;
extern const variant rin_negative_cas_close_worried;
extern const variant rin_negative_cas_close_spaciness;
extern const variant rin_negative_cas_close_annoyed;
extern const variant rin_negative_cas_close_angry;
extern const variant rin_relaxed_cas_close_nonchalant;
extern const variant rin_relaxed_cas_close_doubt;
extern const variant rin_basic_close_crying;
extern const variant rin_basic_close_awayabsent;
extern const variant rin_basic_close_lucid;
extern const variant rin_basic_close_delight;
extern const variant rin_basic_close_deadpandelight;
extern const variant rin_basic_close_upset;
extern const variant rin_basic_close_amused;
extern const variant rin_basic_close_deadpanupset;
extern const variant rin_basic_close_blush;
extern const variant rin_basic_close_deadpancontemplation;
extern const variant rin_basic_close_deadpansurprised;
extern const variant rin_basic_close_deadpan;
extern const variant rin_basic_close_sad;
extern const variant rin_basic_close_surprised;
extern const variant rin_basic_close_deadpannormal;
extern const variant rin_basic_close_deadpanamused;
extern const variant rin_basic_close_absent;
extern const variant rin_negative_close_worried;
extern const variant rin_negative_close_sad;
extern const variant rin_negative_close_confused;
extern const variant rin_negative_close_annoyed;
extern const variant rin_negative_close_spaciness;
extern const variant rin_negative_close_angry;
extern const variant rin_relaxed_close_sleepy;
extern const variant rin_relaxed_close_surprised;
extern const variant rin_relaxed_close_nonchalant;
extern const variant rin_relaxed_close_boredom;
extern const variant rin_relaxed_close_doubt;
extern const variant rin_relaxed_silhouette_surprised;
extern const variant rinpan_basic_deadpan;
extern const variant rinpan_basic_upset;
extern const variant rinpan_basic_surprised;
extern const variant rinpan_basic_awayabsent;
extern const variant rinpan_basic_deadpandelight;
extern const variant rinpan_basic_deadpanupset;
extern const variant rinpan_basic_deadpanamused;
extern const variant rinpan_basic_amused;
extern const variant rinpan_basic_absent;
extern const variant rinpan_basic_lucid;
extern const variant rinpan_basic_deadpancontemplation;
extern const variant rinpan_basic_deadpannormal;
extern const variant rinpan_basic_deadpansurprised;
extern const variant rinpan_relaxed_sleepy;
extern const variant rinpan_relaxed_boredom;
extern const variant rinpan_relaxed_surprised;
extern const variant rinpan_relaxed_nonchalant;
extern const variant rinpan_relaxed_doubt;
extern const variant rinpan_basic_close_deadpanamused;
extern const variant rinpan_basic_close_awayabsent;
extern const variant rinpan_basic_close_deadpancontemplation;
extern const variant rinpan_basic_close_deadpan;
extern const variant rinpan_basic_close_lucid;
extern const variant rinpan_basic_close_deadpandelight;
extern const variant rinpan_basic_close_deadpanupset;
extern const variant rinpan_relaxed_close_boredom;
extern const variant rinpan_relaxed_close_doubt;
extern const variant rinpan_relaxed_close_sleepy;
extern const variant rinpan_relaxed_close_nonchalant;
extern const variant rinpan_relaxed_close_surprised;

}  // namespace ks::smart_characters::rin

#endif  // KS_SMART_CHAR_RIN_H
