#include "script_a1_tuesday.h"
#include "script_a1_tuesday_en_tl_index.h"
namespace ks {
    class ScriptA1TuesdayEn : public ScriptA1Tuesday {
        public:
            static void a1_tuesday_smalltalk() {
                ks::SceneManager::free_resources();
                ks::SceneManager::set_background(bn::regular_bg_items::school_dormhisao);
                ks::SceneManager::show_dialog("", 0);
                ks::SceneManager::show_dialog("", 1);
                ks::SceneManager::show_dialog("", 2);
                ks::SceneManager::show_dialog("", 3);
                ks::SceneManager::music_play("music_dreamy.gsm");
                ks::SceneManager::show_dialog("", 4);
                ks::SceneManager::show_dialog("", 5);
                ks::SceneManager::show_dialog("", 6);
                ks::SceneManager::show_dialog("", 7);
                ks::SceneManager::show_dialog("", 8);
                ks::SceneManager::show_dialog("", 9);
                ks::SceneManager::show_dialog("", 10);
                ks::SceneManager::show_dialog("", 11);
                ks::SceneManager::show_dialog("", 12);
                ks::SceneManager::show_dialog("", 13);
                ks::SceneManager::show_dialog("", 14);
                ks::SceneManager::show_dialog("", 15);
                ks::SceneManager::show_dialog("", 16);
                ks::SceneManager::show_dialog("", 17);
                ks::SceneManager::show_dialog("", 18);
                ks::SceneManager::show_dialog("", 19);
                ks::SceneManager::show_dialog("", 20);
                ks::SceneManager::show_dialog("", 21);
                ks::SceneManager::show_dialog("", 22);
                ks::SceneManager::music_stop();
                ks::SceneManager::set_background(bn::regular_bg_items::school_scienceroom);
                ks::SceneManager::show_dialog("", 23);
                ks::SceneManager::show_dialog("", 24);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_cross, bn::sprite_items::shizu_spr_cross_wut, ks::sprite_metas::shizu_cross);
                ks::SceneManager::show_dialog("", 26);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_cross, bn::sprite_items::shizu_spr_cross_angry, ks::sprite_metas::shizu_cross);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_cross, bn::sprite_items::shizu_spr_cross_angry, ks::sprite_metas::shizu_cross, 48, 0);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips, -48, 0);
                ks::SceneManager::music_play("music_happiness.gsm");
                ks::SceneManager::show_dialog("mi", 27);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_angry, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("mi", 28);
                ks::SceneManager::show_dialog("", 29);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal2, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_smile, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog("mi", 30);
                ks::SceneManager::show_dialog("mi", 31);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 32);
                ks::SceneManager::show_dialog("hi", 33);
                ks::SceneManager::show_dialog("hi", 34);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("", 35);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_laugh, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 36);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_confused, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog("", 37);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_confused, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog("mi", 38);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 39);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("", 40);
                ks::SceneManager::show_dialog("", 41);
                ks::SceneManager::show_dialog("hi", 42);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_frown, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 43);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog("shi", 44);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 45);
                ks::SceneManager::show_dialog("", 46);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_sad, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog("", 47);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_angry, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("mi", 48);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("mi", 49);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_sparkle, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_smile, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog("mi", 50);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("", 51);
                ks::SceneManager::show_dialog("hi", 52);
                ks::SceneManager::show_dialog("", 53);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog("", 54);
                ks::SceneManager::show_dialog("", 55);
                ks::SceneManager::show_dialog("", 56);
                ks::SceneManager::show_dialog("", 57);
                ks::SceneManager::show_dialog("", 58);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("mi", 59);
                ks::SceneManager::show_dialog("", 60);
                ks::SceneManager::show_dialog("", 61);
                ks::SceneManager::show_dialog("hi", 62);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_happy, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 63);
                ks::SceneManager::show_dialog("", 64);
                ks::SceneManager::show_dialog("hi", 65);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 66);
                ks::SceneManager::show_dialog("hi", 33);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_laugh, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog("mi", 67);
                ks::SceneManager::set_background(bn::regular_bg_items::school_scienceroom);
                ks::SceneManager::show_dialog("", 68);
                ks::SceneManager::show_dialog("", 69);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_frown, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog("", 70);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind, 48, 0);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips, -48, 0);
                ks::SceneManager::music_play("music_comedy.gsm");
                ks::SceneManager::show_dialog("mi", 71);
                ks::SceneManager::show_dialog("hi", 72);
                ks::SceneManager::show_dialog("mi", 73);
                ks::SceneManager::show_dialog("hi", 74);
                ks::SceneManager::show_dialog("", 75);
                ks::SceneManager::show_dialog("", 76);
                ks::SceneManager::show_dialog("", 77);
                ks::SceneManager::show_dialog("", 78);
                ks::SceneManager::show_dialog("hi", 79);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_happy, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog("", 80);
                ks::SceneManager::show_dialog("", 81);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("mi", 82);
                ks::SceneManager::show_dialog("hi", 83);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 84);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_laugh, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 85);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog("", 86);
                ks::SceneManager::hide_character(0);
                ks::SceneManager::hide_character(1);
                ks::SceneManager::show_dialog("", 87);
                ks::SceneManager::set_background(bn::regular_bg_items::school_hallway3);
                ks::SceneManager::show_dialog("", 88);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips, -120, 0);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind, 120, 0);
                ks::SceneManager::set_character_position(1, -48, 0);
                ks::SceneManager::set_character_position(0, 48, 0);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 89);
                ks::SceneManager::show_dialog("hi", 90);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_laugh, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 91);
                ks::SceneManager::show_dialog("", 92);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog("", 93);
                ks::SceneManager::show_dialog("", 94);
                ks::SceneManager::set_background(bn::regular_bg_items::school_cafeteria);
                ks::SceneManager::show_dialog("", 95);
                ks::SceneManager::show_dialog("", 96);
                ks::SceneManager::music_play("music_shizune.gsm");
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky, -48, 0);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind, 48, 0);
                ks::SceneManager::show_dialog("mi", 97);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_dialog("mi", 98);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("", 99);
                ks::SceneManager::show_dialog("mi", 100);
                ks::SceneManager::show_dialog("hi", 101);
                ks::SceneManager::show_dialog("hi", 102);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("mi", 103);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_happy, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_dialog("mi", 104);
                ks::SceneManager::show_dialog("hi", 105);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_laugh, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog("mi", 106);
                ks::SceneManager::show_dialog("hi", 107);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_grin, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog("mi", 108);
                ks::SceneManager::show_dialog("mi", 109);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_laugh, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 110);
                ks::SceneManager::show_dialog("", 111);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_blush, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog("", 112);
                ks::SceneManager::show_dialog("", 113);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_grin, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog("mi", 114);
                ks::SceneManager::show_dialog("hi", 115);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_smile, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog("mi", 116);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("mi", 117);
                ks::SceneManager::show_dialog("", 118);
                ks::SceneManager::show_dialog("", 119);
                ks::SceneManager::show_dialog("", 120);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 121);
                ks::SceneManager::show_dialog("hi", 122);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("mi", 123);
                ks::SceneManager::show_dialog("mi", 124);
                ks::SceneManager::show_dialog("mi", 125);
                ks::SceneManager::show_dialog("", 126);
                ks::SceneManager::show_dialog("hi", 127);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 128);
                ks::SceneManager::show_dialog("hi", 129);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_sad, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("mi", 130);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("mi", 131);
                ks::SceneManager::show_dialog("hi", 132);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_happy, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog("", 133);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_laugh, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog("mi", 134);
                ks::SceneManager::show_dialog("hi", 135);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 136);
                ks::SceneManager::show_dialog("hi", 137);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_sad, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("mi", 138);
                ks::SceneManager::show_dialog("hi", 139);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 140);
                ks::SceneManager::show_dialog("hi", 141);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_angry, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_frown, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 142);
                ks::SceneManager::show_dialog("hi", 143);
                ks::SceneManager::show_dialog("", 144);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_dialog("mi", 145);
                ks::SceneManager::show_dialog("hi", 146);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 147);
                ks::SceneManager::show_dialog("hi", 148);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 149);
                ks::SceneManager::show_dialog("mi", 150);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_dialog("mi", 151);
                ks::SceneManager::show_dialog("hi", 152);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_laugh, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog("mi", 153);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_grin, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog("", 154);
                ks::SceneManager::show_dialog("", 155);
                ks::SceneManager::show_dialog("", 156);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_smile, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog("mi", 157);
                ks::SceneManager::show_dialog("hi", 158);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 159);
                ks::SceneManager::show_dialog("", 160);
                ks::SceneManager::show_dialog("mi", 161);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_dialog("mi", 162);
                ks::SceneManager::show_dialog("hi", 163);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("mi", 164);
                ks::SceneManager::show_dialog("hi", 165);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 166);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_laugh, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog("mi", 85);
                ks::SceneManager::show_dialog("", 167);
                ks::SceneManager::show_dialog("", 168);
                ks::SceneManager::show_dialog("", 169);
                ks::SceneManager::music_stop();
                ks::SceneManager::set_background(bn::regular_bg_items::school_scienceroom);
                ks::SceneManager::show_dialog("", 170);
                ks::SceneManager::show_dialog("", 171);
                if (ks::in_replay) {
                    ScriptA1TuesdayEn::a1_tuesday_smalltalk__condition_0_0();
                } 
                
            
            }
            static void a1_tuesday_risk_vs_reward() {
                ks::SceneManager::free_resources();
                ks::SceneManager::set_background(bn::regular_bg_items::school_lobby);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind, 48, 0);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips, -48, 0);
                ks::SceneManager::music_play("music_ease.gsm");
                ks::SceneManager::show_dialog("", 172);
                ks::SceneManager::show_dialog("", 173);
                ks::SceneManager::show_dialog("hi", 174);
                ks::SceneManager::show_dialog("", 175);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_laugh, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog("mi", 176);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_grin, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog("mi", 177);
                ks::SceneManager::show_dialog("", 178);
                ks::SceneManager::show_dialog("", 179);
                ks::SceneManager::hide_character(1);
                ks::SceneManager::hide_character(0);
                ks::SceneManager::show_dialog("", 180);
                ks::SceneManager::show_dialog("hi", 181);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal2, ks::sprite_metas::shizu_basic, 48, 0);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky, -48, 0);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 182);
                ks::SceneManager::show_dialog("hi", 183);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog("", 184);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 185);
                ks::SceneManager::show_dialog("", 186);
                ks::SceneManager::music_stop();
                ks::SceneManager::set_background(bn::regular_bg_items::school_council);
                ks::SceneManager::show_dialog("", 187);
                ks::SceneManager::show_dialog("", 188);
                ks::SceneManager::show_dialog("", 189);
                ks::SceneManager::show_dialog("", 190);
                ks::SceneManager::show_dialog("hi", 191);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind, 48, 0);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips, -48, 0);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 192);
                ks::SceneManager::show_dialog("hi", 193);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_smile, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog("mi", 194);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_happy, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog("", 195);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 196);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 197);
                ks::SceneManager::hide_character(0);
                ks::SceneManager::show_dialog("", 198);
                ks::SceneManager::show_dialog("", 199);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_frown, ks::sprite_metas::shizu_adjust, 48, 0);
                ks::SceneManager::show_dialog("", 200);
                ks::SceneManager::show_dialog("", 201);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal2, ks::sprite_metas::shizu_basic);
                ks::SceneManager::music_play("music_running.gsm");
                ks::SceneManager::show_dialog("", 202);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_smile, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog("mi", 203);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 204);
                ks::SceneManager::show_dialog("hi", 205);
                ks::SceneManager::show_dialog("", 206);
                ks::SceneManager::show_dialog("hi", 207);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_dialog("mi", 208);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_laugh, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog("mi", 209);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_grin, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog("hi", 210);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog("", 211);
                ks::SceneManager::show_dialog("hi", 212);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("mi", 213);
                ks::SceneManager::show_dialog("", 214);
                ks::SceneManager::show_dialog("", 215);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_happy, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_dialog("", 216);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_confused, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog("mi", 217);
                ks::SceneManager::show_dialog("hi", 218);
                ks::SceneManager::show_dialog("mi", 219);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_sparkle, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog("", 220);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_happy, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_smile, ks::sprite_metas::misha_cross);
                ScriptA1TuesdayEn::a1_tuesday_risk_vs_reward__menu_question_0();
                ks::SceneManager::show_dialog("", 221);
                ks::SceneManager::show_dialog("hi", 222);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog("", 223);
                ks::SceneManager::show_dialog("", 224);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("mi", 225);
                ks::SceneManager::show_dialog("mi", 226);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 227);
                ks::SceneManager::show_dialog("hi", 228);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 229);
                ks::SceneManager::music_stop();
                if (ks::in_replay) {
                    ScriptA1TuesdayEn::a1_tuesday_risk_vs_reward__condition_0_0();
                } 
                
            
            }
            static void a1_tuesday_pseudo_tea_cosy() {
                ks::SceneManager::free_resources();
                ks::SceneManager::set_background(bn::regular_bg_items::school_staircase2);
                ks::SceneManager::set_background(bn::regular_bg_items::school_hallway2);
                ks::SceneManager::show_dialog("", 230);
                ks::SceneManager::show_dialog("", 231);
                ks::SceneManager::show_dialog("", 232);
                ks::SceneManager::show_dialog("", 233);
                ks::SceneManager::show_dialog("", 234);
                ks::SceneManager::show_dialog("", 235);
                ks::SceneManager::show_dialog("", 236);
                ks::SceneManager::show_dialog("", 237);
                ks::SceneManager::show_dialog("", 238);
                ks::SceneManager::show_dialog("", 239);
                ks::SceneManager::show_dialog("", 240);
                ks::SceneManager::show_dialog("", 241);
                ks::SceneManager::show_dialog("", 242);
                ks::SceneManager::show_dialog("", 243);
                ks::SceneManager::show_dialog("", 244);
                ks::SceneManager::music_play("music_lilly.gsm");
                ks::SceneManager::set_background(bn::regular_bg_items::lilly_tearoom);
                ks::SceneManager::show_dialog("", 25);
                ks::SceneManager::show_dialog("", 245);
                ks::SceneManager::show_dialog("", 246);
                ks::SceneManager::show_dialog("", 247);
                ks::SceneManager::show_dialog("", 248);
                ks::SceneManager::set_background(bn::regular_bg_items::lilly_tearoom_open);
                ks::SceneManager::show_dialog("li_", 249);
                ks::SceneManager::show_dialog("", 250);
                ks::SceneManager::show_dialog("", 251);
                ks::SceneManager::show_dialog("", 252);
                ks::SceneManager::show_dialog("hi", 253);
                ks::SceneManager::show_dialog("", 254);
                ks::SceneManager::show_dialog("li_", 255);
                ks::SceneManager::show_dialog("", 256);
                ks::SceneManager::show_dialog("hi", 257);
                ks::SceneManager::show_dialog("", 258);
                ks::SceneManager::show_dialog("", 259);
                ks::SceneManager::show_dialog("", 260);
                ks::SceneManager::show_dialog("", 261);
                ks::SceneManager::set_background(bn::regular_bg_items::lilly_tearoom);
                ks::SceneManager::show_dialog("", 262);
                ks::SceneManager::show_dialog("li_", 263);
                ks::SceneManager::show_dialog("hi", 264);
                ks::SceneManager::show_dialog("", 265);
                ks::SceneManager::show_dialog("", 266);
                ks::SceneManager::set_background(bn::regular_bg_items::lilly_tearoom_open);
                ks::SceneManager::show_dialog("li_", 267);
                ks::SceneManager::show_dialog("hi", 268);
                ks::SceneManager::show_dialog("", 269);
                ks::SceneManager::show_dialog("li", 270);
                ks::SceneManager::show_dialog("hi", 33);
                ks::SceneManager::show_dialog("", 271);
                ks::SceneManager::show_dialog("", 272);
                ks::SceneManager::set_background(bn::regular_bg_items::school_miyagi);
                ks::SceneManager::show_dialog("", 273);
                ks::SceneManager::show_dialog("", 274);
                ks::SceneManager::show_dialog("", 275);
                ks::SceneManager::show_dialog("", 276);
                ks::SceneManager::show_dialog("", 277);
                ks::SceneManager::show_dialog("", 278);
                ks::SceneManager::show_dialog("li", 279);
                ks::SceneManager::show_dialog("", 280);
                ks::SceneManager::show_character(2, bn::regular_bg_items::lilly_bg_basic, bn::sprite_items::lilly_spr_basic_smile, ks::sprite_metas::lilly_basic);
                ks::SceneManager::show_dialog("li", 281);
                ks::SceneManager::show_dialog("hi", 282);
                ks::SceneManager::show_dialog("", 283);
                ks::SceneManager::show_dialog("li", 284);
                ks::SceneManager::show_dialog("hi", 285);
                ks::SceneManager::show_character(2, bn::regular_bg_items::lilly_bg_basic2, bn::sprite_items::lilly_spr_basic2_giggle, ks::sprite_metas::lilly_basic2);
                ks::SceneManager::show_dialog("", 286);
                ks::SceneManager::show_dialog("li", 287);
                ks::SceneManager::set_background(bn::regular_bg_items::tearoom_lillyhisao_noon);
                ks::SceneManager::show_dialog("", 288);
                ks::SceneManager::show_dialog("", 289);
                ks::SceneManager::show_dialog("hi", 290);
                ks::SceneManager::show_dialog("", 291);
                ks::SceneManager::show_dialog("li", 292);
                ks::SceneManager::show_dialog("", 293);
                ks::SceneManager::show_dialog("", 294);
                ks::SceneManager::show_dialog("hi", 295);
                ks::SceneManager::show_dialog("li", 296);
                ks::SceneManager::show_dialog("hi", 297);
                ks::SceneManager::show_dialog("", 298);
                ks::SceneManager::show_dialog("li", 299);
                ks::SceneManager::show_dialog("hi", 300);
                ks::SceneManager::show_dialog("li", 301);
                ks::SceneManager::show_dialog("", 302);
                ks::SceneManager::show_dialog("hi", 303);
                ks::SceneManager::show_dialog("", 304);
                ks::SceneManager::show_dialog("li", 305);
                ks::SceneManager::show_dialog("", 306);
                ks::SceneManager::show_dialog("", 307);
                ks::SceneManager::show_dialog("", 308);
                ks::SceneManager::show_dialog("hi", 309);
                ks::SceneManager::show_dialog("li", 310);
                ks::SceneManager::show_dialog("li", 311);
                ks::SceneManager::show_dialog("", 312);
                ks::SceneManager::show_dialog("", 313);
                ks::SceneManager::show_dialog("hi", 314);
                ks::SceneManager::show_dialog("li", 315);
                ks::SceneManager::show_dialog("hi", 316);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog("", 317);
                ks::SceneManager::show_dialog("", 318);
                ks::SceneManager::set_background(bn::regular_bg_items::tearoom_lillyhisao_sunset);
                ks::SceneManager::music_play("music_tranquil.gsm");
                ks::SceneManager::show_dialog("", 319);
                ks::SceneManager::show_dialog("", 320);
                ks::SceneManager::show_dialog("hi", 321);
                ks::SceneManager::show_dialog("li", 143);
                ks::SceneManager::show_dialog("", 322);
                ks::SceneManager::show_dialog("hi", 323);
                ks::SceneManager::show_dialog("", 324);
                ks::SceneManager::show_dialog("li", 325);
                ks::SceneManager::show_dialog("", 326);
                ks::SceneManager::show_dialog("hi", 327);
                ks::SceneManager::show_dialog("", 328);
                ks::SceneManager::show_dialog("", 329);
                ks::SceneManager::show_dialog("li", 330);
                ks::SceneManager::show_dialog("", 331);
                ks::SceneManager::show_dialog("hi", 332);
                ks::SceneManager::show_dialog("", 333);
                ks::SceneManager::show_dialog("li", 334);
                ks::SceneManager::show_dialog("li", 335);
                ks::SceneManager::show_dialog("hi", 336);
                ks::SceneManager::show_dialog("", 337);
                ks::SceneManager::show_dialog("li", 338);
                ks::SceneManager::show_dialog("", 339);
                ks::SceneManager::show_dialog("hi", 340);
                ks::SceneManager::set_background(bn::regular_bg_items::school_miyagi_ss);
                ks::SceneManager::show_character(2, bn::regular_bg_items::lilly_bg_cane, bn::sprite_items::lilly_spr_cane_smile, ks::sprite_metas::lilly_cane);
                ks::SceneManager::show_dialog("", 341);
                ks::SceneManager::show_dialog("", 342);
                ks::SceneManager::show_dialog("", 343);
                ks::SceneManager::music_stop();
                ks::SceneManager::set_background(bn::regular_bg_items::school_hallway2);
                ks::SceneManager::show_dialog("", 344);
                ks::SceneManager::show_dialog("", 345);
                ks::SceneManager::show_dialog("hi", 346);
                ks::SceneManager::show_character(2, bn::regular_bg_items::lilly_bg_cane, bn::sprite_items::lilly_spr_cane_smileclosed, ks::sprite_metas::lilly_cane);
                ks::SceneManager::show_dialog("", 347);
                ks::SceneManager::set_background(bn::regular_bg_items::school_library_ss);
                ks::SceneManager::music_play("music_happiness.gsm");
                ks::SceneManager::show_dialog("", 348);
                ks::SceneManager::show_dialog("", 349);
                ks::SceneManager::show_dialog("", 350);
                ks::SceneManager::show_character(2, bn::regular_bg_items::lilly_bg_cane, bn::sprite_items::lilly_spr_cane_smileclosed, ks::sprite_metas::lilly_cane);
                ks::SceneManager::show_dialog("li", 351);
                ks::SceneManager::show_dialog("", 352);
                ks::SceneManager::show_dialog("", 353);
                ks::SceneManager::show_character(2, bn::regular_bg_items::lilly_bg_cane, bn::sprite_items::lilly_spr_cane_surprised, ks::sprite_metas::lilly_cane);
                ks::SceneManager::show_dialog("", 354);
                ks::SceneManager::show_dialog("mystery", 355);
                ks::SceneManager::show_character(2, bn::regular_bg_items::lilly_bg_cane, bn::sprite_items::lilly_spr_cane_weaksmile, ks::sprite_metas::lilly_cane, -48, 0);
                ks::SceneManager::show_dialog("", 356);
                ks::SceneManager::show_dialog("yu_", 357);
                ks::SceneManager::show_dialog("", 358);
                ks::SceneManager::show_dialog("li", 359);
                ks::SceneManager::show_dialog("yu_", 360);
                ks::SceneManager::show_dialog("yu_", 361);
                ks::SceneManager::show_character(2, bn::regular_bg_items::lilly_bg_cane, bn::sprite_items::lilly_spr_cane_sad, ks::sprite_metas::lilly_cane);
                ks::SceneManager::show_dialog("li", 362);
                ks::SceneManager::show_dialog("yu_", 363);
                ks::SceneManager::show_character(2, bn::regular_bg_items::lilly_bg_cane, bn::sprite_items::lilly_spr_cane_weaksmile, ks::sprite_metas::lilly_cane);
                ks::SceneManager::show_dialog("yu_", 364);
                ks::SceneManager::show_dialog("", 365);
                ks::SceneManager::show_dialog("yu_", 366);
                ks::SceneManager::show_dialog("", 367);
                ks::SceneManager::show_dialog("", 368);
                ks::SceneManager::show_dialog("yu_", 369);
                ks::SceneManager::show_character(2, bn::regular_bg_items::lilly_bg_cane, bn::sprite_items::lilly_spr_cane_reminisce, ks::sprite_metas::lilly_cane);
                ks::SceneManager::show_dialog("li", 370);
                ks::SceneManager::show_character(2, bn::regular_bg_items::lilly_bg_cane, bn::sprite_items::lilly_spr_cane_smile, ks::sprite_metas::lilly_cane);
                ks::SceneManager::show_dialog("li", 371);
                ks::SceneManager::show_dialog("yu_", 372);
                ks::SceneManager::show_dialog("", 373);
                ks::SceneManager::show_character(2, bn::regular_bg_items::lilly_bg_cane, bn::sprite_items::lilly_spr_cane_weaksmile, ks::sprite_metas::lilly_cane);
                ks::SceneManager::show_dialog("yu_", 374);
                ks::SceneManager::show_dialog("yu_", 375);
                ks::SceneManager::show_dialog("", 376);
                ks::SceneManager::show_character(2, bn::regular_bg_items::lilly_bg_cane, bn::sprite_items::lilly_spr_cane_smileclosed, ks::sprite_metas::lilly_cane);
                ks::SceneManager::show_dialog("li", 377);
                ks::SceneManager::show_dialog("hi", 378);
                ks::SceneManager::show_dialog("yu", 379);
                ks::SceneManager::show_dialog("", 380);
                ks::SceneManager::show_dialog("li", 381);
                ks::SceneManager::show_dialog("li", 382);
                ks::SceneManager::show_dialog("", 383);
                ks::SceneManager::show_dialog("yu", 384);
                ks::SceneManager::show_dialog("", 385);
                ks::SceneManager::show_character(2, bn::regular_bg_items::lilly_bg_cane, bn::sprite_items::lilly_spr_cane_sleepy, ks::sprite_metas::lilly_cane);
                ks::SceneManager::show_dialog("li", 386);
                ks::SceneManager::show_dialog("hi", 387);
                ks::SceneManager::show_dialog("", 388);
                ks::SceneManager::show_character(2, bn::regular_bg_items::lilly_bg_cane, bn::sprite_items::lilly_spr_cane_weaksmile, ks::sprite_metas::lilly_cane);
                ks::SceneManager::show_dialog("yu", 389);
                ks::SceneManager::show_dialog("", 390);
                ks::SceneManager::show_dialog("hi", 391);
                ks::SceneManager::show_dialog("yu", 392);
                ks::SceneManager::show_dialog("yu", 393);
                ks::SceneManager::show_dialog("yu", 394);
                ks::SceneManager::show_dialog("", 25);
                ks::SceneManager::show_dialog("", 395);
                ks::SceneManager::show_dialog("hi", 396);
                ks::SceneManager::show_dialog("", 397);
                ks::SceneManager::show_character(2, bn::regular_bg_items::lilly_bg_cane, bn::sprite_items::lilly_spr_cane_smileclosed, ks::sprite_metas::lilly_cane);
                ks::SceneManager::show_dialog("li", 398);
                ks::SceneManager::music_stop();
                if (ks::in_replay) {
                    ScriptA1TuesdayEn::a1_tuesday_pseudo_tea_cosy__condition_0_0();
                } 
                
            
            }
            static void a1_tuesday_shared_library() {
                ks::SceneManager::free_resources();
                ks::SceneManager::set_background(bn::regular_bg_items::school_library_ss);
                ks::SceneManager::show_dialog("", 399);
                ks::SceneManager::show_dialog("", 400);
                ks::SceneManager::show_dialog("", 401);
                ks::SceneManager::show_dialog("", 402);
                ks::SceneManager::show_dialog("", 403);
                ks::SceneManager::show_dialog("", 404);
                ks::SceneManager::show_dialog("", 405);
                ks::SceneManager::show_dialog("", 406);
                ks::SceneManager::show_dialog("", 407);
                ks::SceneManager::show_dialog("", 408);
                ks::SceneManager::music_play("music_another.gsm");
                ks::SceneManager::show_dialog("", 409);
                ks::SceneManager::show_dialog("", 410);
                ks::SceneManager::show_dialog("", 411);
                ks::SceneManager::show_dialog("", 412);
                ks::SceneManager::show_dialog("", 413);
                ks::SceneManager::show_dialog("", 414);
                ks::SceneManager::show_dialog("", 415);
                ks::SceneManager::show_dialog("", 416);
                ks::SceneManager::show_dialog("", 417);
                ks::SceneManager::show_dialog("", 418);
                ScriptA1TuesdayEn::a1_tuesday_shared_library__menu_question_0();
                ks::SceneManager::show_dialog("ha", 419);
                ks::SceneManager::show_dialog("ha", 420);
                ks::SceneManager::show_dialog("hi", 421);
                ks::SceneManager::show_dialog("ha", 422);
                ks::SceneManager::show_dialog("", 423);
                ks::SceneManager::show_dialog("", 424);
                ks::SceneManager::set_background(bn::regular_bg_items::school_library_ss);
                ks::SceneManager::show_character(2, bn::regular_bg_items::lilly_bg_cane, bn::sprite_items::lilly_spr_cane_smileclosed, ks::sprite_metas::lilly_cane, -48, 0);
                ks::SceneManager::music_play("music_pearly.gsm");
                ks::SceneManager::show_dialog("", 425);
                ks::SceneManager::show_dialog("", 426);
                ks::SceneManager::show_dialog("", 427);
                ks::SceneManager::show_dialog("hi", 428);
                ks::SceneManager::show_dialog("yu", 429);
                ks::SceneManager::show_dialog("hi", 430);
                ks::SceneManager::show_character(2, bn::regular_bg_items::lilly_bg_cane, bn::sprite_items::lilly_spr_cane_surprised, ks::sprite_metas::lilly_cane);
                ks::SceneManager::show_dialog("li", 431);
                ks::SceneManager::show_dialog("hi", 432);
                ks::SceneManager::show_character(2, bn::regular_bg_items::lilly_bg_cane, bn::sprite_items::lilly_spr_cane_sad, ks::sprite_metas::lilly_cane);
                ks::SceneManager::show_dialog("li", 433);
                ks::SceneManager::show_dialog("yu", 434);
                ks::SceneManager::show_dialog("hi", 435);
                ks::SceneManager::show_dialog("li", 436);
                ks::SceneManager::show_dialog("hi", 437);
                ks::SceneManager::hide_character(2);
                ks::SceneManager::show_dialog("", 438);
                ks::SceneManager::show_dialog("hi", 439);
                ks::SceneManager::show_dialog("hi", 440);
                ks::SceneManager::show_dialog("yu", 441);
                if (ks::progress.im_new_here == true) {
                    ScriptA1TuesdayEn::a1_tuesday_shared_library__condition_0_0();
                } 
                else {
                    ScriptA1TuesdayEn::a1_tuesday_shared_library__condition_0_1();
                } 
                
            
                ks::SceneManager::show_dialog("hi", 442);
                ks::SceneManager::show_dialog("hi", 443);
                ks::SceneManager::show_dialog("", 444);
                ks::SceneManager::show_dialog("yu", 445);
                ks::SceneManager::show_dialog("", 446);
                ks::SceneManager::show_dialog("yu", 447);
                ks::SceneManager::show_dialog("hi", 448);
                ks::SceneManager::show_dialog("", 449);
                ks::SceneManager::show_dialog("", 450);
                ks::SceneManager::show_dialog("yu", 451);
                ks::SceneManager::show_dialog("hi", 452);
                ks::SceneManager::show_dialog("hi", 453);
                ks::SceneManager::show_dialog("", 454);
                ks::SceneManager::show_dialog("yu", 455);
                ks::SceneManager::show_dialog("hi", 456);
                ks::SceneManager::show_dialog("hi", 457);
                ks::SceneManager::show_dialog("yu", 458);
                ks::SceneManager::show_dialog("", 459);
                ks::SceneManager::show_dialog("", 460);
                ks::SceneManager::music_stop();
                if (ks::in_replay) {
                    ScriptA1TuesdayEn::a1_tuesday_shared_library__condition_1_0();
                } 
                
            
            }
            static void a1_tuesday_bizarre_and_surreal() {
                ks::SceneManager::free_resources();
                ks::SceneManager::set_background(bn::regular_bg_items::school_dormhallway);
                ks::SceneManager::show_dialog("", 461);
                ks::SceneManager::show_dialog("", 462);
                ks::SceneManager::show_dialog("mystery", 463);
                ks::SceneManager::music_play("music_kenji.gsm");
                ks::SceneManager::show_dialog("", 464);
                ks::SceneManager::show_dialog("hi", 465);
                ks::SceneManager::show_dialog("", 466);
                ks::SceneManager::show_dialog("ke", 467);
                ks::SceneManager::show_dialog("", 468);
                ks::SceneManager::show_dialog("hi", 469);
                ks::SceneManager::show_dialog("ke", 470);
                ks::SceneManager::show_dialog("", 471);
                ks::SceneManager::show_dialog("ke", 472);
                ks::SceneManager::show_dialog("hi", 473);
                ks::SceneManager::show_dialog("", 474);
                ks::SceneManager::show_dialog("ke", 475);
                ks::SceneManager::show_dialog("", 476);
                ks::SceneManager::show_dialog("ke", 477);
                ks::SceneManager::show_dialog("", 478);
                ks::SceneManager::show_dialog("", 479);
                ks::SceneManager::show_dialog("hi", 480);
                ks::SceneManager::show_dialog("ke", 481);
                ks::SceneManager::show_dialog("", 482);
                ks::SceneManager::show_dialog("ke", 483);
                ks::SceneManager::show_dialog("hi", 484);
                ks::SceneManager::show_dialog("ke", 485);
                ks::SceneManager::show_dialog("ke", 486);
                ks::SceneManager::show_dialog("", 487);
                ks::SceneManager::show_dialog("ke", 488);
                ks::SceneManager::show_dialog("", 489);
                ks::SceneManager::show_dialog("ke", 490);
                ks::SceneManager::show_dialog("", 491);
                ks::SceneManager::show_dialog("ke", 492);
                ks::SceneManager::show_dialog("hi", 493);
                ks::SceneManager::show_dialog("hi", 494);
                ks::SceneManager::show_dialog("", 495);
                ks::SceneManager::show_dialog("ke", 496);
                ks::SceneManager::show_dialog("ke", 497);
                ks::SceneManager::show_dialog("", 498);
                ks::SceneManager::show_dialog("ke", 499);
                ks::SceneManager::show_dialog("hi", 500);
                ks::SceneManager::show_dialog("ke", 501);
                ks::SceneManager::show_dialog("", 502);
                ks::SceneManager::show_dialog("ke", 503);
                ks::SceneManager::show_dialog("hi", 504);
                ks::SceneManager::show_dialog("hi", 505);
                ks::SceneManager::show_dialog("ke", 506);
                ks::SceneManager::show_dialog("", 507);
                ScriptA1TuesdayEn::a1_tuesday_bizarre_and_surreal__menu_question_0();
                ks::SceneManager::show_dialog("ke", 508);
                ks::SceneManager::show_dialog("ke", 509);
                ks::SceneManager::show_dialog("", 510);
                ks::SceneManager::show_dialog("hi", 511);
                ks::SceneManager::show_dialog("ke", 512);
                ks::SceneManager::show_dialog("ke", 513);
                ks::SceneManager::show_dialog("", 514);
                ks::SceneManager::show_dialog("ke", 515);
                ks::SceneManager::show_dialog("ke", 516);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog("ke", 517);
                ks::SceneManager::show_dialog("", 518);
                ks::SceneManager::show_dialog("hi", 519);
                ks::SceneManager::show_dialog("", 520);
                ks::SceneManager::music_play("music_tension.gsm");
                ks::SceneManager::show_dialog("ke", 521);
                ks::SceneManager::show_dialog("ke", 522);
                ks::SceneManager::show_dialog("ke", 523);
                ks::SceneManager::show_dialog("ke", 524);
                ks::SceneManager::show_dialog("ke", 525);
                ks::SceneManager::show_dialog("ke", 526);
                ks::SceneManager::show_dialog("ke", 527);
                ks::SceneManager::show_dialog("", 528);
                ks::SceneManager::show_dialog("ke", 529);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog("hi", 530);
                ks::SceneManager::show_dialog("", 531);
                ks::SceneManager::music_play("music_kenji.gsm");
                ks::SceneManager::show_dialog("ke", 532);
                ks::SceneManager::show_dialog("hi", 533);
                ks::SceneManager::show_dialog("", 534);
                ks::SceneManager::show_dialog("ke", 535);
                ks::SceneManager::show_dialog("ke", 536);
                ks::SceneManager::show_dialog("hi", 537);
                ks::SceneManager::show_dialog("ke", 538);
                ks::SceneManager::show_dialog("hi", 539);
                ks::SceneManager::show_dialog("ke", 540);
                ks::SceneManager::show_dialog("", 541);
                ks::SceneManager::show_dialog("", 542);
                ks::SceneManager::show_dialog("ke", 543);
                ks::SceneManager::show_dialog("hi", 544);
                ks::SceneManager::show_dialog("", 545);
                ks::SceneManager::show_dialog("ke", 546);
                ks::SceneManager::show_dialog("ke", 547);
                ks::SceneManager::show_dialog("ke", 548);
                ks::SceneManager::show_dialog("", 549);
                ks::SceneManager::show_dialog("ke", 550);
                ks::SceneManager::show_dialog("ke", 551);
                ks::SceneManager::show_dialog("hi", 552);
                ks::SceneManager::show_dialog("ke", 553);
                ks::SceneManager::show_dialog("ke", 554);
                ks::SceneManager::show_dialog("ke", 555);
                ks::SceneManager::show_dialog("ke", 556);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog("", 557);
                ks::SceneManager::set_background(bn::regular_bg_items::school_dormhisao_ss);
                ks::SceneManager::show_dialog("", 558);
                ks::SceneManager::show_dialog("", 559);
                ks::SceneManager::show_dialog("", 560);
                ks::SceneManager::show_dialog("", 561);
                ks::SceneManager::show_dialog("", 562);
                ks::SceneManager::show_dialog("hi", 563);
                ks::SceneManager::show_dialog("", 564);
                ks::SceneManager::show_dialog("", 565);
                ks::SceneManager::show_dialog("", 566);
                ks::SceneManager::show_dialog("", 567);
                ks::SceneManager::show_dialog("", 568);
                if (ks::in_replay) {
                    ScriptA1TuesdayEn::a1_tuesday_bizarre_and_surreal__condition_0_0();
                } 
                
            
            }
            static void a1_tuesday() {
                ks::SceneManager::set(ks::SceneManager("script_a1_tuesday", "en", script_a1_tuesday_en_intl));
            
                a1_tuesday_smalltalk();
                a1_tuesday_risk_vs_reward();
                a1_tuesday_pseudo_tea_cosy();
                a1_tuesday_shared_library();
                a1_tuesday_bizarre_and_surreal();
            }
            static void a1c3o1() {
                ks::SceneManager::show_dialog("", 569);
                ks::SceneManager::show_dialog("", 570);
                ks::SceneManager::show_dialog("", 571);
                ks::SceneManager::show_dialog("", 572);
                ks::SceneManager::show_dialog("", 573);
                ks::SceneManager::show_dialog("", 574);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog("", 575);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_grin, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog("mi", 576);
                ks::SceneManager::show_dialog("hi", 577);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 578);
                ks::SceneManager::show_dialog("mi", 579);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("mi", 580);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog("mi", 581);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_dialog("mi", 582);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("mi", 583);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_dialog("mi", 25);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal2, ks::sprite_metas::shizu_basic);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog("", 584);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 585);
                ks::SceneManager::show_dialog("", 586);
                ks::SceneManager::show_dialog("", 587);
                ks::SceneManager::show_dialog("", 588);
                ks::SceneManager::show_dialog("", 589);
                ks::SceneManager::show_dialog("", 590);
                ks::SceneManager::show_dialog("hi", 591);
                ks::SceneManager::music_play("music_shizune.gsm");
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_frown, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 592);
                ks::SceneManager::show_dialog("hi", 593);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("mi", 594);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 595);
                ks::SceneManager::show_dialog("hi", 596);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_sparkle, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog("", 597);
                return;
            }
            static void a1c3o2() {
                ks::SceneManager::show_dialog("", 598);
                ks::SceneManager::show_dialog("", 599);
                ks::SceneManager::show_dialog("", 600);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog("", 575);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 601);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("mi", 602);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("mi", 603);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frustrated, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_dialog("mi", 604);
                ks::SceneManager::show_dialog("mi", 605);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_frown, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_dialog("mi", 606);
                ks::SceneManager::show_dialog("mi", 607);
                ks::SceneManager::show_dialog("", 608);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal2, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_dialog("mi", 609);
                ks::SceneManager::music_play("music_normal.gsm");
                ks::SceneManager::show_dialog("", 610);
                ks::SceneManager::show_dialog("hi", 611);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_dialog("mi", 612);
                ks::SceneManager::show_dialog("", 613);
                ks::SceneManager::show_dialog("", 614);
                ks::SceneManager::show_dialog("", 615);
                ks::SceneManager::show_dialog("hi", 616);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("mi", 617);
                ks::SceneManager::show_dialog("hi", 618);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_sad, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("mi", 619);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("mi", 620);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_angry, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_smile, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog("mi", 621);
                ks::SceneManager::show_dialog("hi", 622);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog("shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog("mi", 623);
                ks::SceneManager::show_dialog("hi", 624);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_sad, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog("mi", 625);
                return;
            }
            static void a1c4o1() {
                ks::SceneManager::show_dialog("hi", 626);
                ks::SceneManager::show_dialog("", 25);
                ks::SceneManager::show_dialog("hi", 627);
                ks::SceneManager::show_dialog("", 25);
                if (ks::progress.wanted_introduce || ks::in_replay) {
                    ScriptA1TuesdayEn::a1c4o1__condition_0_0();
                } 
                
            
                ks::SceneManager::set_background(bn::regular_bg_items::hana_library);
                ks::SceneManager::show_dialog("", 628);
                ks::SceneManager::show_dialog("hi", 629);
                ks::SceneManager::show_dialog("hi", 630);
                ks::SceneManager::show_dialog("ha_", 631);
                ks::SceneManager::show_dialog("", 632);
                ks::SceneManager::show_dialog("", 633);
                ks::SceneManager::show_dialog("hi", 634);
                ks::SceneManager::set_background(bn::regular_bg_items::school_library_ss);
                ks::SceneManager::show_dialog("", 635);
                ks::SceneManager::show_dialog("", 636);
                ks::SceneManager::show_dialog("hi", 637);
                ks::SceneManager::show_dialog("ha", 638);
                ks::SceneManager::show_dialog("ha", 639);
                ks::SceneManager::show_dialog("", 640);
                ks::SceneManager::show_dialog("hi", 641);
                ks::SceneManager::show_dialog("", 642);
                ks::SceneManager::show_dialog("", 643);
                ks::SceneManager::show_dialog("", 644);
                ks::SceneManager::show_dialog("", 645);
                ks::SceneManager::show_dialog("hi", 646);
                ks::SceneManager::show_dialog("ha", 647);
                ks::SceneManager::show_dialog("hi", 648);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog("", 25);
                ks::SceneManager::show_dialog("", 649);
                ks::SceneManager::show_dialog("", 650);
                ks::SceneManager::show_dialog("hi", 651);
                return;
            }
            static void a1c4o2() {
                ks::SceneManager::show_dialog("hi", 652);
                ks::SceneManager::show_dialog("ha_", 653);
                ks::SceneManager::show_dialog("", 654);
                ks::SceneManager::show_dialog("hi", 655);
                ks::SceneManager::show_dialog("", 656);
                ks::SceneManager::set_background(bn::regular_bg_items::hana_library);
                ks::SceneManager::show_dialog("ha_", 657);
                ks::SceneManager::show_dialog("", 658);
                ks::SceneManager::show_dialog("", 659);
                ks::SceneManager::show_dialog("hi", 660);
                ks::SceneManager::show_dialog("", 661);
                ks::SceneManager::show_dialog("ha_", 662);
                ks::SceneManager::show_dialog("ha_", 663);
                ks::SceneManager::show_dialog("", 664);
                ks::SceneManager::show_dialog("", 633);
                ks::SceneManager::show_dialog("ha_", 665);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog("", 25);
                ks::SceneManager::show_dialog("", 666);
                ks::SceneManager::show_dialog("", 667);
                ks::SceneManager::show_dialog("hi", 668);
                ks::SceneManager::show_dialog("", 669);
                ks::SceneManager::show_dialog("", 25);
                ks::SceneManager::show_dialog("", 670);
                ks::SceneManager::show_dialog("", 671);
                ks::SceneManager::show_dialog("", 672);
                ks::SceneManager::show_dialog("", 673);
                ks::SceneManager::show_dialog("", 674);
                ks::SceneManager::show_dialog("", 675);
                ks::SceneManager::set_background(bn::regular_bg_items::school_library_ss);
                ks::SceneManager::show_dialog("", 676);
                return;
            }
            static void a1c5o1() {
                ks::SceneManager::show_dialog("hi", 677);
                ks::SceneManager::show_dialog("ke", 678);
                return;
            }
            static void a1c5o2() {
                ks::SceneManager::show_dialog("hi", 679);
                ks::SceneManager::show_dialog("ke", 680);
                return;
            }
            static void a1_tuesday_risk_vs_reward__menu_question_0() {
                ks::SceneManager::show_dialog("mi", 681);
                bn::vector<int, 5> answers;
                answers.push_back(682);
                answers.push_back(683);
                ks::SceneManager::show_dialog_question(answers);
                int answer = ks::SceneManager::get_dialog_question_answer();
                if (answer == 0) {
                    ScriptA1TuesdayEn::a1_tuesday_risk_vs_reward__menu_question_0_she_has_a_point_attack_aggressively();
                } else if (answer == 1) {
                    ScriptA1TuesdayEn::a1_tuesday_risk_vs_reward__menu_question_0_its_a_trap_its_smarter_to_play_defensively_here();
                }
            }
            static void a1_tuesday_risk_vs_reward__menu_question_0_she_has_a_point_attack_aggressively() {
                ks::progress.attraction_sc += 1;
                ScriptA1TuesdayEn::a1c3o1();
            }
            static void a1_tuesday_risk_vs_reward__menu_question_0_its_a_trap_its_smarter_to_play_defensively_here() {
                ScriptA1TuesdayEn::a1c3o2();
            }
            static void a1_tuesday_shared_library__menu_question_0() {
                bn::vector<int, 5> answers;
                answers.push_back(626);
                answers.push_back(684);
                ks::SceneManager::show_dialog_question(answers);
                int answer = ks::SceneManager::get_dialog_question_answer();
                if (answer == 0) {
                    ScriptA1TuesdayEn::a1_tuesday_shared_library__menu_question_0_hi_im_new_here_hisao_nakai_were_in_the_same_class();
                } else if (answer == 1) {
                    ScriptA1TuesdayEn::a1_tuesday_shared_library__menu_question_0_im_sorry_i_didnt_mean_to_startle_you();
                }
            }
            static void a1_tuesday_shared_library__menu_question_0_hi_im_new_here_hisao_nakai_were_in_the_same_class() {
                ks::progress.im_new_here = true;
                ScriptA1TuesdayEn::a1c4o1();
            }
            static void a1_tuesday_shared_library__menu_question_0_im_sorry_i_didnt_mean_to_startle_you() {
                ks::progress.attraction_hanako += 1;
                ScriptA1TuesdayEn::a1c4o2();
            }
            static void a1_tuesday_bizarre_and_surreal__menu_question_0() {
                bn::vector<int, 5> answers;
                answers.push_back(685);
                answers.push_back(686);
                ks::SceneManager::show_dialog_question(answers);
                int answer = ks::SceneManager::get_dialog_question_answer();
                if (answer == 0) {
                    ScriptA1TuesdayEn::a1_tuesday_bizarre_and_surreal__menu_question_0_she_was_cute();
                } else if (answer == 1) {
                    ScriptA1TuesdayEn::a1_tuesday_bizarre_and_surreal__menu_question_0_she_wasnt_cute();
                }
            }
            static void a1_tuesday_bizarre_and_surreal__menu_question_0_she_was_cute() {
                ks::progress.attraction_hanako += 1;
                ScriptA1TuesdayEn::a1c5o1();
            }
            static void a1_tuesday_bizarre_and_surreal__menu_question_0_she_wasnt_cute() {
                ScriptA1TuesdayEn::a1c5o2();
            }
            static void a1_tuesday_smalltalk__condition_0_0() {
                return;
            }
            static void a1_tuesday_risk_vs_reward__condition_0_0() {
                return;
            }
            static void a1_tuesday_pseudo_tea_cosy__condition_0_0() {
                return;
            }
            static void a1_tuesday_shared_library__condition_0_0() {
                ks::SceneManager::show_dialog("hi", 687);
                ks::SceneManager::show_dialog("", 688);
                ks::SceneManager::show_dialog("yu", 689);
                ks::SceneManager::show_dialog("hi", 690);
                ks::SceneManager::show_dialog("yu", 691);
                ks::SceneManager::show_dialog("hi", 692);
                ks::SceneManager::show_dialog("yu", 693);
                ks::SceneManager::show_dialog("", 694);
                ks::SceneManager::show_dialog("", 695);
                ks::SceneManager::show_dialog("", 696);
            }
            static void a1_tuesday_shared_library__condition_0_1() {
                ks::SceneManager::show_dialog("hi", 697);
                ks::SceneManager::show_dialog("hi", 698);
                ks::SceneManager::show_dialog("yu", 699);
                ks::SceneManager::show_dialog("yu", 700);
                ks::SceneManager::show_dialog("hi", 692);
                ks::SceneManager::show_dialog("yu", 693);
                ks::SceneManager::show_dialog("", 694);
                ks::SceneManager::show_dialog("", 695);
            }
            static void a1_tuesday_shared_library__condition_1_0() {
                return;
            }
            static void a1_tuesday_bizarre_and_surreal__condition_0_0() {
                return;
            }
            static void a1c4o1__condition_0_0() {
                ks::SceneManager::show_dialog("hi", 701);
                ks::SceneManager::show_dialog("", 25);
            }
    };
}