#include "script_a1_monday.h"
#include "script_a1_monday_en_tl_index.h"
namespace ks {
    class ScriptA1MondayEn : public ScriptA1Monday {
        public:
            static void a1_monday_out_cold() {
                // POTENTIAL MEMLEAK!!!! better to provide it globally.
                // bn::optional<bn::regular_bg_ptr> main_bg;
                constexpr ks::SceneManager scene = ks::SceneManager("script_a1_monday", "en", script_a1_monday_en_intl);
            
                ks::SceneManager::reset();
                ks::SceneManager::set_background(bn::regular_bg_items::op_snowywoods);
                ks::SceneManager::music_play("music_serene.gsm");
                ks::SceneManager::show_dialog(&scene, "", 0);
                ks::SceneManager::show_dialog(&scene, "", 1);
                ks::SceneManager::show_dialog(&scene, "", 2);
                ks::SceneManager::show_dialog(&scene, "", 3);
                ks::SceneManager::show_dialog(&scene, "hi", 4);
                ks::SceneManager::show_dialog(&scene, "", 5);
                ks::SceneManager::show_dialog(&scene, "", 6);
                ks::SceneManager::show_dialog(&scene, "", 7);
                ks::SceneManager::show_dialog(&scene, "", 8);
                ks::SceneManager::show_dialog(&scene, "", 9);
                ks::SceneManager::show_dialog(&scene, "", 10);
                ks::SceneManager::show_dialog(&scene, "mystery", 11);
                ks::SceneManager::show_dialog(&scene, "", 12);
                ks::SceneManager::show_dialog(&scene, "", 13);
                ks::SceneManager::show_dialog(&scene, "", 14);
                ks::SceneManager::show_dialog(&scene, "", 15);
                ks::SceneManager::show_dialog(&scene, "", 16);
                ks::SceneManager::set_background(bn::regular_bg_items::other_iwanako);
                ks::SceneManager::show_dialog(&scene, "hi", 17);
                ks::SceneManager::show_dialog(&scene, "", 18);
                ks::SceneManager::show_dialog(&scene, "", 19);
                ks::SceneManager::show_dialog(&scene, "Iwanako", 20);
                ks::SceneManager::show_dialog(&scene, "", 21);
                ks::SceneManager::music_stop();
                ks::SceneManager::set_background(bn::regular_bg_items::op_snowywoods);
                ks::SceneManager::show_dialog(&scene, "", 22);
                ks::SceneManager::set_background(bn::regular_bg_items::other_iwanako);
                ks::SceneManager::show_dialog(&scene, "hi", 23);
                ks::SceneManager::show_dialog(&scene, "", 24);
                ks::SceneManager::show_dialog(&scene, "", 25);
                ks::SceneManager::show_dialog(&scene, "", 26);
                ks::SceneManager::show_dialog(&scene, "", 27);
                ks::SceneManager::show_dialog(&scene, "", 28);
                ks::SceneManager::set_background(bn::regular_bg_items::op_snowywoods);
                ks::SceneManager::show_dialog(&scene, "", 29);
                ks::SceneManager::show_dialog(&scene, "Iwanako", 30);
                ks::SceneManager::show_dialog(&scene, "Iwanako", 31);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "Iwanako", 32);
                ks::SceneManager::show_dialog(&scene, "", 33);
                ks::SceneManager::show_dialog(&scene, "", 34);
                ks::SceneManager::music_play("music_tragic.gsm");
                ks::SceneManager::show_dialog(&scene, "Iwanako", 35);
                ks::SceneManager::show_dialog(&scene, "", 36);
                ks::SceneManager::show_dialog(&scene, "Iwanako", 37);
                ks::SceneManager::show_dialog(&scene, "", 38);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "Iwanako", 39);
                ks::SceneManager::show_dialog(&scene, "", 40);
                ks::SceneManager::show_dialog(&scene, "n", 41);
                ks::SceneManager::show_dialog(&scene, "n", 42);
                // bn::vector<ks::ConditionItem, 1> a1_monday_out_cold__condition_0;
                // a1_monday_out_cold__condition_0.push_back(ks::ConditionItem("_in_replay", &ScriptA1MondayEn::a1_monday_out_cold__condition_0_0));
                // scene.add_condition(a1_monday_out_cold__condition_0);
            }
            static void a1_monday_bundle_of_hisao() {
                // POTENTIAL MEMLEAK!!!! better to provide it globally.
                // bn::optional<bn::regular_bg_ptr> main_bg;
                constexpr ks::SceneManager scene = ks::SceneManager("script_a1_monday", "en", script_a1_monday_en_intl);
            
                ks::SceneManager::reset();
                ks::SceneManager::show_dialog(&scene, "centered", 43);
                ks::SceneManager::set_background(bn::regular_bg_items::hosp_room);
                // scene.add_sequence(ks::AssignmentItem("renpy.music.set_volume(0.5, 0.0, channel="music")"));
                ks::SceneManager::music_play("music_rain.gsm");
                ks::SceneManager::show_dialog(&scene, "n", 44);
                ks::SceneManager::show_dialog(&scene, "n", 45);
                ks::SceneManager::show_dialog(&scene, "n", 46);
                ks::SceneManager::show_dialog(&scene, "n", 47);
                ks::SceneManager::show_dialog(&scene, "n", 48);
                ks::SceneManager::show_dialog(&scene, "n", 49);
                ks::SceneManager::show_dialog(&scene, "n", 50);
                ks::SceneManager::show_dialog(&scene, "n", 51);
                ks::SceneManager::show_dialog(&scene, "n", 52);
                ks::SceneManager::show_dialog(&scene, "n", 53);
                ks::SceneManager::show_dialog(&scene, "n", 54);
                ks::SceneManager::show_dialog(&scene, "n", 55);
                ks::SceneManager::show_dialog(&scene, "n", 56);
                ks::SceneManager::show_dialog(&scene, "n", 57);
                ks::SceneManager::show_dialog(&scene, "n", 58);
                ks::SceneManager::show_dialog(&scene, "n", 59);
                ks::SceneManager::show_dialog(&scene, "n", 60);
                ks::SceneManager::show_dialog(&scene, "n", 61);
                ks::SceneManager::show_dialog(&scene, "n", 62);
                ks::SceneManager::show_dialog(&scene, "n", 63);
                ks::SceneManager::show_dialog(&scene, "n", 64);
                ks::SceneManager::show_dialog(&scene, "n", 65);
                ks::SceneManager::show_dialog(&scene, "n", 66);
                ks::SceneManager::show_dialog(&scene, "n", 67);
                ks::SceneManager::show_dialog(&scene, "n", 68);
                ks::SceneManager::show_dialog(&scene, "n", 69);
                ks::SceneManager::show_dialog(&scene, "n", 70);
                ks::SceneManager::show_dialog(&scene, "n", 71);
                ks::SceneManager::show_dialog(&scene, "n", 72);
                ks::SceneManager::show_dialog(&scene, "n", 73);
                ks::SceneManager::show_dialog(&scene, "n", 74);
                ks::SceneManager::show_dialog(&scene, "n", 75);
                ks::SceneManager::show_dialog(&scene, "n", 76);
                ks::SceneManager::show_dialog(&scene, "n", 77);
                ks::SceneManager::show_dialog(&scene, "n", 78);
                ks::SceneManager::show_dialog(&scene, "n", 79);
                ks::SceneManager::show_dialog(&scene, "n", 80);
                ks::SceneManager::show_dialog(&scene, "n", 81);
                ks::SceneManager::show_dialog(&scene, "n", 82);
                ks::SceneManager::show_dialog(&scene, "n", 83);
                ks::SceneManager::show_dialog(&scene, "n", 84);
                // scene.add_sequence(ks::AssignmentItem("renpy.music.set_volume(1.0, 1.0, channel="music")"));
                ks::SceneManager::show_dialog(&scene, "", 85);
                ks::SceneManager::show_dialog(&scene, "", 86);
                ks::SceneManager::show_dialog(&scene, "", 87);
                ks::SceneManager::show_dialog(&scene, "", 88);
                ks::SceneManager::show_dialog(&scene, "Doctor", 89);
                ks::SceneManager::show_dialog(&scene, "", 90);
                ks::SceneManager::show_dialog(&scene, "Doctor", 91);
                ks::SceneManager::show_dialog(&scene, "Doctor", 92);
                ks::SceneManager::show_dialog(&scene, "", 93);
                ks::SceneManager::show_dialog(&scene, "Dad", 94);
                ks::SceneManager::show_dialog(&scene, "", 95);
                // scene.add_sequence(ks::AssignmentItem("renpy.music.set_volume(0.5, 2.0, channel="music")"));
                ks::SceneManager::show_dialog(&scene, "", 96);
                ks::SceneManager::show_dialog(&scene, "", 97);
                ks::SceneManager::show_dialog(&scene, "", 98);
                ks::SceneManager::show_dialog(&scene, "", 99);
                ks::SceneManager::show_dialog(&scene, "", 100);
                ks::SceneManager::show_dialog(&scene, "", 101);
                // scene.add_sequence(ks::AssignmentItem("renpy.music.set_volume(1.0, 1.0, channel="music")"));
                ks::SceneManager::set_background(bn::regular_bg_items::hosp_room);
                ks::SceneManager::show_dialog(&scene, "Doctor", 102);
                ks::SceneManager::show_dialog(&scene, "Doctor", 103);
                ks::SceneManager::show_dialog(&scene, "", 104);
                ks::SceneManager::show_dialog(&scene, "Doctor", 105);
                ks::SceneManager::show_dialog(&scene, "", 106);
                ks::SceneManager::show_dialog(&scene, "Dad", 107);
                ks::SceneManager::show_dialog(&scene, "", 108);
                ks::SceneManager::show_dialog(&scene, "", 109);
                ks::SceneManager::show_dialog(&scene, "Doctor", 110);
                ks::SceneManager::show_dialog(&scene, "Doctor", 111);
                ks::SceneManager::show_dialog(&scene, "Doctor", 112);
                ks::SceneManager::show_dialog(&scene, "Doctor", 113);
                ks::SceneManager::show_dialog(&scene, "", 114);
                ks::SceneManager::show_dialog(&scene, "Doctor", 115);
                ks::SceneManager::show_dialog(&scene, "Doctor", 116);
                ks::SceneManager::show_dialog(&scene, "", 117);
                ks::SceneManager::show_dialog(&scene, "", 118);
                ks::SceneManager::show_dialog(&scene, "Dad", 119);
                ks::SceneManager::show_dialog(&scene, "Dad", 120);
                ks::SceneManager::show_dialog(&scene, "", 121);
                ks::SceneManager::show_dialog(&scene, "Doctor", 122);
                ks::SceneManager::show_dialog(&scene, "", 123);
                ks::SceneManager::show_dialog(&scene, "Doctor", 124);
                ks::SceneManager::show_dialog(&scene, "", 125);
                ks::SceneManager::show_dialog(&scene, "", 126);
                ks::SceneManager::show_dialog(&scene, "Dad", 127);
                ks::SceneManager::show_dialog(&scene, "Dad", 128);
                ks::SceneManager::show_dialog(&scene, "Doctor", 129);
                ks::SceneManager::show_dialog(&scene, "Doctor", 130);
                ks::SceneManager::show_dialog(&scene, "", 131);
                ks::SceneManager::show_dialog(&scene, "", 132);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "", 133);
                ks::SceneManager::show_dialog(&scene, "", 134);
                ks::SceneManager::show_dialog(&scene, "", 135);
                ks::SceneManager::show_dialog(&scene, "", 136);
                ks::SceneManager::show_dialog(&scene, "", 137);
                ks::SceneManager::show_dialog(&scene, "", 138);
                ks::SceneManager::show_dialog(&scene, "", 139);
                ks::SceneManager::show_dialog(&scene, "", 140);
                ks::SceneManager::show_dialog(&scene, "", 141);
                // bn::vector<ks::ConditionItem, 1> a1_monday_bundle_of_hisao__condition_0;
                // a1_monday_bundle_of_hisao__condition_0.push_back(ks::ConditionItem("_in_replay", &ScriptA1MondayEn::a1_monday_bundle_of_hisao__condition_0_0));
                // scene.add_condition(a1_monday_bundle_of_hisao__condition_0);
            }
            static void a1_monday_gateway_effect() {
                // POTENTIAL MEMLEAK!!!! better to provide it globally.
                // bn::optional<bn::regular_bg_ptr> main_bg;
                constexpr ks::SceneManager scene = ks::SceneManager("script_a1_monday", "en", script_a1_monday_en_intl);
            
                ks::SceneManager::reset();
                ks::SceneManager::set_background(bn::regular_bg_items::school_gate);
                ks::SceneManager::music_play("music_happiness.gsm");
                ks::SceneManager::show_dialog(&scene, "", 142);
                ks::SceneManager::show_dialog(&scene, "", 143);
                ks::SceneManager::show_dialog(&scene, "", 144);
                ks::SceneManager::show_dialog(&scene, "", 145);
                ks::SceneManager::show_dialog(&scene, "", 146);
                ks::SceneManager::show_dialog(&scene, "", 147);
                ks::SceneManager::set_background(bn::regular_bg_items::school_courtyard);
                ks::SceneManager::show_dialog(&scene, "", 148);
                ks::SceneManager::show_dialog(&scene, "", 149);
                ks::SceneManager::show_dialog(&scene, "", 150);
                ks::SceneManager::show_dialog(&scene, "", 151);
                ks::SceneManager::show_dialog(&scene, "", 152);
                ks::SceneManager::show_dialog(&scene, "", 153);
                ks::SceneManager::show_dialog(&scene, "", 154);
                ks::SceneManager::show_dialog(&scene, "", 155);
                ks::SceneManager::show_dialog(&scene, "", 156);
                ks::SceneManager::show_dialog(&scene, "", 157);
                ks::SceneManager::show_dialog(&scene, "", 158);
                ks::SceneManager::show_dialog(&scene, "", 159);
                ks::SceneManager::show_dialog(&scene, "", 160);
                ks::SceneManager::show_dialog(&scene, "", 161);
                ks::SceneManager::show_dialog(&scene, "", 162);
                ks::SceneManager::show_dialog(&scene, "", 163);
                ks::SceneManager::show_dialog(&scene, "", 164);
                ks::SceneManager::show_dialog(&scene, "", 165);
                ks::SceneManager::show_dialog(&scene, "", 166);
                ks::SceneManager::show_dialog(&scene, "", 167);
                ks::SceneManager::set_background(bn::regular_bg_items::school_lobby);
                ks::SceneManager::show_dialog(&scene, "", 168);
                ks::SceneManager::show_dialog(&scene, "mu_", 169);
                ks::SceneManager::show_dialog(&scene, "hi", 170);
                ks::SceneManager::show_dialog(&scene, "mu_", 171);
                ks::SceneManager::show_dialog(&scene, "mu", 172);
                ks::SceneManager::show_dialog(&scene, "", 173);
                ks::SceneManager::show_dialog(&scene, "mu", 174);
                ks::SceneManager::show_dialog(&scene, "hi", 175);
                ks::SceneManager::show_dialog(&scene, "mu", 176);
                ks::SceneManager::show_dialog(&scene, "", 177);
                ks::SceneManager::show_dialog(&scene, "", 178);
                ks::SceneManager::show_dialog(&scene, "", 179);
                ScriptA1MondayEn::a1_monday_gateway_effect__menu_question_0(scene);
                ks::SceneManager::set_background(bn::regular_bg_items::school_staircase2);
                ks::SceneManager::show_dialog(&scene, "", 180);
                ks::SceneManager::set_background(bn::regular_bg_items::school_hallway3);
                ks::SceneManager::show_dialog(&scene, "", 181);
                ks::SceneManager::show_dialog(&scene, "", 182);
                ks::SceneManager::show_dialog(&scene, "mu", 183);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "", 184);
                // bn::vector<ks::ConditionItem, 1> a1_monday_gateway_effect__condition_0;
                // a1_monday_gateway_effect__condition_0.push_back(ks::ConditionItem("_in_replay", &ScriptA1MondayEn::a1_monday_gateway_effect__condition_0_0));
                // scene.add_condition(a1_monday_gateway_effect__condition_0);
            }
            static void a1_monday_enter_stage_left() {
                // POTENTIAL MEMLEAK!!!! better to provide it globally.
                // bn::optional<bn::regular_bg_ptr> main_bg;
                constexpr ks::SceneManager scene = ks::SceneManager("script_a1_monday", "en", script_a1_monday_en_intl);
            
                ks::SceneManager::reset();
                ks::SceneManager::set_background(bn::regular_bg_items::school_hallway3);
                ks::SceneManager::show_dialog(&scene, "", 185);
                ks::SceneManager::set_background(bn::regular_bg_items::hisao_class);
                ks::SceneManager::music_play("music_normal.gsm");
                ks::SceneManager::show_dialog(&scene, "", 186);
                ks::SceneManager::show_dialog(&scene, "", 187);
                ks::SceneManager::show_dialog(&scene, "", 188);
                ks::SceneManager::show_dialog(&scene, "", 189);
                ks::SceneManager::show_dialog(&scene, "", 190);
                ks::SceneManager::set_background(bn::regular_bg_items::hisao_class);
                ks::SceneManager::show_dialog(&scene, "", 191);
                ks::SceneManager::show_dialog(&scene, "", 192);
                ks::SceneManager::show_dialog(&scene, "", 193);
                ks::SceneManager::show_dialog(&scene, "", 194);
                ks::SceneManager::show_dialog(&scene, "", 195);
                ks::SceneManager::show_dialog(&scene, "", 196);
                ks::SceneManager::show_dialog(&scene, "mu", 197);
                ks::SceneManager::show_dialog(&scene, "", 198);
                // bn::vector<ks::ConditionItem, 2> a1_monday_enter_stage_left__condition_0;
                // a1_monday_enter_stage_left__condition_0.push_back(ks::ConditionItem("wanted_introduce or _in_replay", &ScriptA1MondayEn::a1_monday_enter_stage_left__condition_0_0));
                // a1_monday_enter_stage_left__condition_0.push_back(ks::ConditionItem("None", &ScriptA1MondayEn::a1_monday_enter_stage_left__condition_0_1));
                // scene.add_condition(a1_monday_enter_stage_left__condition_0);
                ks::SceneManager::set_background(bn::regular_bg_items::hisao_class);
                ks::SceneManager::show_dialog(&scene, "", 199);
                ks::SceneManager::show_dialog(&scene, "", 200);
                ks::SceneManager::show_dialog(&scene, "", 201);
                ks::SceneManager::show_dialog(&scene, "", 202);
                ks::SceneManager::set_background(bn::regular_bg_items::school_scienceroom);
                ks::SceneManager::show_dialog(&scene, "mu", 203);
                ks::SceneManager::show_dialog(&scene, "hi", 204);
                ks::SceneManager::show_dialog(&scene, "mu", 205);
                ks::SceneManager::show_dialog(&scene, "mu", 206);
                ks::SceneManager::show_dialog(&scene, "", 207);
                ks::SceneManager::show_dialog(&scene, "", 208);
                ks::SceneManager::show_dialog(&scene, "", 209);
                ks::SceneManager::show_dialog(&scene, "mu", 210);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "", 211);
                ks::SceneManager::show_dialog(&scene, "hi", 212);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_laugh, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi_shi", 213);
                ks::SceneManager::show_dialog(&scene, "", 214);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi_shi", 215);
                ks::SceneManager::show_dialog(&scene, "mi_not_shi", 216);
                ks::SceneManager::music_play("music_shizune.gsm");
                ks::SceneManager::set_character_position(0, -48, 0);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal, ks::sprite_metas::shizu_basic, 48, 0);
                ks::SceneManager::show_dialog(&scene, "", 217);
                ks::SceneManager::show_dialog(&scene, "", 218);
                ks::SceneManager::show_dialog(&scene, "hi", 219);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 163);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_smile, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "", 220);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "", 221);
                ks::SceneManager::show_dialog(&scene, "", 222);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 223);
                ks::SceneManager::show_dialog(&scene, "mi", 224);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 225);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal2, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 163);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 226);
                // bn::vector<ks::ConditionItem, 2> a1_monday_enter_stage_left__condition_1;
                // a1_monday_enter_stage_left__condition_1.push_back(ks::ConditionItem("wanted_introduce or _in_replay", &ScriptA1MondayEn::a1_monday_enter_stage_left__condition_1_0));
                // a1_monday_enter_stage_left__condition_1.push_back(ks::ConditionItem("None", &ScriptA1MondayEn::a1_monday_enter_stage_left__condition_1_1));
                // scene.add_condition(a1_monday_enter_stage_left__condition_1);
                ks::SceneManager::show_dialog(&scene, "mi", 227);
                ks::SceneManager::show_dialog(&scene, "", 228);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 229);
                ks::SceneManager::show_dialog(&scene, "", 230);
                ks::SceneManager::show_dialog(&scene, "hi", 231);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_grin, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi", 232);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 163);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_laugh, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "mi", 233);
                ks::SceneManager::show_dialog(&scene, "hi", 234);
                ks::SceneManager::show_dialog(&scene, "shi", 163);
                ks::SceneManager::show_dialog(&scene, "", 235);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_smile, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "", 236);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 237);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 238);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 163);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_smile, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog(&scene, "mi", 239);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "extend", 240);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "extend", 241);
                ks::SceneManager::show_dialog(&scene, "", 242);
                ks::SceneManager::show_dialog(&scene, "hi", 243);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 163);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_laugh, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 213);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 244);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 245);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "", 246);
                ks::SceneManager::show_dialog(&scene, "", 247);
                ks::SceneManager::show_dialog(&scene, "", 248);
                ks::SceneManager::show_dialog(&scene, "", 249);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_sad, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 250);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 163);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 251);
                ks::SceneManager::show_dialog(&scene, "mi", 252);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_laugh, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi", 253);
                ks::SceneManager::show_dialog(&scene, "hi", 254);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 163);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 255);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_blush, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 163);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 256);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal2, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 163);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::music_play("music_shizune.gsm");
                ks::SceneManager::show_dialog(&scene, "mi", 257);
                ks::SceneManager::show_dialog(&scene, "hi", 258);
                ks::SceneManager::show_dialog(&scene, "", 259);
                ks::SceneManager::show_dialog(&scene, "", 260);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 261);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 262);
                ks::SceneManager::show_dialog(&scene, "hi", 263);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_laugh, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 264);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_frown, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 163);
                ks::SceneManager::show_dialog(&scene, "", 265);
                ks::SceneManager::show_dialog(&scene, "hi", 266);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 163);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 267);
                ks::SceneManager::show_dialog(&scene, "", 268);
                ks::SceneManager::music_stop();
                ks::SceneManager::set_background(bn::regular_bg_items::school_scienceroom);
                ks::SceneManager::show_dialog(&scene, "", 269);
                ks::SceneManager::show_dialog(&scene, "", 270);
                ks::SceneManager::show_dialog(&scene, "", 271);
                ks::SceneManager::show_dialog(&scene, "", 272);
                ks::SceneManager::set_background(bn::regular_bg_items::school_hallway3);
                ks::SceneManager::show_dialog(&scene, "", 273);
                // bn::vector<ks::ConditionItem, 1> a1_monday_enter_stage_left__condition_2;
                // a1_monday_enter_stage_left__condition_2.push_back(ks::ConditionItem("_in_replay", &ScriptA1MondayEn::a1_monday_enter_stage_left__condition_2_0));
                // scene.add_condition(a1_monday_enter_stage_left__condition_2);
            }
            static void a1_monday_in_the_nursery() {
                // POTENTIAL MEMLEAK!!!! better to provide it globally.
                // bn::optional<bn::regular_bg_ptr> main_bg;
                constexpr ks::SceneManager scene = ks::SceneManager("script_a1_monday", "en", script_a1_monday_en_intl);
            
                ks::SceneManager::reset();
                ks::SceneManager::set_background(bn::regular_bg_items::school_staircase2);
                ks::SceneManager::show_dialog(&scene, "", 274);
                ks::SceneManager::set_background(bn::regular_bg_items::school_cafeteria);
                ks::SceneManager::show_dialog(&scene, "", 275);
                ks::SceneManager::show_dialog(&scene, "", 276);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::music_play("music_ease.gsm");
                ks::SceneManager::show_dialog(&scene, "mi", 277);
                ks::SceneManager::show_dialog(&scene, "", 278);
                ks::SceneManager::hide_character(0);
                ks::SceneManager::show_dialog(&scene, "", 279);
                ks::SceneManager::show_dialog(&scene, "", 280);
                ks::SceneManager::show_dialog(&scene, "", 281);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_frown, ks::sprite_metas::misha_hips, -48, 0);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal, ks::sprite_metas::shizu_basic, 48, 0);
                ks::SceneManager::show_dialog(&scene, "", 282);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_frown, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 163);
                ks::SceneManager::show_dialog(&scene, "", 283);
                ks::SceneManager::show_dialog(&scene, "", 284);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "mi", 285);
                ks::SceneManager::show_dialog(&scene, "hi", 286);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 287);
                ScriptA1MondayEn::a1_monday_in_the_nursery__menu_question_0(scene);
                ks::SceneManager::show_dialog(&scene, "", 288);
                ks::SceneManager::show_dialog(&scene, "", 289);
                ks::SceneManager::show_dialog(&scene, "", 163);
                ks::SceneManager::music_stop();
                // scene.add_sequence(ks::AssignmentItem("renpy.music.set_volume(1.0, .5, channel="ambient")"));
                ks::SceneManager::show_dialog(&scene, "", 290);
                ks::SceneManager::set_background(bn::regular_bg_items::school_scienceroom);
                ks::SceneManager::music_play("music_daily.gsm");
                ks::SceneManager::show_dialog(&scene, "", 291);
                ks::SceneManager::show_dialog(&scene, "", 292);
                ks::SceneManager::show_dialog(&scene, "", 293);
                ks::SceneManager::show_dialog(&scene, "", 294);
                ks::SceneManager::show_dialog(&scene, "", 295);
                ks::SceneManager::show_dialog(&scene, "", 296);
                ks::SceneManager::show_dialog(&scene, "", 297);
                ks::SceneManager::show_dialog(&scene, "", 298);
                ks::SceneManager::show_dialog(&scene, "", 299);
                ks::SceneManager::show_dialog(&scene, "", 300);
                ks::SceneManager::set_background(bn::regular_bg_items::school_scienceroom);
                ks::SceneManager::show_dialog(&scene, "", 301);
                ks::SceneManager::show_dialog(&scene, "", 302);
                ks::SceneManager::show_dialog(&scene, "", 303);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind, 48, 0);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky, -48, 0);
                ks::SceneManager::show_dialog(&scene, "shi", 163);
                ks::SceneManager::show_dialog(&scene, "mi", 304);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal2, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 163);
                ks::SceneManager::show_dialog(&scene, "mi", 305);
                ks::SceneManager::show_dialog(&scene, "hi", 306);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 307);
                ks::SceneManager::show_dialog(&scene, "mi", 308);
                ks::SceneManager::hide_character(1);
                ks::SceneManager::hide_character(0);
                ks::SceneManager::set_background(bn::regular_bg_items::school_hallway3);
                ks::SceneManager::show_dialog(&scene, "", 309);
                ks::SceneManager::set_background(bn::regular_bg_items::school_courtyard);
                ks::SceneManager::show_dialog(&scene, "", 310);
                ks::SceneManager::show_dialog(&scene, "", 311);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind, 48, 0);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky, -48, 0);
                ks::SceneManager::show_dialog(&scene, "shi", 163);
                ks::SceneManager::show_dialog(&scene, "mi", 312);
                ks::SceneManager::show_dialog(&scene, "hi", 313);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frustrated, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 163);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 314);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_smile, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog(&scene, "mi", 315);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "mi", 316);
                ks::SceneManager::show_dialog(&scene, "hi", 317);
                ks::SceneManager::music_stop();
                ks::SceneManager::hide_character(1);
                ks::SceneManager::hide_character(0);
                ks::SceneManager::show_dialog(&scene, "", 318);
                ks::SceneManager::show_dialog(&scene, "", 319);
                ks::SceneManager::set_background(bn::regular_bg_items::school_nursehall);
                ks::SceneManager::show_dialog(&scene, "", 320);
                ks::SceneManager::show_dialog(&scene, "", 321);
                ks::SceneManager::show_dialog(&scene, "", 322);
                ks::SceneManager::show_dialog(&scene, "", 323);
                ks::SceneManager::set_background(bn::regular_bg_items::school_nurseoffice);
                ks::SceneManager::show_dialog(&scene, "", 324);
                ks::SceneManager::show_dialog(&scene, "", 325);
                ks::SceneManager::music_play("music_nurse.gsm");
                ks::SceneManager::show_dialog(&scene, "nk_", 326);
                ks::SceneManager::show_dialog(&scene, "", 327);
                ks::SceneManager::show_dialog(&scene, "hi", 328);
                ks::SceneManager::show_dialog(&scene, "", 329);
                ks::SceneManager::show_dialog(&scene, "nk_", 330);
                ks::SceneManager::show_dialog(&scene, "nk_", 331);
                ks::SceneManager::show_dialog(&scene, "", 332);
                ks::SceneManager::show_dialog(&scene, "hi", 333);
                ks::SceneManager::show_dialog(&scene, "", 334);
                ks::SceneManager::show_dialog(&scene, "nk", 335);
                ks::SceneManager::show_dialog(&scene, "nk", 336);
                ks::SceneManager::show_dialog(&scene, "", 337);
                ks::SceneManager::show_dialog(&scene, "hi", 338);
                ks::SceneManager::show_dialog(&scene, "nk", 339);
                ks::SceneManager::show_dialog(&scene, "nk", 340);
                ks::SceneManager::show_dialog(&scene, "nk", 341);
                ks::SceneManager::show_dialog(&scene, "", 342);
                ks::SceneManager::show_dialog(&scene, "hi", 343);
                ks::SceneManager::show_dialog(&scene, "nk", 344);
                ks::SceneManager::show_dialog(&scene, "", 345);
                ks::SceneManager::show_dialog(&scene, "hi", 346);
                ks::SceneManager::show_dialog(&scene, "nk", 347);
                ks::SceneManager::show_dialog(&scene, "", 348);
                ks::SceneManager::show_dialog(&scene, "nk", 349);
                ks::SceneManager::show_dialog(&scene, "", 350);
                ks::SceneManager::show_dialog(&scene, "", 351);
                ks::SceneManager::show_dialog(&scene, "", 352);
                ks::SceneManager::show_dialog(&scene, "", 353);
                ks::SceneManager::show_dialog(&scene, "", 354);
                ks::SceneManager::show_dialog(&scene, "nk", 355);
                ks::SceneManager::show_dialog(&scene, "nk", 356);
                ks::SceneManager::show_dialog(&scene, "", 357);
                ks::SceneManager::show_dialog(&scene, "hi", 358);
                ks::SceneManager::show_dialog(&scene, "nk", 359);
                ks::SceneManager::show_dialog(&scene, "hi", 360);
                ks::SceneManager::show_dialog(&scene, "", 361);
                ks::SceneManager::show_dialog(&scene, "", 362);
                ks::SceneManager::show_dialog(&scene, "nk", 363);
                ks::SceneManager::show_dialog(&scene, "nk", 364);
                ks::SceneManager::show_dialog(&scene, "hi", 365);
                ks::SceneManager::show_dialog(&scene, "", 366);
                ks::SceneManager::show_dialog(&scene, "nk", 367);
                ks::SceneManager::show_dialog(&scene, "nk", 368);
                ks::SceneManager::show_dialog(&scene, "nk", 369);
                ks::SceneManager::show_dialog(&scene, "nk", 370);
                ks::SceneManager::show_dialog(&scene, "hi", 371);
                ks::SceneManager::show_dialog(&scene, "nk", 372);
                ks::SceneManager::show_dialog(&scene, "nk", 373);
                ks::SceneManager::show_dialog(&scene, "", 374);
                ks::SceneManager::show_dialog(&scene, "nk", 375);
                ks::SceneManager::show_dialog(&scene, "hi", 376);
                ks::SceneManager::show_dialog(&scene, "", 377);
                ks::SceneManager::show_dialog(&scene, "nk", 378);
                ks::SceneManager::set_background(bn::regular_bg_items::school_nursehall);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "", 379);
                // bn::vector<ks::ConditionItem, 1> a1_monday_in_the_nursery__condition_0;
                // a1_monday_in_the_nursery__condition_0.push_back(ks::ConditionItem("_in_replay", &ScriptA1MondayEn::a1_monday_in_the_nursery__condition_0_0));
                // scene.add_condition(a1_monday_in_the_nursery__condition_0);
            }
            static void a1_monday_nobodys_room() {
                // POTENTIAL MEMLEAK!!!! better to provide it globally.
                // bn::optional<bn::regular_bg_ptr> main_bg;
                constexpr ks::SceneManager scene = ks::SceneManager("script_a1_monday", "en", script_a1_monday_en_intl);
            
                ks::SceneManager::reset();
                ks::SceneManager::set_background(bn::regular_bg_items::school_courtyard);
                ks::SceneManager::music_play("music_pearly.gsm");
                ks::SceneManager::show_dialog(&scene, "", 380);
                ks::SceneManager::show_dialog(&scene, "", 381);
                ks::SceneManager::show_dialog(&scene, "", 382);
                ks::SceneManager::show_dialog(&scene, "", 383);
                ks::SceneManager::show_dialog(&scene, "", 384);
                ks::SceneManager::show_dialog(&scene, "", 163);
                ks::SceneManager::show_dialog(&scene, "", 385);
                ks::SceneManager::show_dialog(&scene, "", 386);
                ks::SceneManager::show_dialog(&scene, "", 387);
                ks::SceneManager::set_background(bn::regular_bg_items::school_gardens);
                ks::SceneManager::show_dialog(&scene, "", 388);
                ks::SceneManager::show_dialog(&scene, "", 389);
                ks::SceneManager::set_background(bn::regular_bg_items::school_dormext_start);
                ks::SceneManager::show_dialog(&scene, "", 390);
                ks::SceneManager::set_background(bn::regular_bg_items::school_dormhallground);
                ks::SceneManager::show_dialog(&scene, "", 391);
                ks::SceneManager::show_dialog(&scene, "hi", 392);
                ks::SceneManager::show_dialog(&scene, "", 393);
                ks::SceneManager::show_dialog(&scene, "", 394);
                ks::SceneManager::show_dialog(&scene, "", 395);
                ks::SceneManager::show_dialog(&scene, "", 396);
                ks::SceneManager::show_dialog(&scene, "", 397);
                ks::SceneManager::show_dialog(&scene, "", 398);
                ks::SceneManager::show_dialog(&scene, "", 399);
                ks::SceneManager::set_background(bn::regular_bg_items::school_dormhallway);
                ks::SceneManager::show_dialog(&scene, "", 400);
                ks::SceneManager::show_dialog(&scene, "", 401);
                ks::SceneManager::show_dialog(&scene, "", 402);
                ks::SceneManager::show_dialog(&scene, "", 403);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "", 404);
                ks::SceneManager::show_dialog(&scene, "hi", 405);
                ks::SceneManager::show_dialog(&scene, "", 406);
                ks::SceneManager::music_play("music_kenji.gsm");
                ks::SceneManager::show_dialog(&scene, "", 407);
                ks::SceneManager::show_dialog(&scene, "ke_", 408);
                ks::SceneManager::show_dialog(&scene, "", 409);
                ks::SceneManager::show_dialog(&scene, "", 410);
                ks::SceneManager::show_dialog(&scene, "hi", 411);
                ks::SceneManager::show_dialog(&scene, "", 412);
                ks::SceneManager::show_dialog(&scene, "ke_", 413);
                ks::SceneManager::show_dialog(&scene, "hi", 414);
                ks::SceneManager::show_dialog(&scene, "", 415);
                ks::SceneManager::show_dialog(&scene, "ke", 416);
                ks::SceneManager::show_dialog(&scene, "hi", 417);
                ks::SceneManager::show_dialog(&scene, "ke", 418);
                ks::SceneManager::show_dialog(&scene, "", 419);
                ks::SceneManager::show_dialog(&scene, "hi", 420);
                ks::SceneManager::show_dialog(&scene, "", 421);
                ks::SceneManager::show_dialog(&scene, "ke", 422);
                ks::SceneManager::show_dialog(&scene, "ke", 423);
                ks::SceneManager::show_dialog(&scene, "ke", 424);
                ks::SceneManager::show_dialog(&scene, "hi", 425);
                ks::SceneManager::show_dialog(&scene, "", 426);
                ks::SceneManager::show_dialog(&scene, "ke", 427);
                ks::SceneManager::show_dialog(&scene, "ke", 428);
                ks::SceneManager::show_dialog(&scene, "ke", 429);
                ks::SceneManager::show_dialog(&scene, "ke", 430);
                ks::SceneManager::show_dialog(&scene, "", 431);
                ks::SceneManager::show_dialog(&scene, "ke", 432);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "", 433);
                ks::SceneManager::show_dialog(&scene, "extend", 434);
                ks::SceneManager::show_dialog(&scene, "", 435);
                ks::SceneManager::set_background(bn::regular_bg_items::school_dormhisao_ss);
                ks::SceneManager::music_play("music_night.gsm");
                ks::SceneManager::show_dialog(&scene, "", 436);
                ks::SceneManager::show_dialog(&scene, "", 437);
                ks::SceneManager::show_dialog(&scene, "", 438);
                ks::SceneManager::show_dialog(&scene, "", 439);
                ks::SceneManager::show_dialog(&scene, "", 440);
                ks::SceneManager::show_dialog(&scene, "", 441);
                ks::SceneManager::show_dialog(&scene, "", 442);
                ks::SceneManager::show_dialog(&scene, "", 443);
                ks::SceneManager::show_dialog(&scene, "", 444);
                ks::SceneManager::show_dialog(&scene, "", 445);
                ks::SceneManager::show_dialog(&scene, "", 446);
                ks::SceneManager::show_dialog(&scene, "", 447);
                ks::SceneManager::show_dialog(&scene, "", 448);
                ks::SceneManager::show_dialog(&scene, "", 449);
                ks::SceneManager::show_dialog(&scene, "", 450);
                ks::SceneManager::show_dialog(&scene, "", 451);
                ks::SceneManager::show_dialog(&scene, "", 452);
                ks::SceneManager::show_dialog(&scene, "", 453);
                ks::SceneManager::show_dialog(&scene, "", 454);
                ks::SceneManager::show_dialog(&scene, "", 455);
                ks::SceneManager::show_dialog(&scene, "", 456);
                ks::SceneManager::show_dialog(&scene, "", 457);
                ks::SceneManager::show_dialog(&scene, "", 458);
                ks::SceneManager::show_dialog(&scene, "", 459);
                ks::SceneManager::show_dialog(&scene, "", 163);
                ks::SceneManager::show_dialog(&scene, "", 460);
                ks::SceneManager::music_stop();
                ks::SceneManager::set_background(bn::regular_bg_items::school_dormhisao_ni);
                ks::SceneManager::show_dialog(&scene, "", 461);
                ks::SceneManager::show_dialog(&scene, "", 462);
                ks::SceneManager::show_dialog(&scene, "", 463);
                ks::SceneManager::show_dialog(&scene, "", 464);
                ks::SceneManager::show_dialog(&scene, "", 465);
                // bn::vector<ks::ConditionItem, 1> a1_monday_nobodys_room__condition_0;
                // a1_monday_nobodys_room__condition_0.push_back(ks::ConditionItem("_in_replay", &ScriptA1MondayEn::a1_monday_nobodys_room__condition_0_0));
                // scene.add_condition(a1_monday_nobodys_room__condition_0);
            }
            static void a1_monday() {
                a1_monday_out_cold();
                a1_monday_bundle_of_hisao();
                a1_monday_gateway_effect();
                a1_monday_enter_stage_left();
                a1_monday_in_the_nursery();
                a1_monday_nobodys_room();
            }
            static void a1c1o1(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "hi", 466);
                ks::SceneManager::show_dialog(&scene, "mu", 467);
                ks::SceneManager::show_dialog(&scene, "hi", 468);
                ks::SceneManager::show_dialog(&scene, "mu", 469);
                return;
            }
            static void a1c1o2(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "hi", 470);
                ks::SceneManager::show_dialog(&scene, "mu", 471);
                ks::SceneManager::show_dialog(&scene, "", 472);
                ks::SceneManager::show_dialog(&scene, "hi", 473);
                ks::SceneManager::show_dialog(&scene, "mu", 469);
                return;
            }
            static void a1c2o1(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "hi", 474);
                ks::SceneManager::show_dialog(&scene, "", 475);
                ks::SceneManager::show_dialog(&scene, "mi", 476);
                ks::SceneManager::show_dialog(&scene, "hi", 477);
                ks::SceneManager::show_dialog(&scene, "", 478);
                return;
            }
            static void a1c2o2(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "", 479);
                ks::SceneManager::show_dialog(&scene, "", 480);
                ks::SceneManager::show_dialog(&scene, "", 481);
                ks::SceneManager::show_dialog(&scene, "", 482);
                return;
            }
            static void a1c2o3(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "hi", 483);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_smile, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog(&scene, "mi", 484);
                ks::SceneManager::show_dialog(&scene, "", 163);
                ks::SceneManager::show_dialog(&scene, "hi", 485);
                ks::SceneManager::show_character(0, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_character(1, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "", 486);
                ks::SceneManager::show_dialog(&scene, "", 487);
                return;
            }
            static void a1_monday_gateway_effect__menu_question_0(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "mu", 488);
                // bn::vector<ks::AnswerItem, 2> answers;
                // answers.push_back(ks::AnswerItem("Why?", &ScriptA1MondayEn::a1_monday_gateway_effect__menu_question_0_why));
                // answers.push_back(ks::AnswerItem("Yeah, of course.", &ScriptA1MondayEn::a1_monday_gateway_effect__menu_question_0_yeah_of_course));
                // scene.add_sequence(ks::MenuItem(answers);
            }
            static void a1_monday_gateway_effect__menu_question_0_why(const ks::SceneManager scene) {
                // scene.add_sequence(ks::AssignmentItem("wanted_introduce = False"));
                ScriptA1MondayEn::a1c1o1(scene);
            }
            static void a1_monday_gateway_effect__menu_question_0_yeah_of_course(const ks::SceneManager scene) {
                // scene.add_sequence(ks::AssignmentItem("wanted_introduce = True"));
                // scene.add_sequence(ks::AssignmentItem("attraction_sc += 1"));
                ScriptA1MondayEn::a1c1o2(scene);
            }
            static void a1_monday_in_the_nursery__menu_question_0(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "hi", 489);
                // bn::vector<ks::AnswerItem, 3> answers;
                // answers.push_back(ks::AnswerItem("Ask about the library.", &ScriptA1MondayEn::a1_monday_in_the_nursery__menu_question_0_ask_about_the_library));
                // answers.push_back(ks::AnswerItem("Ask about Shizune's deafness.", &ScriptA1MondayEn::a1_monday_in_the_nursery__menu_question_0_ask_about_shizunes_deafness));
                // answers.push_back(ks::AnswerItem("I think I got everything I need to know.", &ScriptA1MondayEn::a1_monday_in_the_nursery__menu_question_0_i_think_i_got_everything_i_need_to_know));
                // scene.add_sequence(ks::MenuItem(answers);
            }
            static void a1_monday_in_the_nursery__menu_question_0_ask_about_the_library(const ks::SceneManager scene) {
                // scene.add_sequence(ks::AssignmentItem("attraction_hanako += 1"));
                ScriptA1MondayEn::a1c2o1(scene);
            }
            static void a1_monday_in_the_nursery__menu_question_0_ask_about_shizunes_deafness(const ks::SceneManager scene) {
                ScriptA1MondayEn::a1c2o2(scene);
            }
            static void a1_monday_in_the_nursery__menu_question_0_i_think_i_got_everything_i_need_to_know(const ks::SceneManager scene) {
                // scene.add_sequence(ks::AssignmentItem("attraction_sc += 1"));
                ScriptA1MondayEn::a1c2o3(scene);
            }
            static void a1_monday_out_cold__condition_0_0(const ks::SceneManager scene) {
                return;
            }
            static void a1_monday_bundle_of_hisao__condition_0_0(const ks::SceneManager scene) {
                return;
            }
            static void a1_monday_gateway_effect__condition_0_0(const ks::SceneManager scene) {
                return;
            }
            static void a1_monday_enter_stage_left__condition_0_0(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "", 490);
                ks::SceneManager::show_dialog(&scene, "hi", 491);
                ks::SceneManager::show_dialog(&scene, "", 492);
                ks::SceneManager::show_dialog(&scene, "hi", 493);
                ks::SceneManager::show_dialog(&scene, "", 492);
                ks::SceneManager::show_dialog(&scene, "", 494);
                ks::SceneManager::show_dialog(&scene, "", 495);
                ks::SceneManager::show_dialog(&scene, "", 496);
                ks::SceneManager::show_dialog(&scene, "", 163);
            }
            static void a1_monday_enter_stage_left__condition_0_1(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "", 497);
                ks::SceneManager::show_dialog(&scene, "", 498);
                ks::SceneManager::show_dialog(&scene, "", 499);
                ks::SceneManager::show_dialog(&scene, "", 500);
                ks::SceneManager::show_dialog(&scene, "", 501);
                ks::SceneManager::show_dialog(&scene, "", 502);
            }
            static void a1_monday_enter_stage_left__condition_1_0(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "mi", 503);
            }
            static void a1_monday_enter_stage_left__condition_1_1(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "", 504);
                ks::SceneManager::show_dialog(&scene, "mi", 505);
                ks::SceneManager::show_dialog(&scene, "", 506);
            }
            static void a1_monday_enter_stage_left__condition_2_0(const ks::SceneManager scene) {
                return;
            }
            static void a1_monday_in_the_nursery__condition_0_0(const ks::SceneManager scene) {
                return;
            }
            static void a1_monday_nobodys_room__condition_0_0(const ks::SceneManager scene) {
                return;
            }
    };
}