#include "script_a1_tuesday.h"
#include "script_a1_tuesday_ru_tl_index.h"
namespace ks {
    class ScriptA1TuesdayRu : public ScriptA1Tuesday {
        public:
            static void a1_tuesday_smalltalk() {
                // POTENTIAL MEMLEAK!!!! better to provide it globally.
                // bn::optional<bn::regular_bg_ptr> main_bg;
                constexpr ks::SceneManager scene = ks::SceneManager("script_a1_tuesday", "ru", script_a1_tuesday_ru_intl);
            
                ks::SceneManager::reset();
                ks::SceneManager::set_background(bn::regular_bg_items::school_dormhisao);
                ks::SceneManager::show_dialog(&scene, "", 0);
                ks::SceneManager::show_dialog(&scene, "", 1);
                ks::SceneManager::show_dialog(&scene, "", 2);
                ks::SceneManager::show_dialog(&scene, "", 3);
                ks::SceneManager::music_play("music_dreamy.gsm");
                ks::SceneManager::show_dialog(&scene, "", 4);
                ks::SceneManager::show_dialog(&scene, "", 5);
                ks::SceneManager::show_dialog(&scene, "", 6);
                ks::SceneManager::show_dialog(&scene, "", 7);
                ks::SceneManager::show_dialog(&scene, "", 8);
                ks::SceneManager::show_dialog(&scene, "", 9);
                ks::SceneManager::show_dialog(&scene, "", 10);
                ks::SceneManager::show_dialog(&scene, "", 11);
                ks::SceneManager::show_dialog(&scene, "", 12);
                ks::SceneManager::show_dialog(&scene, "", 13);
                ks::SceneManager::show_dialog(&scene, "", 14);
                ks::SceneManager::show_dialog(&scene, "", 15);
                ks::SceneManager::show_dialog(&scene, "", 16);
                ks::SceneManager::show_dialog(&scene, "", 17);
                ks::SceneManager::show_dialog(&scene, "", 18);
                ks::SceneManager::show_dialog(&scene, "", 19);
                ks::SceneManager::show_dialog(&scene, "", 20);
                ks::SceneManager::show_dialog(&scene, "", 21);
                ks::SceneManager::show_dialog(&scene, "", 22);
                ks::SceneManager::music_stop();
                ks::SceneManager::set_background(bn::regular_bg_items::school_scienceroom);
                ks::SceneManager::show_dialog(&scene, "", 23);
                ks::SceneManager::show_dialog(&scene, "", 24);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_cross, bn::sprite_items::shizu_spr_cross_wut, ks::sprite_metas::shizu_cross);
                ks::SceneManager::show_dialog(&scene, "", 26);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_cross, bn::sprite_items::shizu_spr_cross_angry, ks::sprite_metas::shizu_cross);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_cross, bn::sprite_items::shizu_spr_cross_angry, ks::sprite_metas::shizu_cross, 48, 0);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips, -48, 0);
                ks::SceneManager::music_play("music_happiness.gsm");
                ks::SceneManager::show_dialog(&scene, "mi", 27);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_angry, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 28);
                ks::SceneManager::show_dialog(&scene, "", 29);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal2, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_smile, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog(&scene, "mi", 30);
                ks::SceneManager::show_dialog(&scene, "mi", 31);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 32);
                ks::SceneManager::show_dialog(&scene, "hi", 33);
                ks::SceneManager::show_dialog(&scene, "hi", 34);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "", 35);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_laugh, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 36);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_confused, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "", 37);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_confused, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog(&scene, "mi", 38);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 39);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "", 40);
                ks::SceneManager::show_dialog(&scene, "", 41);
                ks::SceneManager::show_dialog(&scene, "hi", 42);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_frown, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 43);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 44);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 45);
                ks::SceneManager::show_dialog(&scene, "", 46);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_sad, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog(&scene, "", 47);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_angry, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 48);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 49);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_sparkle, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_smile, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog(&scene, "mi", 50);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "", 51);
                ks::SceneManager::show_dialog(&scene, "hi", 52);
                ks::SceneManager::show_dialog(&scene, "", 53);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "", 54);
                ks::SceneManager::show_dialog(&scene, "", 55);
                ks::SceneManager::show_dialog(&scene, "", 56);
                ks::SceneManager::show_dialog(&scene, "", 57);
                ks::SceneManager::show_dialog(&scene, "", 58);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 59);
                ks::SceneManager::show_dialog(&scene, "", 60);
                ks::SceneManager::show_dialog(&scene, "", 61);
                ks::SceneManager::show_dialog(&scene, "hi", 62);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_happy, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 63);
                ks::SceneManager::show_dialog(&scene, "", 64);
                ks::SceneManager::show_dialog(&scene, "hi", 65);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 66);
                ks::SceneManager::show_dialog(&scene, "hi", 67);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_laugh, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi", 68);
                ks::SceneManager::set_background(bn::regular_bg_items::school_scienceroom);
                ks::SceneManager::show_dialog(&scene, "", 69);
                ks::SceneManager::show_dialog(&scene, "", 70);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_frown, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "", 71);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind, 48, 0);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips, -48, 0);
                ks::SceneManager::music_play("music_comedy.gsm");
                ks::SceneManager::show_dialog(&scene, "mi", 72);
                ks::SceneManager::show_dialog(&scene, "hi", 73);
                ks::SceneManager::show_dialog(&scene, "mi", 74);
                ks::SceneManager::show_dialog(&scene, "hi", 75);
                ks::SceneManager::show_dialog(&scene, "", 76);
                ks::SceneManager::show_dialog(&scene, "", 77);
                ks::SceneManager::show_dialog(&scene, "", 78);
                ks::SceneManager::show_dialog(&scene, "", 79);
                ks::SceneManager::show_dialog(&scene, "hi", 80);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_happy, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "", 81);
                ks::SceneManager::show_dialog(&scene, "", 82);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 83);
                ks::SceneManager::show_dialog(&scene, "hi", 84);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 85);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_laugh, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 86);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "", 87);
                ks::SceneManager::hide_character(0);
                ks::SceneManager::hide_character(1);
                ks::SceneManager::show_dialog(&scene, "", 88);
                ks::SceneManager::set_background(bn::regular_bg_items::school_hallway3);
                ks::SceneManager::show_dialog(&scene, "", 89);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips, -120, 0);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind, 120, 0);
                ks::SceneManager::set_character_position(1, -48, 0);
                ks::SceneManager::set_character_position(0, 48, 0);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 90);
                ks::SceneManager::show_dialog(&scene, "hi", 91);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_laugh, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 92);
                ks::SceneManager::show_dialog(&scene, "", 93);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "", 94);
                ks::SceneManager::show_dialog(&scene, "", 95);
                ks::SceneManager::set_background(bn::regular_bg_items::school_cafeteria);
                ks::SceneManager::show_dialog(&scene, "", 96);
                ks::SceneManager::show_dialog(&scene, "", 97);
                ks::SceneManager::music_play("music_shizune.gsm");
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky, -48, 0);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind, 48, 0);
                ks::SceneManager::show_dialog(&scene, "mi", 98);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "mi", 99);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "", 100);
                ks::SceneManager::show_dialog(&scene, "mi", 101);
                ks::SceneManager::show_dialog(&scene, "hi", 102);
                ks::SceneManager::show_dialog(&scene, "hi", 103);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 104);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_happy, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "mi", 105);
                ks::SceneManager::show_dialog(&scene, "hi", 106);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_laugh, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi", 107);
                ks::SceneManager::show_dialog(&scene, "hi", 108);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_grin, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "mi", 109);
                ks::SceneManager::show_dialog(&scene, "mi", 110);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_laugh, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 111);
                ks::SceneManager::show_dialog(&scene, "", 112);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_blush, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "", 113);
                ks::SceneManager::show_dialog(&scene, "", 114);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_grin, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi", 115);
                ks::SceneManager::show_dialog(&scene, "hi", 116);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_smile, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi", 117);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 118);
                ks::SceneManager::show_dialog(&scene, "", 119);
                ks::SceneManager::show_dialog(&scene, "", 120);
                ks::SceneManager::show_dialog(&scene, "", 121);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 122);
                ks::SceneManager::show_dialog(&scene, "hi", 123);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 124);
                ks::SceneManager::show_dialog(&scene, "mi", 125);
                ks::SceneManager::show_dialog(&scene, "mi", 126);
                ks::SceneManager::show_dialog(&scene, "", 127);
                ks::SceneManager::show_dialog(&scene, "hi", 128);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 129);
                ks::SceneManager::show_dialog(&scene, "hi", 130);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_sad, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 131);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 132);
                ks::SceneManager::show_dialog(&scene, "hi", 133);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_happy, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "", 134);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_laugh, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi", 135);
                ks::SceneManager::show_dialog(&scene, "hi", 136);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 137);
                ks::SceneManager::show_dialog(&scene, "hi", 138);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_sad, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 139);
                ks::SceneManager::show_dialog(&scene, "hi", 140);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 141);
                ks::SceneManager::show_dialog(&scene, "hi", 142);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_angry, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_frown, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 143);
                ks::SceneManager::show_dialog(&scene, "hi", 144);
                ks::SceneManager::show_dialog(&scene, "", 145);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "mi", 146);
                ks::SceneManager::show_dialog(&scene, "hi", 147);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 148);
                ks::SceneManager::show_dialog(&scene, "hi", 149);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 150);
                ks::SceneManager::show_dialog(&scene, "mi", 151);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "mi", 152);
                ks::SceneManager::show_dialog(&scene, "hi", 153);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_laugh, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi", 154);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_grin, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "", 155);
                ks::SceneManager::show_dialog(&scene, "", 156);
                ks::SceneManager::show_dialog(&scene, "", 157);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_smile, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog(&scene, "mi", 158);
                ks::SceneManager::show_dialog(&scene, "hi", 159);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 160);
                ks::SceneManager::show_dialog(&scene, "", 161);
                ks::SceneManager::show_dialog(&scene, "mi", 162);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "mi", 163);
                ks::SceneManager::show_dialog(&scene, "hi", 164);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 165);
                ks::SceneManager::show_dialog(&scene, "hi", 166);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 167);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_laugh, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi", 86);
                ks::SceneManager::show_dialog(&scene, "", 168);
                ks::SceneManager::show_dialog(&scene, "", 169);
                ks::SceneManager::show_dialog(&scene, "", 170);
                ks::SceneManager::music_stop();
                ks::SceneManager::set_background(bn::regular_bg_items::school_scienceroom);
                ks::SceneManager::show_dialog(&scene, "", 171);
                ks::SceneManager::show_dialog(&scene, "", 172);
                // bn::vector<ks::ConditionItem, 1> a1_tuesday_smalltalk__condition_0;
                // a1_tuesday_smalltalk__condition_0.push_back(ks::ConditionItem("_in_replay", &ScriptA1TuesdayRu::a1_tuesday_smalltalk__condition_0_0));
                // scene.add_condition(a1_tuesday_smalltalk__condition_0);
            }
            static void a1_tuesday_risk_vs_reward() {
                // POTENTIAL MEMLEAK!!!! better to provide it globally.
                // bn::optional<bn::regular_bg_ptr> main_bg;
                constexpr ks::SceneManager scene = ks::SceneManager("script_a1_tuesday", "ru", script_a1_tuesday_ru_intl);
            
                ks::SceneManager::reset();
                ks::SceneManager::set_background(bn::regular_bg_items::school_lobby);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind, 48, 0);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips, -48, 0);
                ks::SceneManager::music_play("music_ease.gsm");
                ks::SceneManager::show_dialog(&scene, "", 173);
                ks::SceneManager::show_dialog(&scene, "", 174);
                ks::SceneManager::show_dialog(&scene, "hi", 175);
                ks::SceneManager::show_dialog(&scene, "", 176);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_laugh, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi", 177);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_grin, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi", 178);
                ks::SceneManager::show_dialog(&scene, "", 179);
                ks::SceneManager::show_dialog(&scene, "", 180);
                ks::SceneManager::hide_character(1);
                ks::SceneManager::hide_character(0);
                ks::SceneManager::show_dialog(&scene, "", 181);
                ks::SceneManager::show_dialog(&scene, "hi", 182);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal2, ks::sprite_metas::shizu_basic, 48, 0);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky, -48, 0);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 183);
                ks::SceneManager::show_dialog(&scene, "hi", 184);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "", 185);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 186);
                ks::SceneManager::show_dialog(&scene, "", 187);
                ks::SceneManager::music_stop();
                ks::SceneManager::set_background(bn::regular_bg_items::school_council);
                ks::SceneManager::show_dialog(&scene, "", 188);
                ks::SceneManager::show_dialog(&scene, "", 189);
                ks::SceneManager::show_dialog(&scene, "", 190);
                ks::SceneManager::show_dialog(&scene, "", 191);
                ks::SceneManager::show_dialog(&scene, "hi", 192);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind, 48, 0);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips, -48, 0);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 193);
                ks::SceneManager::show_dialog(&scene, "hi", 194);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_smile, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog(&scene, "mi", 195);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_happy, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "", 196);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 197);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 198);
                ks::SceneManager::hide_character(0);
                ks::SceneManager::show_dialog(&scene, "", 199);
                ks::SceneManager::show_dialog(&scene, "", 200);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_frown, ks::sprite_metas::shizu_adjust, 48, 0);
                ks::SceneManager::show_dialog(&scene, "", 201);
                ks::SceneManager::show_dialog(&scene, "", 202);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal2, ks::sprite_metas::shizu_basic);
                ks::SceneManager::music_play("music_running.gsm");
                ks::SceneManager::show_dialog(&scene, "", 203);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_smile, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog(&scene, "mi", 204);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 205);
                ks::SceneManager::show_dialog(&scene, "hi", 206);
                ks::SceneManager::show_dialog(&scene, "", 207);
                ks::SceneManager::show_dialog(&scene, "hi", 208);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "mi", 209);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_laugh, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi", 210);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_grin, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "hi", 211);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "", 212);
                ks::SceneManager::show_dialog(&scene, "hi", 213);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 214);
                ks::SceneManager::show_dialog(&scene, "", 215);
                ks::SceneManager::show_dialog(&scene, "", 216);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_happy, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "", 217);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_confused, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog(&scene, "mi", 218);
                ks::SceneManager::show_dialog(&scene, "hi", 219);
                ks::SceneManager::show_dialog(&scene, "mi", 220);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_sparkle, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "", 221);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_happy, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_smile, ks::sprite_metas::misha_cross);
                ScriptA1TuesdayRu::a1_tuesday_risk_vs_reward__menu_question_0(scene);
                ks::SceneManager::show_dialog(&scene, "", 222);
                ks::SceneManager::show_dialog(&scene, "hi", 223);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "", 224);
                ks::SceneManager::show_dialog(&scene, "", 225);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 226);
                ks::SceneManager::show_dialog(&scene, "mi", 227);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 228);
                ks::SceneManager::show_dialog(&scene, "hi", 229);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 230);
                ks::SceneManager::music_stop();
                // bn::vector<ks::ConditionItem, 1> a1_tuesday_risk_vs_reward__condition_0;
                // a1_tuesday_risk_vs_reward__condition_0.push_back(ks::ConditionItem("_in_replay", &ScriptA1TuesdayRu::a1_tuesday_risk_vs_reward__condition_0_0));
                // scene.add_condition(a1_tuesday_risk_vs_reward__condition_0);
            }
            static void a1_tuesday_pseudo_tea_cosy() {
                // POTENTIAL MEMLEAK!!!! better to provide it globally.
                // bn::optional<bn::regular_bg_ptr> main_bg;
                constexpr ks::SceneManager scene = ks::SceneManager("script_a1_tuesday", "ru", script_a1_tuesday_ru_intl);
            
                ks::SceneManager::reset();
                ks::SceneManager::set_background(bn::regular_bg_items::school_staircase2);
                ks::SceneManager::set_background(bn::regular_bg_items::school_hallway2);
                ks::SceneManager::show_dialog(&scene, "", 231);
                ks::SceneManager::show_dialog(&scene, "", 232);
                ks::SceneManager::show_dialog(&scene, "", 233);
                ks::SceneManager::show_dialog(&scene, "", 234);
                ks::SceneManager::show_dialog(&scene, "", 235);
                ks::SceneManager::show_dialog(&scene, "", 236);
                ks::SceneManager::show_dialog(&scene, "", 237);
                ks::SceneManager::show_dialog(&scene, "", 238);
                ks::SceneManager::show_dialog(&scene, "", 239);
                ks::SceneManager::show_dialog(&scene, "", 240);
                ks::SceneManager::show_dialog(&scene, "", 241);
                ks::SceneManager::show_dialog(&scene, "", 242);
                ks::SceneManager::show_dialog(&scene, "", 243);
                ks::SceneManager::show_dialog(&scene, "", 244);
                ks::SceneManager::show_dialog(&scene, "", 245);
                ks::SceneManager::music_play("music_lilly.gsm");
                ks::SceneManager::set_background(bn::regular_bg_items::lilly_tearoom);
                ks::SceneManager::show_dialog(&scene, "", 25);
                ks::SceneManager::show_dialog(&scene, "", 246);
                ks::SceneManager::show_dialog(&scene, "", 247);
                ks::SceneManager::show_dialog(&scene, "", 248);
                ks::SceneManager::show_dialog(&scene, "", 249);
                ks::SceneManager::set_background(bn::regular_bg_items::lilly_tearoom_open);
                ks::SceneManager::show_dialog(&scene, "li_", 250);
                ks::SceneManager::show_dialog(&scene, "", 251);
                ks::SceneManager::show_dialog(&scene, "", 252);
                ks::SceneManager::show_dialog(&scene, "", 253);
                ks::SceneManager::show_dialog(&scene, "hi", 254);
                ks::SceneManager::show_dialog(&scene, "", 255);
                ks::SceneManager::show_dialog(&scene, "li_", 256);
                ks::SceneManager::show_dialog(&scene, "", 257);
                ks::SceneManager::show_dialog(&scene, "hi", 258);
                ks::SceneManager::show_dialog(&scene, "", 259);
                ks::SceneManager::show_dialog(&scene, "", 260);
                ks::SceneManager::show_dialog(&scene, "", 261);
                ks::SceneManager::show_dialog(&scene, "", 262);
                ks::SceneManager::set_background(bn::regular_bg_items::lilly_tearoom);
                ks::SceneManager::show_dialog(&scene, "", 263);
                ks::SceneManager::show_dialog(&scene, "li_", 264);
                ks::SceneManager::show_dialog(&scene, "hi", 265);
                ks::SceneManager::show_dialog(&scene, "", 266);
                ks::SceneManager::show_dialog(&scene, "", 267);
                ks::SceneManager::set_background(bn::regular_bg_items::lilly_tearoom_open);
                ks::SceneManager::show_dialog(&scene, "li_", 268);
                ks::SceneManager::show_dialog(&scene, "hi", 269);
                ks::SceneManager::show_dialog(&scene, "", 270);
                ks::SceneManager::show_dialog(&scene, "li", 271);
                ks::SceneManager::show_dialog(&scene, "hi", 272);
                ks::SceneManager::show_dialog(&scene, "", 273);
                ks::SceneManager::show_dialog(&scene, "", 274);
                ks::SceneManager::set_background(bn::regular_bg_items::school_miyagi);
                ks::SceneManager::show_dialog(&scene, "", 275);
                ks::SceneManager::show_dialog(&scene, "", 276);
                ks::SceneManager::show_dialog(&scene, "", 277);
                ks::SceneManager::show_dialog(&scene, "", 278);
                ks::SceneManager::show_dialog(&scene, "", 279);
                ks::SceneManager::show_dialog(&scene, "", 280);
                ks::SceneManager::show_dialog(&scene, "li", 281);
                ks::SceneManager::show_dialog(&scene, "", 282);
                ks::SceneManager::show_dialog(&scene, "li", 283);
                ks::SceneManager::show_dialog(&scene, "hi", 284);
                ks::SceneManager::show_dialog(&scene, "", 285);
                ks::SceneManager::show_dialog(&scene, "li", 286);
                ks::SceneManager::show_dialog(&scene, "hi", 287);
                ks::SceneManager::show_dialog(&scene, "", 288);
                ks::SceneManager::show_dialog(&scene, "li", 289);
                ks::SceneManager::set_background(bn::regular_bg_items::tearoom_lillyhisao_noon);
                ks::SceneManager::show_dialog(&scene, "", 290);
                ks::SceneManager::show_dialog(&scene, "", 291);
                ks::SceneManager::show_dialog(&scene, "hi", 292);
                ks::SceneManager::show_dialog(&scene, "", 293);
                ks::SceneManager::show_dialog(&scene, "li", 294);
                ks::SceneManager::show_dialog(&scene, "", 295);
                ks::SceneManager::show_dialog(&scene, "", 296);
                ks::SceneManager::show_dialog(&scene, "hi", 297);
                ks::SceneManager::show_dialog(&scene, "li", 298);
                ks::SceneManager::show_dialog(&scene, "hi", 299);
                ks::SceneManager::show_dialog(&scene, "", 300);
                ks::SceneManager::show_dialog(&scene, "li", 301);
                ks::SceneManager::show_dialog(&scene, "hi", 302);
                ks::SceneManager::show_dialog(&scene, "li", 303);
                ks::SceneManager::show_dialog(&scene, "", 304);
                ks::SceneManager::show_dialog(&scene, "hi", 305);
                ks::SceneManager::show_dialog(&scene, "", 306);
                ks::SceneManager::show_dialog(&scene, "li", 307);
                ks::SceneManager::show_dialog(&scene, "", 308);
                ks::SceneManager::show_dialog(&scene, "", 309);
                ks::SceneManager::show_dialog(&scene, "", 310);
                ks::SceneManager::show_dialog(&scene, "hi", 311);
                ks::SceneManager::show_dialog(&scene, "li", 312);
                ks::SceneManager::show_dialog(&scene, "li", 313);
                ks::SceneManager::show_dialog(&scene, "", 314);
                ks::SceneManager::show_dialog(&scene, "", 315);
                ks::SceneManager::show_dialog(&scene, "hi", 316);
                ks::SceneManager::show_dialog(&scene, "li", 317);
                ks::SceneManager::show_dialog(&scene, "hi", 318);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "", 319);
                ks::SceneManager::show_dialog(&scene, "", 320);
                ks::SceneManager::set_background(bn::regular_bg_items::tearoom_lillyhisao_sunset);
                ks::SceneManager::music_play("music_tranquil.gsm");
                ks::SceneManager::show_dialog(&scene, "", 321);
                ks::SceneManager::show_dialog(&scene, "", 322);
                ks::SceneManager::show_dialog(&scene, "hi", 323);
                ks::SceneManager::show_dialog(&scene, "li", 324);
                ks::SceneManager::show_dialog(&scene, "", 325);
                ks::SceneManager::show_dialog(&scene, "hi", 326);
                ks::SceneManager::show_dialog(&scene, "", 327);
                ks::SceneManager::show_dialog(&scene, "li", 328);
                ks::SceneManager::show_dialog(&scene, "", 329);
                ks::SceneManager::show_dialog(&scene, "hi", 330);
                ks::SceneManager::show_dialog(&scene, "", 331);
                ks::SceneManager::show_dialog(&scene, "", 332);
                ks::SceneManager::show_dialog(&scene, "li", 333);
                ks::SceneManager::show_dialog(&scene, "", 334);
                ks::SceneManager::show_dialog(&scene, "hi", 335);
                ks::SceneManager::show_dialog(&scene, "", 336);
                ks::SceneManager::show_dialog(&scene, "li", 337);
                ks::SceneManager::show_dialog(&scene, "li", 338);
                ks::SceneManager::show_dialog(&scene, "hi", 339);
                ks::SceneManager::show_dialog(&scene, "", 340);
                ks::SceneManager::show_dialog(&scene, "li", 341);
                ks::SceneManager::show_dialog(&scene, "", 342);
                ks::SceneManager::show_dialog(&scene, "hi", 343);
                ks::SceneManager::set_background(bn::regular_bg_items::school_miyagi_ss);
                ks::SceneManager::show_dialog(&scene, "", 344);
                ks::SceneManager::show_dialog(&scene, "", 345);
                ks::SceneManager::show_dialog(&scene, "", 346);
                ks::SceneManager::music_stop();
                ks::SceneManager::set_background(bn::regular_bg_items::school_hallway2);
                ks::SceneManager::show_dialog(&scene, "", 347);
                ks::SceneManager::show_dialog(&scene, "", 348);
                ks::SceneManager::show_dialog(&scene, "hi", 349);
                ks::SceneManager::show_dialog(&scene, "", 350);
                ks::SceneManager::set_background(bn::regular_bg_items::school_library_ss);
                ks::SceneManager::music_play("music_happiness.gsm");
                ks::SceneManager::show_dialog(&scene, "", 351);
                ks::SceneManager::show_dialog(&scene, "", 352);
                ks::SceneManager::show_dialog(&scene, "", 353);
                ks::SceneManager::show_dialog(&scene, "li", 354);
                ks::SceneManager::show_dialog(&scene, "", 355);
                ks::SceneManager::show_dialog(&scene, "", 356);
                ks::SceneManager::show_dialog(&scene, "", 357);
                ks::SceneManager::show_dialog(&scene, "mystery", 358);
                ks::SceneManager::show_dialog(&scene, "", 359);
                ks::SceneManager::show_dialog(&scene, "yu_", 360);
                ks::SceneManager::show_dialog(&scene, "", 361);
                ks::SceneManager::show_dialog(&scene, "li", 362);
                ks::SceneManager::show_dialog(&scene, "yu_", 363);
                ks::SceneManager::show_dialog(&scene, "yu_", 364);
                ks::SceneManager::show_dialog(&scene, "li", 365);
                ks::SceneManager::show_dialog(&scene, "yu_", 366);
                ks::SceneManager::show_dialog(&scene, "yu_", 367);
                ks::SceneManager::show_dialog(&scene, "", 368);
                ks::SceneManager::show_dialog(&scene, "yu_", 369);
                ks::SceneManager::show_dialog(&scene, "", 370);
                ks::SceneManager::show_dialog(&scene, "", 371);
                ks::SceneManager::show_dialog(&scene, "yu_", 372);
                ks::SceneManager::show_dialog(&scene, "li", 373);
                ks::SceneManager::show_dialog(&scene, "li", 374);
                ks::SceneManager::show_dialog(&scene, "yu_", 375);
                ks::SceneManager::show_dialog(&scene, "", 376);
                ks::SceneManager::show_dialog(&scene, "yu_", 377);
                ks::SceneManager::show_dialog(&scene, "yu_", 378);
                ks::SceneManager::show_dialog(&scene, "", 379);
                ks::SceneManager::show_dialog(&scene, "li", 380);
                ks::SceneManager::show_dialog(&scene, "hi", 381);
                ks::SceneManager::show_dialog(&scene, "yu", 382);
                ks::SceneManager::show_dialog(&scene, "", 383);
                ks::SceneManager::show_dialog(&scene, "li", 384);
                ks::SceneManager::show_dialog(&scene, "li", 385);
                ks::SceneManager::show_dialog(&scene, "", 386);
                ks::SceneManager::show_dialog(&scene, "yu", 387);
                ks::SceneManager::show_dialog(&scene, "", 388);
                ks::SceneManager::show_dialog(&scene, "li", 389);
                ks::SceneManager::show_dialog(&scene, "hi", 390);
                ks::SceneManager::show_dialog(&scene, "", 391);
                ks::SceneManager::show_dialog(&scene, "yu", 392);
                ks::SceneManager::show_dialog(&scene, "", 393);
                ks::SceneManager::show_dialog(&scene, "hi", 394);
                ks::SceneManager::show_dialog(&scene, "yu", 395);
                ks::SceneManager::show_dialog(&scene, "yu", 396);
                ks::SceneManager::show_dialog(&scene, "yu", 397);
                ks::SceneManager::show_dialog(&scene, "", 25);
                ks::SceneManager::show_dialog(&scene, "", 398);
                ks::SceneManager::show_dialog(&scene, "hi", 399);
                ks::SceneManager::show_dialog(&scene, "", 400);
                ks::SceneManager::show_dialog(&scene, "li", 401);
                ks::SceneManager::music_stop();
                // bn::vector<ks::ConditionItem, 1> a1_tuesday_pseudo_tea_cosy__condition_0;
                // a1_tuesday_pseudo_tea_cosy__condition_0.push_back(ks::ConditionItem("_in_replay", &ScriptA1TuesdayRu::a1_tuesday_pseudo_tea_cosy__condition_0_0));
                // scene.add_condition(a1_tuesday_pseudo_tea_cosy__condition_0);
            }
            static void a1_tuesday_shared_library() {
                // POTENTIAL MEMLEAK!!!! better to provide it globally.
                // bn::optional<bn::regular_bg_ptr> main_bg;
                constexpr ks::SceneManager scene = ks::SceneManager("script_a1_tuesday", "ru", script_a1_tuesday_ru_intl);
            
                ks::SceneManager::reset();
                ks::SceneManager::set_background(bn::regular_bg_items::school_library_ss);
                ks::SceneManager::show_dialog(&scene, "", 402);
                ks::SceneManager::show_dialog(&scene, "", 403);
                ks::SceneManager::show_dialog(&scene, "", 404);
                ks::SceneManager::show_dialog(&scene, "", 405);
                ks::SceneManager::show_dialog(&scene, "", 406);
                ks::SceneManager::show_dialog(&scene, "", 407);
                ks::SceneManager::show_dialog(&scene, "", 408);
                ks::SceneManager::show_dialog(&scene, "", 409);
                ks::SceneManager::show_dialog(&scene, "", 410);
                ks::SceneManager::show_dialog(&scene, "", 411);
                ks::SceneManager::music_play("music_another.gsm");
                ks::SceneManager::show_dialog(&scene, "", 412);
                ks::SceneManager::show_dialog(&scene, "", 413);
                ks::SceneManager::show_dialog(&scene, "", 414);
                ks::SceneManager::show_dialog(&scene, "", 415);
                ks::SceneManager::show_dialog(&scene, "", 416);
                ks::SceneManager::show_dialog(&scene, "", 417);
                ks::SceneManager::show_dialog(&scene, "", 418);
                ks::SceneManager::show_dialog(&scene, "", 419);
                ks::SceneManager::show_dialog(&scene, "", 420);
                ks::SceneManager::show_dialog(&scene, "", 421);
                ScriptA1TuesdayRu::a1_tuesday_shared_library__menu_question_0(scene);
                ks::SceneManager::show_dialog(&scene, "ha", 422);
                ks::SceneManager::show_dialog(&scene, "ha", 423);
                ks::SceneManager::show_dialog(&scene, "hi", 424);
                ks::SceneManager::show_dialog(&scene, "ha", 425);
                ks::SceneManager::show_dialog(&scene, "", 426);
                ks::SceneManager::show_dialog(&scene, "", 427);
                ks::SceneManager::set_background(bn::regular_bg_items::school_library_ss);
                ks::SceneManager::music_play("music_pearly.gsm");
                ks::SceneManager::show_dialog(&scene, "", 428);
                ks::SceneManager::show_dialog(&scene, "", 429);
                ks::SceneManager::show_dialog(&scene, "", 430);
                ks::SceneManager::show_dialog(&scene, "hi", 431);
                ks::SceneManager::show_dialog(&scene, "yu", 432);
                ks::SceneManager::show_dialog(&scene, "hi", 433);
                ks::SceneManager::show_dialog(&scene, "li", 434);
                ks::SceneManager::show_dialog(&scene, "hi", 435);
                ks::SceneManager::show_dialog(&scene, "li", 436);
                ks::SceneManager::show_dialog(&scene, "yu", 437);
                ks::SceneManager::show_dialog(&scene, "hi", 438);
                ks::SceneManager::show_dialog(&scene, "li", 439);
                ks::SceneManager::show_dialog(&scene, "hi", 440);
                ks::SceneManager::show_dialog(&scene, "", 441);
                ks::SceneManager::show_dialog(&scene, "hi", 442);
                ks::SceneManager::show_dialog(&scene, "hi", 443);
                ks::SceneManager::show_dialog(&scene, "yu", 444);
                // bn::vector<ks::ConditionItem, 2> a1_tuesday_shared_library__condition_0;
                // a1_tuesday_shared_library__condition_0.push_back(ks::ConditionItem(""Hi! I'm new here. Hisao Nakai. We're in the same class." in choices", &ScriptA1TuesdayRu::a1_tuesday_shared_library__condition_0_0));
                // a1_tuesday_shared_library__condition_0.push_back(ks::ConditionItem("None", &ScriptA1TuesdayRu::a1_tuesday_shared_library__condition_0_1));
                // scene.add_condition(a1_tuesday_shared_library__condition_0);
                ks::SceneManager::show_dialog(&scene, "hi", 445);
                ks::SceneManager::show_dialog(&scene, "hi", 446);
                ks::SceneManager::show_dialog(&scene, "", 447);
                ks::SceneManager::show_dialog(&scene, "yu", 448);
                ks::SceneManager::show_dialog(&scene, "", 449);
                ks::SceneManager::show_dialog(&scene, "yu", 450);
                ks::SceneManager::show_dialog(&scene, "hi", 451);
                ks::SceneManager::show_dialog(&scene, "", 452);
                ks::SceneManager::show_dialog(&scene, "", 453);
                ks::SceneManager::show_dialog(&scene, "yu", 454);
                ks::SceneManager::show_dialog(&scene, "hi", 455);
                ks::SceneManager::show_dialog(&scene, "hi", 456);
                ks::SceneManager::show_dialog(&scene, "", 457);
                ks::SceneManager::show_dialog(&scene, "yu", 458);
                ks::SceneManager::show_dialog(&scene, "hi", 459);
                ks::SceneManager::show_dialog(&scene, "hi", 460);
                ks::SceneManager::show_dialog(&scene, "yu", 461);
                ks::SceneManager::show_dialog(&scene, "", 462);
                ks::SceneManager::show_dialog(&scene, "", 463);
                ks::SceneManager::music_stop();
                // bn::vector<ks::ConditionItem, 1> a1_tuesday_shared_library__condition_1;
                // a1_tuesday_shared_library__condition_1.push_back(ks::ConditionItem("_in_replay", &ScriptA1TuesdayRu::a1_tuesday_shared_library__condition_1_0));
                // scene.add_condition(a1_tuesday_shared_library__condition_1);
            }
            static void a1_tuesday_bizarre_and_surreal() {
                // POTENTIAL MEMLEAK!!!! better to provide it globally.
                // bn::optional<bn::regular_bg_ptr> main_bg;
                constexpr ks::SceneManager scene = ks::SceneManager("script_a1_tuesday", "ru", script_a1_tuesday_ru_intl);
            
                ks::SceneManager::reset();
                ks::SceneManager::set_background(bn::regular_bg_items::school_dormhallway);
                ks::SceneManager::show_dialog(&scene, "", 464);
                ks::SceneManager::show_dialog(&scene, "", 465);
                ks::SceneManager::show_dialog(&scene, "mystery", 466);
                ks::SceneManager::music_play("music_kenji.gsm");
                ks::SceneManager::show_dialog(&scene, "", 467);
                ks::SceneManager::show_dialog(&scene, "hi", 468);
                ks::SceneManager::show_dialog(&scene, "", 469);
                ks::SceneManager::show_dialog(&scene, "ke", 470);
                ks::SceneManager::show_dialog(&scene, "", 471);
                ks::SceneManager::show_dialog(&scene, "hi", 472);
                ks::SceneManager::show_dialog(&scene, "ke", 473);
                ks::SceneManager::show_dialog(&scene, "", 474);
                ks::SceneManager::show_dialog(&scene, "ke", 475);
                ks::SceneManager::show_dialog(&scene, "hi", 476);
                ks::SceneManager::show_dialog(&scene, "", 477);
                ks::SceneManager::show_dialog(&scene, "ke", 478);
                ks::SceneManager::show_dialog(&scene, "", 479);
                ks::SceneManager::show_dialog(&scene, "ke", 480);
                ks::SceneManager::show_dialog(&scene, "", 481);
                ks::SceneManager::show_dialog(&scene, "", 482);
                ks::SceneManager::show_dialog(&scene, "hi", 483);
                ks::SceneManager::show_dialog(&scene, "ke", 484);
                ks::SceneManager::show_dialog(&scene, "", 485);
                ks::SceneManager::show_dialog(&scene, "ke", 486);
                ks::SceneManager::show_dialog(&scene, "hi", 487);
                ks::SceneManager::show_dialog(&scene, "ke", 488);
                ks::SceneManager::show_dialog(&scene, "ke", 489);
                ks::SceneManager::show_dialog(&scene, "", 490);
                ks::SceneManager::show_dialog(&scene, "ke", 491);
                ks::SceneManager::show_dialog(&scene, "", 492);
                ks::SceneManager::show_dialog(&scene, "ke", 493);
                ks::SceneManager::show_dialog(&scene, "", 494);
                ks::SceneManager::show_dialog(&scene, "ke", 495);
                ks::SceneManager::show_dialog(&scene, "hi", 496);
                ks::SceneManager::show_dialog(&scene, "hi", 497);
                ks::SceneManager::show_dialog(&scene, "", 498);
                ks::SceneManager::show_dialog(&scene, "ke", 499);
                ks::SceneManager::show_dialog(&scene, "ke", 500);
                ks::SceneManager::show_dialog(&scene, "", 501);
                ks::SceneManager::show_dialog(&scene, "ke", 502);
                ks::SceneManager::show_dialog(&scene, "hi", 503);
                ks::SceneManager::show_dialog(&scene, "ke", 504);
                ks::SceneManager::show_dialog(&scene, "", 505);
                ks::SceneManager::show_dialog(&scene, "ke", 506);
                ks::SceneManager::show_dialog(&scene, "hi", 507);
                ks::SceneManager::show_dialog(&scene, "hi", 508);
                ks::SceneManager::show_dialog(&scene, "ke", 509);
                ks::SceneManager::show_dialog(&scene, "", 510);
                ScriptA1TuesdayRu::a1_tuesday_bizarre_and_surreal__menu_question_0(scene);
                ks::SceneManager::show_dialog(&scene, "ke", 511);
                ks::SceneManager::show_dialog(&scene, "ke", 512);
                ks::SceneManager::show_dialog(&scene, "", 513);
                ks::SceneManager::show_dialog(&scene, "hi", 514);
                ks::SceneManager::show_dialog(&scene, "ke", 515);
                ks::SceneManager::show_dialog(&scene, "ke", 516);
                ks::SceneManager::show_dialog(&scene, "", 517);
                ks::SceneManager::show_dialog(&scene, "ke", 518);
                ks::SceneManager::show_dialog(&scene, "ke", 519);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "ke", 520);
                ks::SceneManager::show_dialog(&scene, "", 521);
                ks::SceneManager::show_dialog(&scene, "hi", 522);
                ks::SceneManager::show_dialog(&scene, "", 523);
                ks::SceneManager::music_play("music_tension.gsm");
                ks::SceneManager::show_dialog(&scene, "ke", 524);
                ks::SceneManager::show_dialog(&scene, "ke", 525);
                ks::SceneManager::show_dialog(&scene, "ke", 526);
                ks::SceneManager::show_dialog(&scene, "ke", 527);
                ks::SceneManager::show_dialog(&scene, "ke", 528);
                ks::SceneManager::show_dialog(&scene, "ke", 529);
                ks::SceneManager::show_dialog(&scene, "ke", 530);
                ks::SceneManager::show_dialog(&scene, "", 531);
                ks::SceneManager::show_dialog(&scene, "ke", 532);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "hi", 533);
                ks::SceneManager::show_dialog(&scene, "", 534);
                ks::SceneManager::music_play("music_kenji.gsm");
                ks::SceneManager::show_dialog(&scene, "ke", 535);
                ks::SceneManager::show_dialog(&scene, "hi", 536);
                ks::SceneManager::show_dialog(&scene, "", 537);
                ks::SceneManager::show_dialog(&scene, "ke", 538);
                ks::SceneManager::show_dialog(&scene, "ke", 539);
                ks::SceneManager::show_dialog(&scene, "hi", 540);
                ks::SceneManager::show_dialog(&scene, "ke", 541);
                ks::SceneManager::show_dialog(&scene, "hi", 542);
                ks::SceneManager::show_dialog(&scene, "ke", 543);
                ks::SceneManager::show_dialog(&scene, "", 544);
                ks::SceneManager::show_dialog(&scene, "", 545);
                ks::SceneManager::show_dialog(&scene, "ke", 546);
                ks::SceneManager::show_dialog(&scene, "hi", 547);
                ks::SceneManager::show_dialog(&scene, "", 548);
                ks::SceneManager::show_dialog(&scene, "ke", 549);
                ks::SceneManager::show_dialog(&scene, "ke", 550);
                ks::SceneManager::show_dialog(&scene, "ke", 551);
                ks::SceneManager::show_dialog(&scene, "", 552);
                ks::SceneManager::show_dialog(&scene, "ke", 553);
                ks::SceneManager::show_dialog(&scene, "ke", 554);
                ks::SceneManager::show_dialog(&scene, "hi", 555);
                ks::SceneManager::show_dialog(&scene, "ke", 556);
                ks::SceneManager::show_dialog(&scene, "ke", 557);
                ks::SceneManager::show_dialog(&scene, "ke", 558);
                ks::SceneManager::show_dialog(&scene, "ke", 559);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "", 560);
                ks::SceneManager::set_background(bn::regular_bg_items::school_dormhisao_ss);
                ks::SceneManager::show_dialog(&scene, "", 561);
                ks::SceneManager::show_dialog(&scene, "", 562);
                ks::SceneManager::show_dialog(&scene, "", 563);
                ks::SceneManager::show_dialog(&scene, "", 564);
                ks::SceneManager::show_dialog(&scene, "", 565);
                ks::SceneManager::show_dialog(&scene, "hi", 566);
                ks::SceneManager::show_dialog(&scene, "", 567);
                ks::SceneManager::show_dialog(&scene, "", 568);
                ks::SceneManager::show_dialog(&scene, "", 569);
                ks::SceneManager::show_dialog(&scene, "", 570);
                ks::SceneManager::show_dialog(&scene, "", 571);
                // bn::vector<ks::ConditionItem, 1> a1_tuesday_bizarre_and_surreal__condition_0;
                // a1_tuesday_bizarre_and_surreal__condition_0.push_back(ks::ConditionItem("_in_replay", &ScriptA1TuesdayRu::a1_tuesday_bizarre_and_surreal__condition_0_0));
                // scene.add_condition(a1_tuesday_bizarre_and_surreal__condition_0);
            }
            static void a1_tuesday() {
                a1_tuesday_smalltalk();
                a1_tuesday_risk_vs_reward();
                a1_tuesday_pseudo_tea_cosy();
                a1_tuesday_shared_library();
                a1_tuesday_bizarre_and_surreal();
            }
            static void a1c3o1(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "", 572);
                ks::SceneManager::show_dialog(&scene, "", 573);
                ks::SceneManager::show_dialog(&scene, "", 574);
                ks::SceneManager::show_dialog(&scene, "", 575);
                ks::SceneManager::show_dialog(&scene, "", 576);
                ks::SceneManager::show_dialog(&scene, "", 577);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "", 578);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_grin, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi", 579);
                ks::SceneManager::show_dialog(&scene, "hi", 580);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 581);
                ks::SceneManager::show_dialog(&scene, "mi", 582);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 583);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "mi", 584);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "mi", 585);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 586);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "mi", 25);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal2, ks::sprite_metas::shizu_basic);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "", 587);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 588);
                ks::SceneManager::show_dialog(&scene, "", 589);
                ks::SceneManager::show_dialog(&scene, "", 590);
                ks::SceneManager::show_dialog(&scene, "", 591);
                ks::SceneManager::show_dialog(&scene, "", 592);
                ks::SceneManager::show_dialog(&scene, "", 593);
                ks::SceneManager::show_dialog(&scene, "hi", 594);
                ks::SceneManager::music_play("music_shizune.gsm");
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_frown, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 595);
                ks::SceneManager::show_dialog(&scene, "hi", 596);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 597);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 598);
                ks::SceneManager::show_dialog(&scene, "hi", 599);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_sparkle, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "", 600);
                return;
            }
            static void a1c3o2(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "", 601);
                ks::SceneManager::show_dialog(&scene, "", 602);
                ks::SceneManager::show_dialog(&scene, "", 577);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "", 578);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 603);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 604);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 605);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frustrated, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "mi", 606);
                ks::SceneManager::show_dialog(&scene, "mi", 607);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_frown, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "mi", 608);
                ks::SceneManager::show_dialog(&scene, "mi", 609);
                ks::SceneManager::show_dialog(&scene, "", 610);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal2, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "mi", 611);
                ks::SceneManager::music_play("music_normal.gsm");
                ks::SceneManager::show_dialog(&scene, "", 612);
                ks::SceneManager::show_dialog(&scene, "hi", 613);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "mi", 614);
                ks::SceneManager::show_dialog(&scene, "", 615);
                ks::SceneManager::show_dialog(&scene, "", 616);
                ks::SceneManager::show_dialog(&scene, "", 617);
                ks::SceneManager::show_dialog(&scene, "hi", 618);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 619);
                ks::SceneManager::show_dialog(&scene, "hi", 620);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_sad, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 621);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 622);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_angry, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_smile, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog(&scene, "mi", 623);
                ks::SceneManager::show_dialog(&scene, "hi", 624);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 625);
                ks::SceneManager::show_dialog(&scene, "hi", 626);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_sad, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 627);
                return;
            }
            static void a1c4o1(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "hi", 628);
                ks::SceneManager::show_dialog(&scene, "", 25);
                ks::SceneManager::show_dialog(&scene, "hi", 629);
                ks::SceneManager::show_dialog(&scene, "", 25);
                // bn::vector<ks::ConditionItem, 1> a1c4o1__condition_0;
                // a1c4o1__condition_0.push_back(ks::ConditionItem("wanted_introduce or _in_replay", &ScriptA1TuesdayRu::a1c4o1__condition_0_0));
                // scene.add_condition(a1c4o1__condition_0);
                ks::SceneManager::set_background(bn::regular_bg_items::hana_library);
                ks::SceneManager::show_dialog(&scene, "", 630);
                ks::SceneManager::show_dialog(&scene, "hi", 631);
                ks::SceneManager::show_dialog(&scene, "hi", 632);
                ks::SceneManager::show_dialog(&scene, "ha_", 633);
                ks::SceneManager::show_dialog(&scene, "", 634);
                ks::SceneManager::show_dialog(&scene, "", 635);
                ks::SceneManager::show_dialog(&scene, "hi", 636);
                ks::SceneManager::set_background(bn::regular_bg_items::school_library_ss);
                ks::SceneManager::show_dialog(&scene, "", 637);
                ks::SceneManager::show_dialog(&scene, "", 638);
                ks::SceneManager::show_dialog(&scene, "hi", 639);
                ks::SceneManager::show_dialog(&scene, "ha", 640);
                ks::SceneManager::show_dialog(&scene, "ha", 641);
                ks::SceneManager::show_dialog(&scene, "", 642);
                ks::SceneManager::show_dialog(&scene, "hi", 643);
                ks::SceneManager::show_dialog(&scene, "", 644);
                ks::SceneManager::show_dialog(&scene, "", 645);
                ks::SceneManager::show_dialog(&scene, "", 646);
                ks::SceneManager::show_dialog(&scene, "", 647);
                ks::SceneManager::show_dialog(&scene, "hi", 648);
                ks::SceneManager::show_dialog(&scene, "ha", 649);
                ks::SceneManager::show_dialog(&scene, "hi", 650);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "", 25);
                ks::SceneManager::show_dialog(&scene, "", 651);
                ks::SceneManager::show_dialog(&scene, "", 652);
                ks::SceneManager::show_dialog(&scene, "hi", 653);
                return;
            }
            static void a1c4o2(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "hi", 654);
                ks::SceneManager::show_dialog(&scene, "ha_", 655);
                ks::SceneManager::show_dialog(&scene, "", 656);
                ks::SceneManager::show_dialog(&scene, "hi", 657);
                ks::SceneManager::show_dialog(&scene, "", 658);
                ks::SceneManager::set_background(bn::regular_bg_items::hana_library);
                ks::SceneManager::show_dialog(&scene, "ha_", 659);
                ks::SceneManager::show_dialog(&scene, "", 660);
                ks::SceneManager::show_dialog(&scene, "", 661);
                ks::SceneManager::show_dialog(&scene, "hi", 662);
                ks::SceneManager::show_dialog(&scene, "", 663);
                ks::SceneManager::show_dialog(&scene, "ha_", 664);
                ks::SceneManager::show_dialog(&scene, "ha_", 665);
                ks::SceneManager::show_dialog(&scene, "", 634);
                ks::SceneManager::show_dialog(&scene, "", 635);
                ks::SceneManager::show_dialog(&scene, "ha_", 666);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "", 25);
                ks::SceneManager::show_dialog(&scene, "", 667);
                ks::SceneManager::show_dialog(&scene, "", 668);
                ks::SceneManager::show_dialog(&scene, "hi", 669);
                ks::SceneManager::show_dialog(&scene, "", 670);
                ks::SceneManager::show_dialog(&scene, "", 25);
                ks::SceneManager::show_dialog(&scene, "", 671);
                ks::SceneManager::show_dialog(&scene, "", 672);
                ks::SceneManager::show_dialog(&scene, "", 673);
                ks::SceneManager::show_dialog(&scene, "", 674);
                ks::SceneManager::show_dialog(&scene, "", 675);
                ks::SceneManager::show_dialog(&scene, "", 676);
                ks::SceneManager::set_background(bn::regular_bg_items::school_library_ss);
                ks::SceneManager::show_dialog(&scene, "", 677);
                return;
            }
            static void a1c5o1(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "hi", 678);
                ks::SceneManager::show_dialog(&scene, "ke", 679);
                return;
            }
            static void a1c5o2(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "hi", 680);
                ks::SceneManager::show_dialog(&scene, "ke", 119);
                return;
            }
            static void a1_tuesday_risk_vs_reward__menu_question_0(const ks::SceneManager scene) {
                // bn::vector<ks::AnswerItem, 2> answers;
                // answers.push_back(ks::AnswerItem("She has a point. Attack aggressively!", &ScriptA1TuesdayRu::a1_tuesday_risk_vs_reward__menu_question_0_she_has_a_point_attack_aggressively));
                // answers.push_back(ks::AnswerItem("It's a trap, it's smarter to play defensively here.", &ScriptA1TuesdayRu::a1_tuesday_risk_vs_reward__menu_question_0_its_a_trap_its_smarter_to_play_defensively_here));
                // scene.add_sequence(ks::MenuItem(answers);
            }
            static void a1_tuesday_risk_vs_reward__menu_question_0_she_has_a_point_attack_aggressively(const ks::SceneManager scene) {
                // scene.add_sequence(ks::AssignmentItem("attraction_sc += 1"));
                ScriptA1TuesdayRu::a1c3o1(scene);
            }
            static void a1_tuesday_risk_vs_reward__menu_question_0_its_a_trap_its_smarter_to_play_defensively_here(const ks::SceneManager scene) {
                ScriptA1TuesdayRu::a1c3o2(scene);
            }
            static void a1_tuesday_shared_library__menu_question_0(const ks::SceneManager scene) {
                // bn::vector<ks::AnswerItem, 2> answers;
                // answers.push_back(ks::AnswerItem("Hi! I'm new here. Hisao Nakai. We're in the same class.", &ScriptA1TuesdayRu::a1_tuesday_shared_library__menu_question_0_hi_im_new_here_hisao_nakai_were_in_the_same_class));
                // answers.push_back(ks::AnswerItem("I'm sorry, I didn't mean to startle you.", &ScriptA1TuesdayRu::a1_tuesday_shared_library__menu_question_0_im_sorry_i_didnt_mean_to_startle_you));
                // scene.add_sequence(ks::MenuItem(answers);
            }
            static void a1_tuesday_shared_library__menu_question_0_hi_im_new_here_hisao_nakai_were_in_the_same_class(const ks::SceneManager scene) {
                ScriptA1TuesdayRu::a1c4o1(scene);
            }
            static void a1_tuesday_shared_library__menu_question_0_im_sorry_i_didnt_mean_to_startle_you(const ks::SceneManager scene) {
                // scene.add_sequence(ks::AssignmentItem("attraction_hanako += 1"));
                ScriptA1TuesdayRu::a1c4o2(scene);
            }
            static void a1_tuesday_bizarre_and_surreal__menu_question_0(const ks::SceneManager scene) {
                // bn::vector<ks::AnswerItem, 2> answers;
                // answers.push_back(ks::AnswerItem("She was cute.", &ScriptA1TuesdayRu::a1_tuesday_bizarre_and_surreal__menu_question_0_she_was_cute));
                // answers.push_back(ks::AnswerItem("She wasn't cute.", &ScriptA1TuesdayRu::a1_tuesday_bizarre_and_surreal__menu_question_0_she_wasnt_cute));
                // scene.add_sequence(ks::MenuItem(answers);
            }
            static void a1_tuesday_bizarre_and_surreal__menu_question_0_she_was_cute(const ks::SceneManager scene) {
                // scene.add_sequence(ks::AssignmentItem("attraction_hanako += 1"));
                ScriptA1TuesdayRu::a1c5o1(scene);
            }
            static void a1_tuesday_bizarre_and_surreal__menu_question_0_she_wasnt_cute(const ks::SceneManager scene) {
                ScriptA1TuesdayRu::a1c5o2(scene);
            }
            static void a1_tuesday_smalltalk__condition_0_0(const ks::SceneManager scene) {
                return;
            }
            static void a1_tuesday_risk_vs_reward__condition_0_0(const ks::SceneManager scene) {
                return;
            }
            static void a1_tuesday_pseudo_tea_cosy__condition_0_0(const ks::SceneManager scene) {
                return;
            }
            static void a1_tuesday_shared_library__condition_0_0(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "hi", 681);
                ks::SceneManager::show_dialog(&scene, "", 682);
                ks::SceneManager::show_dialog(&scene, "yu", 683);
                ks::SceneManager::show_dialog(&scene, "hi", 684);
                ks::SceneManager::show_dialog(&scene, "yu", 685);
                ks::SceneManager::show_dialog(&scene, "hi", 686);
                ks::SceneManager::show_dialog(&scene, "yu", 687);
                ks::SceneManager::show_dialog(&scene, "", 688);
                ks::SceneManager::show_dialog(&scene, "", 689);
                ks::SceneManager::show_dialog(&scene, "", 690);
            }
            static void a1_tuesday_shared_library__condition_0_1(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "hi", 691);
                ks::SceneManager::show_dialog(&scene, "hi", 692);
                ks::SceneManager::show_dialog(&scene, "yu", 693);
                ks::SceneManager::show_dialog(&scene, "yu", 694);
                ks::SceneManager::show_dialog(&scene, "hi", 686);
                ks::SceneManager::show_dialog(&scene, "yu", 687);
                ks::SceneManager::show_dialog(&scene, "", 695);
                ks::SceneManager::show_dialog(&scene, "", 689);
            }
            static void a1_tuesday_shared_library__condition_1_0(const ks::SceneManager scene) {
                return;
            }
            static void a1_tuesday_bizarre_and_surreal__condition_0_0(const ks::SceneManager scene) {
                return;
            }
            static void a1c4o1__condition_0_0(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "hi", 696);
                ks::SceneManager::show_dialog(&scene, "", 25);
            }
    };
}