#ifndef KS_SCRIPT_A1_SUNDAY
#define KS_SCRIPT_A1_SUNDAY

#define SCENE_INLINE static inline __attribute__((always_inline))
#include "../scenemanager.h"
#include "../character.h"
#include "bn_regular_bg_items_kenji_bg_basic.h"
#include "bn_regular_bg_items_kenji_bg_rage.h"
#include "bn_regular_bg_items_emi_bg_basic.h"
#include "bn_regular_bg_items_emi_bg_sad.h"
#include "bn_regular_bg_items_emi_bg_excited.h"
#include "bn_regular_bg_items_rin_bg_basic.h"
#include "bn_regular_bg_items_rin_bg_negative.h"
#include "bn_regular_bg_items_rin_bg_relaxed.h"
#include "bn_regular_bg_items_rin_bg_negative_close.h"
#include "bn_regular_bg_items_rin_bg_basic_close.h"
#include "bn_regular_bg_items_rin_bg_relaxed_close.h"
#include "bn_regular_bg_items_lilly_bg_basic.h"
#include "bn_regular_bg_items_lilly_bg_basic2.h"
#include "bn_regular_bg_items_lilly_bg_basic3.h"
#include "bn_regular_bg_items_lilly_bg_cane.h"
#include "bn_regular_bg_items_hanako_bg_basic.h"
#include "bn_regular_bg_items_hanako_bg_emb.h"
#include "bn_regular_bg_items_lilly_bg_behind.h"
#include "bn_regular_bg_items_hanako_bg_def.h"
#include "bn_regular_bg_items_hanako_bg_defarms.h"
#include "bn_regular_bg_items_hanako_bg_cover.h"
#include "bn_regular_bg_items_yuukoshang_bg_up.h"
#include "bn_regular_bg_items_yuukoshang_bg_down.h"
#include "bn_regular_bg_items_shizu_bg_behind.h"
#include "bn_regular_bg_items_misha_bg_hips.h"
#include "bn_regular_bg_items_shizu_bg_basic.h"
#include "bn_regular_bg_items_misha_bg_sign.h"
#include "bn_regular_bg_items_shizu_bg_cross.h"
#include "bn_regular_bg_items_misha_bg_perky.h"
#include "bn_regular_bg_items_misha_bg_cross.h"
#include "bn_regular_bg_items_shizu_bg_adjust.h"
#include "background_metas/school_dormhisao.h"
#include "background_metas/school_dormhallway.h"
#include "background_metas/school_courtyard.h"
#include "background_metas/school_stalls1.h"
#include "background_metas/school_dormext_full.h"
#include "background_metas/mural.h"
#include "background_metas/school_gardens.h"
#include "background_metas/school_dormhisao_ni.h"
#include "background_metas/misc_sky_ss.h"
#include "background_metas/school_dormext_full_ss.h"
#include "background_metas/misc_sky_ni.h"
#include "background_metas/school_dormext_full_ni.h"
#include "background_metas/school_lobby.h"
#include "background_metas/school_staircase2.h"
#include "background_metas/school_hallway2.h"
#include "background_metas/hana_library_read.h"
#include "background_metas/school_library.h"
#include "background_metas/school_stalls1_ni.h"
#include "background_metas/school_gardens2_ni.h"
#include "background_metas/school_stalls2.h"
#include "background_metas/school_miyagi.h"
#include "background_metas/school_hallway3.h"
#include "background_metas/school_gate_ss.h"
#include "background_metas/school_road_ss.h"
#include "background_metas/suburb_shanghaiext.h"
#include "background_metas/suburb_shanghaiint.h"
#include "background_metas/hanako_fw.h"
#include "background_metas/suburb_shanghaiext_ni.h"
#include "background_metas/suburb_roadcenter_ni.h"
#include "background_metas/school_stalls1_ss.h"
#include "background_metas/school_courtyard_ss.h"
#include "background_metas/school_stalls2_ss.h"
#include "background_metas/school_courtyard_ni.h"
#include "background_metas/school_roof_ni.h"
#include "background_metas/misc_sky.h"
#include "background_metas/school_staircase1.h"
#include "background_metas/school_roof.h"
#include "background_metas/kenji_rooftop.h"
#include "bn_sprite_items_kenji_spr_basic_neutral.h"
#include "bn_sprite_items_kenji_spr_basic_happy.h"
#include "bn_sprite_items_kenji_spr_rage_rage.h"
#include "bn_sprite_items_kenji_spr_basic_tsun.h"
#include "bn_sprite_items_emi_spr_basic_annoyed.h"
#include "bn_sprite_items_emi_spr_sad_annoyed.h"
#include "bn_sprite_items_emi_spr_sad_angry.h"
#include "bn_sprite_items_emi_spr_basic_closedgrin.h"
#include "bn_sprite_items_emi_spr_basic_grin.h"
#include "bn_sprite_items_emi_spr_basic_happy.h"
#include "bn_sprite_items_emi_spr_excited_proud.h"
#include "bn_sprite_items_emi_spr_excited_happy.h"
#include "bn_sprite_items_emi_spr_sad_grin.h"
#include "bn_sprite_items_emi_spr_sad_shy.h"
#include "bn_sprite_items_emi_spr_basic_confused.h"
#include "bn_sprite_items_emi_spr_basic_hes.h"
#include "bn_sprite_items_emi_spr_basic_shock.h"
#include "bn_sprite_items_emi_spr_sad_depressed.h"
#include "bn_sprite_items_rin_spr_basic_absent.h"
#include "bn_sprite_items_rin_spr_basic_awayabsent.h"
#include "bn_sprite_items_emi_spr_basic_closedhappy.h"
#include "bn_sprite_items_rin_spr_basic_deadpan.h"
#include "bn_sprite_items_rin_spr_negative_spaciness.h"
#include "bn_sprite_items_rin_spr_relaxed_nonchalant.h"
#include "bn_sprite_items_rin_spr_basic_deadpannormal.h"
#include "bn_sprite_items_rin_spr_basic_lucid.h"
#include "bn_sprite_items_rin_spr_relaxed_surprised.h"
#include "bn_sprite_items_rin_spr_relaxed_boredom.h"
#include "bn_sprite_items_rin_spr_relaxed_sleepy.h"
#include "bn_sprite_items_rin_spr_basic_deadpanupset.h"
#include "bn_sprite_items_rin_spr_negative_spaciness_close.h"
#include "bn_sprite_items_rin_spr_basic_deadpannormal_close.h"
#include "bn_sprite_items_rin_spr_basic_deadpan_close.h"
#include "bn_sprite_items_rin_spr_basic_awayabsent_close.h"
#include "bn_sprite_items_rin_spr_negative_sad_close.h"
#include "bn_sprite_items_rin_spr_negative_annoyed_close.h"
#include "bn_sprite_items_rin_spr_basic_deadpancontemplation_close.h"
#include "bn_sprite_items_rin_spr_basic_absent_close.h"
#include "bn_sprite_items_rin_spr_basic_lucid_close.h"
#include "bn_sprite_items_rin_spr_basic_deadpanupset_close.h"
#include "bn_sprite_items_rin_spr_negative_confused_close.h"
#include "bn_sprite_items_rin_spr_negative_confused.h"
#include "bn_sprite_items_rin_spr_negative_annoyed.h"
#include "bn_sprite_items_rin_spr_negative_angry.h"
#include "bn_sprite_items_rin_spr_basic_deadpansurprised_close.h"
#include "bn_sprite_items_rin_spr_relaxed_sleepy_close.h"
#include "bn_sprite_items_rin_spr_negative_worried_close.h"
#include "bn_sprite_items_rin_spr_relaxed_doubt_close.h"
#include "bn_sprite_items_rin_spr_relaxed_surprised_close.h"
#include "bn_sprite_items_lilly_spr_basic_smile.h"
#include "bn_sprite_items_lilly_spr_basic_smileclosed.h"
#include "bn_sprite_items_lilly_spr_basic_pout.h"
#include "bn_sprite_items_lilly_spr_basic2_giggle.h"
#include "bn_sprite_items_lilly_spr_basic_reminisce.h"
#include "bn_sprite_items_lilly_spr_basic3_surprised.h"
#include "bn_sprite_items_lilly_spr_basic_displeased.h"
#include "bn_sprite_items_lilly_spr_cane_reminisce.h"
#include "bn_sprite_items_lilly_spr_cane_satisfied.h"
#include "bn_sprite_items_lilly_spr_cane_smileclosed.h"
#include "bn_sprite_items_lilly_spr_cane_smile.h"
#include "bn_sprite_items_lilly_spr_cane_sad.h"
#include "bn_sprite_items_lilly_spr_cane_weaksmile.h"
#include "bn_sprite_items_lilly_spr_cane_surprised.h"
#include "bn_sprite_items_lilly_spr_cane_cheerful.h"
#include "bn_sprite_items_hanako_spr_basic_normal.h"
#include "bn_sprite_items_lilly_spr_cane_pout.h"
#include "bn_sprite_items_hanako_spr_emb_downsmile.h"
#include "bn_sprite_items_hanako_spr_basic_bashful.h"
#include "bn_sprite_items_hanako_spr_basic_distant.h"
#include "bn_sprite_items_hanako_spr_basic_smile.h"
#include "bn_sprite_items_lilly_spr_basic_weaksmile.h"
#include "bn_sprite_items_lilly_spr_basic_concerned.h"
#include "bn_sprite_items_lilly_spr_behind_cheerful.h"
#include "bn_sprite_items_hanako_spr_def_shock.h"
#include "bn_sprite_items_hanako_spr_defarms_worry.h"
#include "bn_sprite_items_hanako_spr_cover_distant.h"
#include "bn_sprite_items_hanako_spr_emb_downtimid.h"
#include "bn_sprite_items_hanako_spr_emb_blushing.h"
#include "bn_sprite_items_hanako_spr_emb_emb.h"
#include "bn_sprite_items_hanako_spr_emb_downsad.h"
#include "bn_sprite_items_hanako_spr_emb_smile.h"
#include "bn_sprite_items_hanako_spr_basic_worry.h"
#include "bn_sprite_items_hanako_spr_def_worry.h"
#include "bn_sprite_items_hanako_spr_emb_timid.h"
#include "bn_sprite_items_hanako_spr_emb_blushtimid.h"
#include "bn_sprite_items_hanako_spr_defarms_shock.h"
#include "bn_sprite_items_hanako_spr_cover_bashful.h"
#include "bn_sprite_items_lilly_spr_basic2_planned.h"
#include "bn_sprite_items_yuukoshang_spr_up_panic.h"
#include "bn_sprite_items_yuukoshang_spr_up_neurotic.h"
#include "bn_sprite_items_yuukoshang_spr_down_smile.h"
#include "bn_sprite_items_yuukoshang_spr_up_noglasses.h"
#include "bn_sprite_items_yuukoshang_spr_down_neutral.h"
#include "bn_sprite_items_yuukoshang_spr_up_worried.h"
#include "bn_sprite_items_yuukoshang_spr_down_happy.h"
#include "bn_sprite_items_yuukoshang_spr_down_closedhappy.h"
#include "bn_sprite_items_lilly_spr_basic_cheerful.h"
#include "bn_sprite_items_lilly_spr_basic3_oops.h"
#include "bn_sprite_items_lilly_spr_basic3_listen.h"
#include "bn_sprite_items_lilly_spr_basic2_ara.h"
#include "bn_sprite_items_shizu_spr_behind_blank.h"
#include "bn_sprite_items_shizu_spr_behind_frustrated.h"
#include "bn_sprite_items_misha_spr_hips_grin.h"
#include "bn_sprite_items_shizu_spr_basic_angry.h"
#include "bn_sprite_items_misha_spr_sign_smile.h"
#include "bn_sprite_items_shizu_spr_cross_angry.h"
#include "bn_sprite_items_misha_spr_hips_frown.h"
#include "bn_sprite_items_misha_spr_perky_sad.h"
#include "bn_sprite_items_misha_spr_perky_smile.h"
#include "bn_sprite_items_misha_spr_cross_laugh.h"
#include "bn_sprite_items_shizu_spr_adjust_happy.h"
#include "bn_sprite_items_misha_spr_perky_confused.h"
#include "bn_sprite_items_shizu_spr_behind_frown.h"
#include "bn_sprite_items_shizu_spr_basic_normal2.h"
#include "bn_sprite_items_misha_spr_hips_smile.h"
#include "bn_sprite_items_shizu_spr_adjust_blush.h"
#include "bn_sprite_items_shizu_spr_adjust_smug.h"
#include "bn_sprite_items_shizu_spr_behind_smile.h"
#include "bn_sprite_items_shizu_spr_basic_normal.h"
#include "bn_sprite_items_misha_spr_cross_grin.h"
#include "bn_sprite_items_shizu_spr_cross_wut.h"
#include "bn_sprite_items_misha_spr_cross_smile.h"
#include "bn_sprite_items_shizu_spr_basic_sparkle.h"
#include "bn_sprite_items_shizu_spr_basic_happy.h"
#include "bn_sprite_items_shizu_spr_basic_frown.h"
#include "bn_sprite_items_lilly_spr_basic_sad.h"
#include "kenji_basic.h"
#include "kenji_rage.h"
#include "emi_basic.h"
#include "emi_sad.h"
#include "emi_excited.h"
#include "rin_basic.h"
#include "rin_negative.h"
#include "rin_relaxed.h"
#include "rin_negative_close.h"
#include "rin_basic_close.h"
#include "rin_relaxed_close.h"
#include "lilly_basic.h"
#include "lilly_basic2.h"
#include "lilly_basic3.h"
#include "lilly_cane.h"
#include "hanako_basic.h"
#include "hanako_emb.h"
#include "lilly_behind.h"
#include "hanako_def.h"
#include "hanako_defarms.h"
#include "hanako_cover.h"
#include "yuukoshang_up.h"
#include "yuukoshang_down.h"
#include "shizu_behind.h"
#include "misha_hips.h"
#include "shizu_basic.h"
#include "misha_sign.h"
#include "shizu_cross.h"
#include "misha_perky.h"
#include "misha_cross.h"
#include "shizu_adjust.h"
namespace ks {
    class ScriptA1Sunday {
        public:
            virtual ~ScriptA1Sunday() = default;
            // Labels
            SCENE_INLINE void a1_sunday_dont_panic();
            SCENE_INLINE void a1_sunday_is_carnival();
            SCENE_INLINE void a1_sunday_clouds_in_my_head();
            SCENE_INLINE void a1_sunday_promise_of_time();
            SCENE_INLINE void a1_sunday_nc5xb3();
            SCENE_INLINE void a1_sunday_movement();
            SCENE_INLINE void a1_sunday_throwing_balls();
            SCENE_INLINE void a1_sunday_the_deep_end();
            static void a1_sunday();
            SCENE_INLINE void stranger_lilly_and_hanako();
            SCENE_INLINE void stranger_union();
            SCENE_INLINE void lilly_and_hanako_union();
            // Choice functions
            // Conditions
            SCENE_INLINE void a1_sunday__condition_0_0();
            SCENE_INLINE void a1_sunday_dont_panic__condition_0_0();
            SCENE_INLINE void a1_sunday_is_carnival__condition_0_0();
            SCENE_INLINE void a1_sunday__condition_1_0();
            SCENE_INLINE void a1_sunday_clouds_in_my_head__condition_0_0();
            SCENE_INLINE void a1_sunday__condition_2_0();
            SCENE_INLINE void a1_sunday_promise_of_time__condition_0_0();
            SCENE_INLINE void a1_sunday__condition_3_0();
            SCENE_INLINE void a1_sunday_nc5xb3__condition_0_0();
            SCENE_INLINE void a1_sunday_movement__condition_0_0();
            SCENE_INLINE void a1_sunday__condition_4_0();
            SCENE_INLINE void a1_sunday_throwing_balls__condition_0_0();
            SCENE_INLINE void a1_sunday__condition_5_0();
            SCENE_INLINE void a1_sunday_the_deep_end__condition_0_0();
            SCENE_INLINE void a1_sunday__condition_6_0();
    };
}

#endif // KS_SCRIPT_A1_SUNDAY