#include "script_a1_tuesday.h"
#include "script_a1_tuesday_en_tl_index.h"
namespace ks {
    class ScriptA1TuesdayEn : public ScriptA1Tuesday {
        public:
            static void a1_tuesday_smalltalk() {
                // POTENTIAL MEMLEAK!!!! better to provide it globally.
                // bn::optional<bn::regular_bg_ptr> main_bg;
                constexpr ks::SceneManager scene = ks::SceneManager("script_a1_tuesday", "en", script_a1_tuesday_en_intl);
            
                ks::SceneManager::reset();
                ks::SceneManager::set_background(bn::regular_bg_items::school_dormhisao);
                ks::SceneManager::show_dialog(&scene, "", 0);
                ks::SceneManager::show_dialog(&scene, "", 1);
                ks::SceneManager::show_dialog(&scene, "", 2);
                ks::SceneManager::show_dialog(&scene, "", 3);
                ks::SceneManager::music_play("music_dreamy.gsm");
                ks::SceneManager::show_dialog(&scene, "", 4);
                ks::SceneManager::show_dialog(&scene, "", 5);
                ks::SceneManager::show_dialog(&scene, "", 6);
                ks::SceneManager::show_dialog(&scene, "", 7);
                ks::SceneManager::show_dialog(&scene, "", 8);
                ks::SceneManager::show_dialog(&scene, "", 9);
                ks::SceneManager::show_dialog(&scene, "", 10);
                ks::SceneManager::show_dialog(&scene, "", 11);
                ks::SceneManager::show_dialog(&scene, "", 12);
                ks::SceneManager::show_dialog(&scene, "", 13);
                ks::SceneManager::show_dialog(&scene, "", 14);
                ks::SceneManager::show_dialog(&scene, "", 15);
                ks::SceneManager::show_dialog(&scene, "", 16);
                ks::SceneManager::show_dialog(&scene, "", 17);
                ks::SceneManager::show_dialog(&scene, "", 18);
                ks::SceneManager::show_dialog(&scene, "", 19);
                ks::SceneManager::show_dialog(&scene, "", 20);
                ks::SceneManager::show_dialog(&scene, "", 21);
                ks::SceneManager::show_dialog(&scene, "", 22);
                ks::SceneManager::music_stop();
                ks::SceneManager::set_background(bn::regular_bg_items::school_scienceroom);
                ks::SceneManager::show_dialog(&scene, "", 23);
                ks::SceneManager::show_dialog(&scene, "", 24);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_cross, bn::sprite_items::shizu_spr_cross_wut, ks::sprite_metas::shizu_cross);
                ks::SceneManager::show_dialog(&scene, "", 26);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_cross, bn::sprite_items::shizu_spr_cross_angry, ks::sprite_metas::shizu_cross);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_cross, bn::sprite_items::shizu_spr_cross_angry, ks::sprite_metas::shizu_cross, 48, 0);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips, -48, 0);
                ks::SceneManager::music_play("music_happiness.gsm");
                ks::SceneManager::show_dialog(&scene, "mi", 27);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_angry, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 28);
                ks::SceneManager::show_dialog(&scene, "", 29);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal2, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_smile, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog(&scene, "mi", 30);
                ks::SceneManager::show_dialog(&scene, "mi", 31);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 32);
                ks::SceneManager::show_dialog(&scene, "hi", 33);
                ks::SceneManager::show_dialog(&scene, "hi", 34);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "", 35);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_laugh, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 36);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_confused, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "", 37);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_confused, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog(&scene, "mi", 38);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 39);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "", 40);
                ks::SceneManager::show_dialog(&scene, "", 41);
                ks::SceneManager::show_dialog(&scene, "hi", 42);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_frown, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 43);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 44);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 45);
                ks::SceneManager::show_dialog(&scene, "", 46);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_sad, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog(&scene, "", 47);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_angry, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 48);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 49);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_sparkle, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_smile, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog(&scene, "mi", 50);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "", 51);
                ks::SceneManager::show_dialog(&scene, "hi", 52);
                ks::SceneManager::show_dialog(&scene, "", 53);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "", 54);
                ks::SceneManager::show_dialog(&scene, "", 55);
                ks::SceneManager::show_dialog(&scene, "", 56);
                ks::SceneManager::show_dialog(&scene, "", 57);
                ks::SceneManager::show_dialog(&scene, "", 58);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 59);
                ks::SceneManager::show_dialog(&scene, "", 60);
                ks::SceneManager::show_dialog(&scene, "", 61);
                ks::SceneManager::show_dialog(&scene, "hi", 62);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_happy, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 63);
                ks::SceneManager::show_dialog(&scene, "", 64);
                ks::SceneManager::show_dialog(&scene, "hi", 65);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 66);
                ks::SceneManager::show_dialog(&scene, "hi", 33);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_laugh, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi", 67);
                ks::SceneManager::set_background(bn::regular_bg_items::school_scienceroom);
                ks::SceneManager::show_dialog(&scene, "", 68);
                ks::SceneManager::show_dialog(&scene, "", 69);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_frown, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "", 70);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind, 48, 0);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips, -48, 0);
                ks::SceneManager::music_play("music_comedy.gsm");
                ks::SceneManager::show_dialog(&scene, "mi", 71);
                ks::SceneManager::show_dialog(&scene, "hi", 72);
                ks::SceneManager::show_dialog(&scene, "mi", 73);
                ks::SceneManager::show_dialog(&scene, "hi", 74);
                ks::SceneManager::show_dialog(&scene, "", 75);
                ks::SceneManager::show_dialog(&scene, "", 76);
                ks::SceneManager::show_dialog(&scene, "", 77);
                ks::SceneManager::show_dialog(&scene, "", 78);
                ks::SceneManager::show_dialog(&scene, "hi", 79);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_happy, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "", 80);
                ks::SceneManager::show_dialog(&scene, "", 81);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 82);
                ks::SceneManager::show_dialog(&scene, "hi", 83);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 84);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_laugh, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 85);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "", 86);
                ks::SceneManager::hide_character(0);
                ks::SceneManager::hide_character(1);
                ks::SceneManager::show_dialog(&scene, "", 87);
                ks::SceneManager::set_background(bn::regular_bg_items::school_hallway3);
                ks::SceneManager::show_dialog(&scene, "", 88);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips, -120, 0);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind, 120, 0);
                ks::SceneManager::set_character_position(1, -48, 0);
                ks::SceneManager::set_character_position(0, 48, 0);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 89);
                ks::SceneManager::show_dialog(&scene, "hi", 90);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_laugh, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 91);
                ks::SceneManager::show_dialog(&scene, "", 92);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "", 93);
                ks::SceneManager::show_dialog(&scene, "", 94);
                ks::SceneManager::set_background(bn::regular_bg_items::school_cafeteria);
                ks::SceneManager::show_dialog(&scene, "", 95);
                ks::SceneManager::show_dialog(&scene, "", 96);
                ks::SceneManager::music_play("music_shizune.gsm");
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky, -48, 0);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind, 48, 0);
                ks::SceneManager::show_dialog(&scene, "mi", 97);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "mi", 98);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "", 99);
                ks::SceneManager::show_dialog(&scene, "mi", 100);
                ks::SceneManager::show_dialog(&scene, "hi", 101);
                ks::SceneManager::show_dialog(&scene, "hi", 102);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 103);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_happy, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "mi", 104);
                ks::SceneManager::show_dialog(&scene, "hi", 105);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_laugh, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi", 106);
                ks::SceneManager::show_dialog(&scene, "hi", 107);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_grin, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "mi", 108);
                ks::SceneManager::show_dialog(&scene, "mi", 109);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_laugh, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 110);
                ks::SceneManager::show_dialog(&scene, "", 111);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_blush, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "", 112);
                ks::SceneManager::show_dialog(&scene, "", 113);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_grin, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi", 114);
                ks::SceneManager::show_dialog(&scene, "hi", 115);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_smile, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi", 116);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 117);
                ks::SceneManager::show_dialog(&scene, "", 118);
                ks::SceneManager::show_dialog(&scene, "", 119);
                ks::SceneManager::show_dialog(&scene, "", 120);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 121);
                ks::SceneManager::show_dialog(&scene, "hi", 122);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 123);
                ks::SceneManager::show_dialog(&scene, "mi", 124);
                ks::SceneManager::show_dialog(&scene, "mi", 125);
                ks::SceneManager::show_dialog(&scene, "", 126);
                ks::SceneManager::show_dialog(&scene, "hi", 127);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 128);
                ks::SceneManager::show_dialog(&scene, "hi", 129);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_sad, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 130);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 131);
                ks::SceneManager::show_dialog(&scene, "hi", 132);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_happy, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "", 133);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_laugh, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi", 134);
                ks::SceneManager::show_dialog(&scene, "hi", 135);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 136);
                ks::SceneManager::show_dialog(&scene, "hi", 137);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_sad, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 138);
                ks::SceneManager::show_dialog(&scene, "hi", 139);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 140);
                ks::SceneManager::show_dialog(&scene, "hi", 141);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_angry, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_frown, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 142);
                ks::SceneManager::show_dialog(&scene, "hi", 143);
                ks::SceneManager::show_dialog(&scene, "", 144);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "mi", 145);
                ks::SceneManager::show_dialog(&scene, "hi", 146);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 147);
                ks::SceneManager::show_dialog(&scene, "hi", 148);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 149);
                ks::SceneManager::show_dialog(&scene, "mi", 150);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "mi", 151);
                ks::SceneManager::show_dialog(&scene, "hi", 152);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_laugh, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi", 153);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_grin, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "", 154);
                ks::SceneManager::show_dialog(&scene, "", 155);
                ks::SceneManager::show_dialog(&scene, "", 156);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_smile, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog(&scene, "mi", 157);
                ks::SceneManager::show_dialog(&scene, "hi", 158);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 159);
                ks::SceneManager::show_dialog(&scene, "", 160);
                ks::SceneManager::show_dialog(&scene, "mi", 161);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "mi", 162);
                ks::SceneManager::show_dialog(&scene, "hi", 163);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 164);
                ks::SceneManager::show_dialog(&scene, "hi", 165);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 166);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_laugh, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi", 85);
                ks::SceneManager::show_dialog(&scene, "", 167);
                ks::SceneManager::show_dialog(&scene, "", 168);
                ks::SceneManager::show_dialog(&scene, "", 169);
                ks::SceneManager::music_stop();
                ks::SceneManager::set_background(bn::regular_bg_items::school_scienceroom);
                ks::SceneManager::show_dialog(&scene, "", 170);
                ks::SceneManager::show_dialog(&scene, "", 171);
                // bn::vector<ks::ConditionItem, 1> a1_tuesday_smalltalk__condition_0;
                // a1_tuesday_smalltalk__condition_0.push_back(ks::ConditionItem("_in_replay", &ScriptA1TuesdayEn::a1_tuesday_smalltalk__condition_0_0));
                // scene.add_condition(a1_tuesday_smalltalk__condition_0);
            }
            static void a1_tuesday_risk_vs_reward() {
                // POTENTIAL MEMLEAK!!!! better to provide it globally.
                // bn::optional<bn::regular_bg_ptr> main_bg;
                constexpr ks::SceneManager scene = ks::SceneManager("script_a1_tuesday", "en", script_a1_tuesday_en_intl);
            
                ks::SceneManager::reset();
                ks::SceneManager::set_background(bn::regular_bg_items::school_lobby);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind, 48, 0);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips, -48, 0);
                ks::SceneManager::music_play("music_ease.gsm");
                ks::SceneManager::show_dialog(&scene, "", 172);
                ks::SceneManager::show_dialog(&scene, "", 173);
                ks::SceneManager::show_dialog(&scene, "hi", 174);
                ks::SceneManager::show_dialog(&scene, "", 175);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_laugh, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi", 176);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_grin, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi", 177);
                ks::SceneManager::show_dialog(&scene, "", 178);
                ks::SceneManager::show_dialog(&scene, "", 179);
                ks::SceneManager::hide_character(1);
                ks::SceneManager::hide_character(0);
                ks::SceneManager::show_dialog(&scene, "", 180);
                ks::SceneManager::show_dialog(&scene, "hi", 181);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal2, ks::sprite_metas::shizu_basic, 48, 0);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky, -48, 0);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 182);
                ks::SceneManager::show_dialog(&scene, "hi", 183);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "", 184);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 185);
                ks::SceneManager::show_dialog(&scene, "", 186);
                ks::SceneManager::music_stop();
                ks::SceneManager::set_background(bn::regular_bg_items::school_council);
                ks::SceneManager::show_dialog(&scene, "", 187);
                ks::SceneManager::show_dialog(&scene, "", 188);
                ks::SceneManager::show_dialog(&scene, "", 189);
                ks::SceneManager::show_dialog(&scene, "", 190);
                ks::SceneManager::show_dialog(&scene, "hi", 191);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind, 48, 0);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips, -48, 0);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 192);
                ks::SceneManager::show_dialog(&scene, "hi", 193);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_smile, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog(&scene, "mi", 194);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_happy, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "", 195);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 196);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 197);
                ks::SceneManager::hide_character(0);
                ks::SceneManager::show_dialog(&scene, "", 198);
                ks::SceneManager::show_dialog(&scene, "", 199);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_frown, ks::sprite_metas::shizu_adjust, 48, 0);
                ks::SceneManager::show_dialog(&scene, "", 200);
                ks::SceneManager::show_dialog(&scene, "", 201);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal2, ks::sprite_metas::shizu_basic);
                ks::SceneManager::music_play("music_running.gsm");
                ks::SceneManager::show_dialog(&scene, "", 202);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_smile, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog(&scene, "mi", 203);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 204);
                ks::SceneManager::show_dialog(&scene, "hi", 205);
                ks::SceneManager::show_dialog(&scene, "", 206);
                ks::SceneManager::show_dialog(&scene, "hi", 207);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "mi", 208);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_laugh, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi", 209);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_grin, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "hi", 210);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "", 211);
                ks::SceneManager::show_dialog(&scene, "hi", 212);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 213);
                ks::SceneManager::show_dialog(&scene, "", 214);
                ks::SceneManager::show_dialog(&scene, "", 215);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_happy, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "", 216);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_confused, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog(&scene, "mi", 217);
                ks::SceneManager::show_dialog(&scene, "hi", 218);
                ks::SceneManager::show_dialog(&scene, "mi", 219);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_sparkle, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "", 220);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_happy, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_smile, ks::sprite_metas::misha_cross);
                ScriptA1TuesdayEn::a1_tuesday_risk_vs_reward__menu_question_0(scene);
                ks::SceneManager::show_dialog(&scene, "", 221);
                ks::SceneManager::show_dialog(&scene, "hi", 222);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "", 223);
                ks::SceneManager::show_dialog(&scene, "", 224);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 225);
                ks::SceneManager::show_dialog(&scene, "mi", 226);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 227);
                ks::SceneManager::show_dialog(&scene, "hi", 228);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 229);
                ks::SceneManager::music_stop();
                // bn::vector<ks::ConditionItem, 1> a1_tuesday_risk_vs_reward__condition_0;
                // a1_tuesday_risk_vs_reward__condition_0.push_back(ks::ConditionItem("_in_replay", &ScriptA1TuesdayEn::a1_tuesday_risk_vs_reward__condition_0_0));
                // scene.add_condition(a1_tuesday_risk_vs_reward__condition_0);
            }
            static void a1_tuesday_pseudo_tea_cosy() {
                // POTENTIAL MEMLEAK!!!! better to provide it globally.
                // bn::optional<bn::regular_bg_ptr> main_bg;
                constexpr ks::SceneManager scene = ks::SceneManager("script_a1_tuesday", "en", script_a1_tuesday_en_intl);
            
                ks::SceneManager::reset();
                ks::SceneManager::set_background(bn::regular_bg_items::school_staircase2);
                ks::SceneManager::set_background(bn::regular_bg_items::school_hallway2);
                ks::SceneManager::show_dialog(&scene, "", 230);
                ks::SceneManager::show_dialog(&scene, "", 231);
                ks::SceneManager::show_dialog(&scene, "", 232);
                ks::SceneManager::show_dialog(&scene, "", 233);
                ks::SceneManager::show_dialog(&scene, "", 234);
                ks::SceneManager::show_dialog(&scene, "", 235);
                ks::SceneManager::show_dialog(&scene, "", 236);
                ks::SceneManager::show_dialog(&scene, "", 237);
                ks::SceneManager::show_dialog(&scene, "", 238);
                ks::SceneManager::show_dialog(&scene, "", 239);
                ks::SceneManager::show_dialog(&scene, "", 240);
                ks::SceneManager::show_dialog(&scene, "", 241);
                ks::SceneManager::show_dialog(&scene, "", 242);
                ks::SceneManager::show_dialog(&scene, "", 243);
                ks::SceneManager::show_dialog(&scene, "", 244);
                ks::SceneManager::music_play("music_lilly.gsm");
                ks::SceneManager::set_background(bn::regular_bg_items::lilly_tearoom);
                ks::SceneManager::show_dialog(&scene, "", 25);
                ks::SceneManager::show_dialog(&scene, "", 245);
                ks::SceneManager::show_dialog(&scene, "", 246);
                ks::SceneManager::show_dialog(&scene, "", 247);
                ks::SceneManager::show_dialog(&scene, "", 248);
                ks::SceneManager::set_background(bn::regular_bg_items::lilly_tearoom_open);
                ks::SceneManager::show_dialog(&scene, "li_", 249);
                ks::SceneManager::show_dialog(&scene, "", 250);
                ks::SceneManager::show_dialog(&scene, "", 251);
                ks::SceneManager::show_dialog(&scene, "", 252);
                ks::SceneManager::show_dialog(&scene, "hi", 253);
                ks::SceneManager::show_dialog(&scene, "", 254);
                ks::SceneManager::show_dialog(&scene, "li_", 255);
                ks::SceneManager::show_dialog(&scene, "", 256);
                ks::SceneManager::show_dialog(&scene, "hi", 257);
                ks::SceneManager::show_dialog(&scene, "", 258);
                ks::SceneManager::show_dialog(&scene, "", 259);
                ks::SceneManager::show_dialog(&scene, "", 260);
                ks::SceneManager::show_dialog(&scene, "", 261);
                ks::SceneManager::set_background(bn::regular_bg_items::lilly_tearoom);
                ks::SceneManager::show_dialog(&scene, "", 262);
                ks::SceneManager::show_dialog(&scene, "li_", 263);
                ks::SceneManager::show_dialog(&scene, "hi", 264);
                ks::SceneManager::show_dialog(&scene, "", 265);
                ks::SceneManager::show_dialog(&scene, "", 266);
                ks::SceneManager::set_background(bn::regular_bg_items::lilly_tearoom_open);
                ks::SceneManager::show_dialog(&scene, "li_", 267);
                ks::SceneManager::show_dialog(&scene, "hi", 268);
                ks::SceneManager::show_dialog(&scene, "", 269);
                ks::SceneManager::show_dialog(&scene, "li", 270);
                ks::SceneManager::show_dialog(&scene, "hi", 33);
                ks::SceneManager::show_dialog(&scene, "", 271);
                ks::SceneManager::show_dialog(&scene, "", 272);
                ks::SceneManager::set_background(bn::regular_bg_items::school_miyagi);
                ks::SceneManager::show_dialog(&scene, "", 273);
                ks::SceneManager::show_dialog(&scene, "", 274);
                ks::SceneManager::show_dialog(&scene, "", 275);
                ks::SceneManager::show_dialog(&scene, "", 276);
                ks::SceneManager::show_dialog(&scene, "", 277);
                ks::SceneManager::show_dialog(&scene, "", 278);
                ks::SceneManager::show_dialog(&scene, "li", 279);
                ks::SceneManager::show_dialog(&scene, "", 280);
                ks::SceneManager::show_dialog(&scene, "li", 281);
                ks::SceneManager::show_dialog(&scene, "hi", 282);
                ks::SceneManager::show_dialog(&scene, "", 283);
                ks::SceneManager::show_dialog(&scene, "li", 284);
                ks::SceneManager::show_dialog(&scene, "hi", 285);
                ks::SceneManager::show_dialog(&scene, "", 286);
                ks::SceneManager::show_dialog(&scene, "li", 287);
                ks::SceneManager::set_background(bn::regular_bg_items::tearoom_lillyhisao_noon);
                ks::SceneManager::show_dialog(&scene, "", 288);
                ks::SceneManager::show_dialog(&scene, "", 289);
                ks::SceneManager::show_dialog(&scene, "hi", 290);
                ks::SceneManager::show_dialog(&scene, "", 291);
                ks::SceneManager::show_dialog(&scene, "li", 292);
                ks::SceneManager::show_dialog(&scene, "", 293);
                ks::SceneManager::show_dialog(&scene, "", 294);
                ks::SceneManager::show_dialog(&scene, "hi", 295);
                ks::SceneManager::show_dialog(&scene, "li", 296);
                ks::SceneManager::show_dialog(&scene, "hi", 297);
                ks::SceneManager::show_dialog(&scene, "", 298);
                ks::SceneManager::show_dialog(&scene, "li", 299);
                ks::SceneManager::show_dialog(&scene, "hi", 300);
                ks::SceneManager::show_dialog(&scene, "li", 301);
                ks::SceneManager::show_dialog(&scene, "", 302);
                ks::SceneManager::show_dialog(&scene, "hi", 303);
                ks::SceneManager::show_dialog(&scene, "", 304);
                ks::SceneManager::show_dialog(&scene, "li", 305);
                ks::SceneManager::show_dialog(&scene, "", 306);
                ks::SceneManager::show_dialog(&scene, "", 307);
                ks::SceneManager::show_dialog(&scene, "", 308);
                ks::SceneManager::show_dialog(&scene, "hi", 309);
                ks::SceneManager::show_dialog(&scene, "li", 310);
                ks::SceneManager::show_dialog(&scene, "li", 311);
                ks::SceneManager::show_dialog(&scene, "", 312);
                ks::SceneManager::show_dialog(&scene, "", 313);
                ks::SceneManager::show_dialog(&scene, "hi", 314);
                ks::SceneManager::show_dialog(&scene, "li", 315);
                ks::SceneManager::show_dialog(&scene, "hi", 316);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "", 317);
                ks::SceneManager::show_dialog(&scene, "", 318);
                ks::SceneManager::set_background(bn::regular_bg_items::tearoom_lillyhisao_sunset);
                ks::SceneManager::music_play("music_tranquil.gsm");
                ks::SceneManager::show_dialog(&scene, "", 319);
                ks::SceneManager::show_dialog(&scene, "", 320);
                ks::SceneManager::show_dialog(&scene, "hi", 321);
                ks::SceneManager::show_dialog(&scene, "li", 143);
                ks::SceneManager::show_dialog(&scene, "", 322);
                ks::SceneManager::show_dialog(&scene, "hi", 323);
                ks::SceneManager::show_dialog(&scene, "", 324);
                ks::SceneManager::show_dialog(&scene, "li", 325);
                ks::SceneManager::show_dialog(&scene, "", 326);
                ks::SceneManager::show_dialog(&scene, "hi", 327);
                ks::SceneManager::show_dialog(&scene, "", 328);
                ks::SceneManager::show_dialog(&scene, "", 329);
                ks::SceneManager::show_dialog(&scene, "li", 330);
                ks::SceneManager::show_dialog(&scene, "", 331);
                ks::SceneManager::show_dialog(&scene, "hi", 332);
                ks::SceneManager::show_dialog(&scene, "", 333);
                ks::SceneManager::show_dialog(&scene, "li", 334);
                ks::SceneManager::show_dialog(&scene, "li", 335);
                ks::SceneManager::show_dialog(&scene, "hi", 336);
                ks::SceneManager::show_dialog(&scene, "", 337);
                ks::SceneManager::show_dialog(&scene, "li", 338);
                ks::SceneManager::show_dialog(&scene, "", 339);
                ks::SceneManager::show_dialog(&scene, "hi", 340);
                ks::SceneManager::set_background(bn::regular_bg_items::school_miyagi_ss);
                ks::SceneManager::show_dialog(&scene, "", 341);
                ks::SceneManager::show_dialog(&scene, "", 342);
                ks::SceneManager::show_dialog(&scene, "", 343);
                ks::SceneManager::music_stop();
                ks::SceneManager::set_background(bn::regular_bg_items::school_hallway2);
                ks::SceneManager::show_dialog(&scene, "", 344);
                ks::SceneManager::show_dialog(&scene, "", 345);
                ks::SceneManager::show_dialog(&scene, "hi", 346);
                ks::SceneManager::show_dialog(&scene, "", 347);
                ks::SceneManager::set_background(bn::regular_bg_items::school_library_ss);
                ks::SceneManager::music_play("music_happiness.gsm");
                ks::SceneManager::show_dialog(&scene, "", 348);
                ks::SceneManager::show_dialog(&scene, "", 349);
                ks::SceneManager::show_dialog(&scene, "", 350);
                ks::SceneManager::show_dialog(&scene, "li", 351);
                ks::SceneManager::show_dialog(&scene, "", 352);
                ks::SceneManager::show_dialog(&scene, "", 353);
                ks::SceneManager::show_dialog(&scene, "", 354);
                ks::SceneManager::show_dialog(&scene, "mystery", 355);
                ks::SceneManager::show_dialog(&scene, "", 356);
                ks::SceneManager::show_dialog(&scene, "yu_", 357);
                ks::SceneManager::show_dialog(&scene, "", 358);
                ks::SceneManager::show_dialog(&scene, "li", 359);
                ks::SceneManager::show_dialog(&scene, "yu_", 360);
                ks::SceneManager::show_dialog(&scene, "yu_", 361);
                ks::SceneManager::show_dialog(&scene, "li", 362);
                ks::SceneManager::show_dialog(&scene, "yu_", 363);
                ks::SceneManager::show_dialog(&scene, "yu_", 364);
                ks::SceneManager::show_dialog(&scene, "", 365);
                ks::SceneManager::show_dialog(&scene, "yu_", 366);
                ks::SceneManager::show_dialog(&scene, "", 367);
                ks::SceneManager::show_dialog(&scene, "", 368);
                ks::SceneManager::show_dialog(&scene, "yu_", 369);
                ks::SceneManager::show_dialog(&scene, "li", 370);
                ks::SceneManager::show_dialog(&scene, "li", 371);
                ks::SceneManager::show_dialog(&scene, "yu_", 372);
                ks::SceneManager::show_dialog(&scene, "", 373);
                ks::SceneManager::show_dialog(&scene, "yu_", 374);
                ks::SceneManager::show_dialog(&scene, "yu_", 375);
                ks::SceneManager::show_dialog(&scene, "", 376);
                ks::SceneManager::show_dialog(&scene, "li", 377);
                ks::SceneManager::show_dialog(&scene, "hi", 378);
                ks::SceneManager::show_dialog(&scene, "yu", 379);
                ks::SceneManager::show_dialog(&scene, "", 380);
                ks::SceneManager::show_dialog(&scene, "li", 381);
                ks::SceneManager::show_dialog(&scene, "li", 382);
                ks::SceneManager::show_dialog(&scene, "", 383);
                ks::SceneManager::show_dialog(&scene, "yu", 384);
                ks::SceneManager::show_dialog(&scene, "", 385);
                ks::SceneManager::show_dialog(&scene, "li", 386);
                ks::SceneManager::show_dialog(&scene, "hi", 387);
                ks::SceneManager::show_dialog(&scene, "", 388);
                ks::SceneManager::show_dialog(&scene, "yu", 389);
                ks::SceneManager::show_dialog(&scene, "", 390);
                ks::SceneManager::show_dialog(&scene, "hi", 391);
                ks::SceneManager::show_dialog(&scene, "yu", 392);
                ks::SceneManager::show_dialog(&scene, "yu", 393);
                ks::SceneManager::show_dialog(&scene, "yu", 394);
                ks::SceneManager::show_dialog(&scene, "", 25);
                ks::SceneManager::show_dialog(&scene, "", 395);
                ks::SceneManager::show_dialog(&scene, "hi", 396);
                ks::SceneManager::show_dialog(&scene, "", 397);
                ks::SceneManager::show_dialog(&scene, "li", 398);
                ks::SceneManager::music_stop();
                // bn::vector<ks::ConditionItem, 1> a1_tuesday_pseudo_tea_cosy__condition_0;
                // a1_tuesday_pseudo_tea_cosy__condition_0.push_back(ks::ConditionItem("_in_replay", &ScriptA1TuesdayEn::a1_tuesday_pseudo_tea_cosy__condition_0_0));
                // scene.add_condition(a1_tuesday_pseudo_tea_cosy__condition_0);
            }
            static void a1_tuesday_shared_library() {
                // POTENTIAL MEMLEAK!!!! better to provide it globally.
                // bn::optional<bn::regular_bg_ptr> main_bg;
                constexpr ks::SceneManager scene = ks::SceneManager("script_a1_tuesday", "en", script_a1_tuesday_en_intl);
            
                ks::SceneManager::reset();
                ks::SceneManager::set_background(bn::regular_bg_items::school_library_ss);
                ks::SceneManager::show_dialog(&scene, "", 399);
                ks::SceneManager::show_dialog(&scene, "", 400);
                ks::SceneManager::show_dialog(&scene, "", 401);
                ks::SceneManager::show_dialog(&scene, "", 402);
                ks::SceneManager::show_dialog(&scene, "", 403);
                ks::SceneManager::show_dialog(&scene, "", 404);
                ks::SceneManager::show_dialog(&scene, "", 405);
                ks::SceneManager::show_dialog(&scene, "", 406);
                ks::SceneManager::show_dialog(&scene, "", 407);
                ks::SceneManager::show_dialog(&scene, "", 408);
                ks::SceneManager::music_play("music_another.gsm");
                ks::SceneManager::show_dialog(&scene, "", 409);
                ks::SceneManager::show_dialog(&scene, "", 410);
                ks::SceneManager::show_dialog(&scene, "", 411);
                ks::SceneManager::show_dialog(&scene, "", 412);
                ks::SceneManager::show_dialog(&scene, "", 413);
                ks::SceneManager::show_dialog(&scene, "", 414);
                ks::SceneManager::show_dialog(&scene, "", 415);
                ks::SceneManager::show_dialog(&scene, "", 416);
                ks::SceneManager::show_dialog(&scene, "", 417);
                ks::SceneManager::show_dialog(&scene, "", 418);
                ScriptA1TuesdayEn::a1_tuesday_shared_library__menu_question_0(scene);
                ks::SceneManager::show_dialog(&scene, "ha", 419);
                ks::SceneManager::show_dialog(&scene, "ha", 420);
                ks::SceneManager::show_dialog(&scene, "hi", 421);
                ks::SceneManager::show_dialog(&scene, "ha", 422);
                ks::SceneManager::show_dialog(&scene, "", 423);
                ks::SceneManager::show_dialog(&scene, "", 424);
                ks::SceneManager::set_background(bn::regular_bg_items::school_library_ss);
                ks::SceneManager::music_play("music_pearly.gsm");
                ks::SceneManager::show_dialog(&scene, "", 425);
                ks::SceneManager::show_dialog(&scene, "", 426);
                ks::SceneManager::show_dialog(&scene, "", 427);
                ks::SceneManager::show_dialog(&scene, "hi", 428);
                ks::SceneManager::show_dialog(&scene, "yu", 429);
                ks::SceneManager::show_dialog(&scene, "hi", 430);
                ks::SceneManager::show_dialog(&scene, "li", 431);
                ks::SceneManager::show_dialog(&scene, "hi", 432);
                ks::SceneManager::show_dialog(&scene, "li", 433);
                ks::SceneManager::show_dialog(&scene, "yu", 434);
                ks::SceneManager::show_dialog(&scene, "hi", 435);
                ks::SceneManager::show_dialog(&scene, "li", 436);
                ks::SceneManager::show_dialog(&scene, "hi", 437);
                ks::SceneManager::show_dialog(&scene, "", 438);
                ks::SceneManager::show_dialog(&scene, "hi", 439);
                ks::SceneManager::show_dialog(&scene, "hi", 440);
                ks::SceneManager::show_dialog(&scene, "yu", 441);
                // bn::vector<ks::ConditionItem, 2> a1_tuesday_shared_library__condition_0;
                // a1_tuesday_shared_library__condition_0.push_back(ks::ConditionItem(""Hi! I'm new here. Hisao Nakai. We're in the same class." in choices", &ScriptA1TuesdayEn::a1_tuesday_shared_library__condition_0_0));
                // a1_tuesday_shared_library__condition_0.push_back(ks::ConditionItem("None", &ScriptA1TuesdayEn::a1_tuesday_shared_library__condition_0_1));
                // scene.add_condition(a1_tuesday_shared_library__condition_0);
                ks::SceneManager::show_dialog(&scene, "hi", 442);
                ks::SceneManager::show_dialog(&scene, "hi", 443);
                ks::SceneManager::show_dialog(&scene, "", 444);
                ks::SceneManager::show_dialog(&scene, "yu", 445);
                ks::SceneManager::show_dialog(&scene, "", 446);
                ks::SceneManager::show_dialog(&scene, "yu", 447);
                ks::SceneManager::show_dialog(&scene, "hi", 448);
                ks::SceneManager::show_dialog(&scene, "", 449);
                ks::SceneManager::show_dialog(&scene, "", 450);
                ks::SceneManager::show_dialog(&scene, "yu", 451);
                ks::SceneManager::show_dialog(&scene, "hi", 452);
                ks::SceneManager::show_dialog(&scene, "hi", 453);
                ks::SceneManager::show_dialog(&scene, "", 454);
                ks::SceneManager::show_dialog(&scene, "yu", 455);
                ks::SceneManager::show_dialog(&scene, "hi", 456);
                ks::SceneManager::show_dialog(&scene, "hi", 457);
                ks::SceneManager::show_dialog(&scene, "yu", 458);
                ks::SceneManager::show_dialog(&scene, "", 459);
                ks::SceneManager::show_dialog(&scene, "", 460);
                ks::SceneManager::music_stop();
                // bn::vector<ks::ConditionItem, 1> a1_tuesday_shared_library__condition_1;
                // a1_tuesday_shared_library__condition_1.push_back(ks::ConditionItem("_in_replay", &ScriptA1TuesdayEn::a1_tuesday_shared_library__condition_1_0));
                // scene.add_condition(a1_tuesday_shared_library__condition_1);
            }
            static void a1_tuesday_bizarre_and_surreal() {
                // POTENTIAL MEMLEAK!!!! better to provide it globally.
                // bn::optional<bn::regular_bg_ptr> main_bg;
                constexpr ks::SceneManager scene = ks::SceneManager("script_a1_tuesday", "en", script_a1_tuesday_en_intl);
            
                ks::SceneManager::reset();
                ks::SceneManager::set_background(bn::regular_bg_items::school_dormhallway);
                ks::SceneManager::show_dialog(&scene, "", 461);
                ks::SceneManager::show_dialog(&scene, "", 462);
                ks::SceneManager::show_dialog(&scene, "mystery", 463);
                ks::SceneManager::music_play("music_kenji.gsm");
                ks::SceneManager::show_dialog(&scene, "", 464);
                ks::SceneManager::show_dialog(&scene, "hi", 465);
                ks::SceneManager::show_dialog(&scene, "", 466);
                ks::SceneManager::show_dialog(&scene, "ke", 467);
                ks::SceneManager::show_dialog(&scene, "", 468);
                ks::SceneManager::show_dialog(&scene, "hi", 469);
                ks::SceneManager::show_dialog(&scene, "ke", 470);
                ks::SceneManager::show_dialog(&scene, "", 471);
                ks::SceneManager::show_dialog(&scene, "ke", 472);
                ks::SceneManager::show_dialog(&scene, "hi", 473);
                ks::SceneManager::show_dialog(&scene, "", 474);
                ks::SceneManager::show_dialog(&scene, "ke", 475);
                ks::SceneManager::show_dialog(&scene, "", 476);
                ks::SceneManager::show_dialog(&scene, "ke", 477);
                ks::SceneManager::show_dialog(&scene, "", 478);
                ks::SceneManager::show_dialog(&scene, "", 479);
                ks::SceneManager::show_dialog(&scene, "hi", 480);
                ks::SceneManager::show_dialog(&scene, "ke", 481);
                ks::SceneManager::show_dialog(&scene, "", 482);
                ks::SceneManager::show_dialog(&scene, "ke", 483);
                ks::SceneManager::show_dialog(&scene, "hi", 484);
                ks::SceneManager::show_dialog(&scene, "ke", 485);
                ks::SceneManager::show_dialog(&scene, "ke", 486);
                ks::SceneManager::show_dialog(&scene, "", 487);
                ks::SceneManager::show_dialog(&scene, "ke", 488);
                ks::SceneManager::show_dialog(&scene, "", 489);
                ks::SceneManager::show_dialog(&scene, "ke", 490);
                ks::SceneManager::show_dialog(&scene, "", 491);
                ks::SceneManager::show_dialog(&scene, "ke", 492);
                ks::SceneManager::show_dialog(&scene, "hi", 493);
                ks::SceneManager::show_dialog(&scene, "hi", 494);
                ks::SceneManager::show_dialog(&scene, "", 495);
                ks::SceneManager::show_dialog(&scene, "ke", 496);
                ks::SceneManager::show_dialog(&scene, "ke", 497);
                ks::SceneManager::show_dialog(&scene, "", 498);
                ks::SceneManager::show_dialog(&scene, "ke", 499);
                ks::SceneManager::show_dialog(&scene, "hi", 500);
                ks::SceneManager::show_dialog(&scene, "ke", 501);
                ks::SceneManager::show_dialog(&scene, "", 502);
                ks::SceneManager::show_dialog(&scene, "ke", 503);
                ks::SceneManager::show_dialog(&scene, "hi", 504);
                ks::SceneManager::show_dialog(&scene, "hi", 505);
                ks::SceneManager::show_dialog(&scene, "ke", 506);
                ks::SceneManager::show_dialog(&scene, "", 507);
                ScriptA1TuesdayEn::a1_tuesday_bizarre_and_surreal__menu_question_0(scene);
                ks::SceneManager::show_dialog(&scene, "ke", 508);
                ks::SceneManager::show_dialog(&scene, "ke", 509);
                ks::SceneManager::show_dialog(&scene, "", 510);
                ks::SceneManager::show_dialog(&scene, "hi", 511);
                ks::SceneManager::show_dialog(&scene, "ke", 512);
                ks::SceneManager::show_dialog(&scene, "ke", 513);
                ks::SceneManager::show_dialog(&scene, "", 514);
                ks::SceneManager::show_dialog(&scene, "ke", 515);
                ks::SceneManager::show_dialog(&scene, "ke", 516);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "ke", 517);
                ks::SceneManager::show_dialog(&scene, "", 518);
                ks::SceneManager::show_dialog(&scene, "hi", 519);
                ks::SceneManager::show_dialog(&scene, "", 520);
                ks::SceneManager::music_play("music_tension.gsm");
                ks::SceneManager::show_dialog(&scene, "ke", 521);
                ks::SceneManager::show_dialog(&scene, "ke", 522);
                ks::SceneManager::show_dialog(&scene, "ke", 523);
                ks::SceneManager::show_dialog(&scene, "ke", 524);
                ks::SceneManager::show_dialog(&scene, "ke", 525);
                ks::SceneManager::show_dialog(&scene, "ke", 526);
                ks::SceneManager::show_dialog(&scene, "ke", 527);
                ks::SceneManager::show_dialog(&scene, "", 528);
                ks::SceneManager::show_dialog(&scene, "ke", 529);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "hi", 530);
                ks::SceneManager::show_dialog(&scene, "", 531);
                ks::SceneManager::music_play("music_kenji.gsm");
                ks::SceneManager::show_dialog(&scene, "ke", 532);
                ks::SceneManager::show_dialog(&scene, "hi", 533);
                ks::SceneManager::show_dialog(&scene, "", 534);
                ks::SceneManager::show_dialog(&scene, "ke", 535);
                ks::SceneManager::show_dialog(&scene, "ke", 536);
                ks::SceneManager::show_dialog(&scene, "hi", 537);
                ks::SceneManager::show_dialog(&scene, "ke", 538);
                ks::SceneManager::show_dialog(&scene, "hi", 539);
                ks::SceneManager::show_dialog(&scene, "ke", 540);
                ks::SceneManager::show_dialog(&scene, "", 541);
                ks::SceneManager::show_dialog(&scene, "", 542);
                ks::SceneManager::show_dialog(&scene, "ke", 543);
                ks::SceneManager::show_dialog(&scene, "hi", 544);
                ks::SceneManager::show_dialog(&scene, "", 545);
                ks::SceneManager::show_dialog(&scene, "ke", 546);
                ks::SceneManager::show_dialog(&scene, "ke", 547);
                ks::SceneManager::show_dialog(&scene, "ke", 548);
                ks::SceneManager::show_dialog(&scene, "", 549);
                ks::SceneManager::show_dialog(&scene, "ke", 550);
                ks::SceneManager::show_dialog(&scene, "ke", 551);
                ks::SceneManager::show_dialog(&scene, "hi", 552);
                ks::SceneManager::show_dialog(&scene, "ke", 553);
                ks::SceneManager::show_dialog(&scene, "ke", 554);
                ks::SceneManager::show_dialog(&scene, "ke", 555);
                ks::SceneManager::show_dialog(&scene, "ke", 556);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "", 557);
                ks::SceneManager::set_background(bn::regular_bg_items::school_dormhisao_ss);
                ks::SceneManager::show_dialog(&scene, "", 558);
                ks::SceneManager::show_dialog(&scene, "", 559);
                ks::SceneManager::show_dialog(&scene, "", 560);
                ks::SceneManager::show_dialog(&scene, "", 561);
                ks::SceneManager::show_dialog(&scene, "", 562);
                ks::SceneManager::show_dialog(&scene, "hi", 563);
                ks::SceneManager::show_dialog(&scene, "", 564);
                ks::SceneManager::show_dialog(&scene, "", 565);
                ks::SceneManager::show_dialog(&scene, "", 566);
                ks::SceneManager::show_dialog(&scene, "", 567);
                ks::SceneManager::show_dialog(&scene, "", 568);
                // bn::vector<ks::ConditionItem, 1> a1_tuesday_bizarre_and_surreal__condition_0;
                // a1_tuesday_bizarre_and_surreal__condition_0.push_back(ks::ConditionItem("_in_replay", &ScriptA1TuesdayEn::a1_tuesday_bizarre_and_surreal__condition_0_0));
                // scene.add_condition(a1_tuesday_bizarre_and_surreal__condition_0);
            }
            static void a1_tuesday() {
                a1_tuesday_smalltalk();
                a1_tuesday_risk_vs_reward();
                a1_tuesday_pseudo_tea_cosy();
                a1_tuesday_shared_library();
                a1_tuesday_bizarre_and_surreal();
            }
            static void a1c3o1(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "", 569);
                ks::SceneManager::show_dialog(&scene, "", 570);
                ks::SceneManager::show_dialog(&scene, "", 571);
                ks::SceneManager::show_dialog(&scene, "", 572);
                ks::SceneManager::show_dialog(&scene, "", 573);
                ks::SceneManager::show_dialog(&scene, "", 574);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "", 575);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_cross, bn::sprite_items::misha_spr_cross_grin, ks::sprite_metas::misha_cross);
                ks::SceneManager::show_dialog(&scene, "mi", 576);
                ks::SceneManager::show_dialog(&scene, "hi", 577);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 578);
                ks::SceneManager::show_dialog(&scene, "mi", 579);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_smile, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 580);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "mi", 581);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_happy, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "mi", 582);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 583);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "mi", 25);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal2, ks::sprite_metas::shizu_basic);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "", 584);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_smile, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 585);
                ks::SceneManager::show_dialog(&scene, "", 586);
                ks::SceneManager::show_dialog(&scene, "", 587);
                ks::SceneManager::show_dialog(&scene, "", 588);
                ks::SceneManager::show_dialog(&scene, "", 589);
                ks::SceneManager::show_dialog(&scene, "", 590);
                ks::SceneManager::show_dialog(&scene, "hi", 591);
                ks::SceneManager::music_play("music_shizune.gsm");
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_frown, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 592);
                ks::SceneManager::show_dialog(&scene, "hi", 593);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 594);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 595);
                ks::SceneManager::show_dialog(&scene, "hi", 596);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_sparkle, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "", 597);
                return;
            }
            static void a1c3o2(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "", 598);
                ks::SceneManager::show_dialog(&scene, "", 599);
                ks::SceneManager::show_dialog(&scene, "", 600);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_adjust, bn::sprite_items::shizu_spr_adjust_smug, ks::sprite_metas::shizu_adjust);
                ks::SceneManager::show_dialog(&scene, "", 575);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 601);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 602);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 603);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frustrated, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "mi", 604);
                ks::SceneManager::show_dialog(&scene, "mi", 605);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_frown, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "mi", 606);
                ks::SceneManager::show_dialog(&scene, "mi", 607);
                ks::SceneManager::show_dialog(&scene, "", 608);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_normal2, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "mi", 609);
                ks::SceneManager::music_play("music_normal.gsm");
                ks::SceneManager::show_dialog(&scene, "", 610);
                ks::SceneManager::show_dialog(&scene, "hi", 611);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_dialog(&scene, "mi", 612);
                ks::SceneManager::show_dialog(&scene, "", 613);
                ks::SceneManager::show_dialog(&scene, "", 614);
                ks::SceneManager::show_dialog(&scene, "", 615);
                ks::SceneManager::show_dialog(&scene, "hi", 616);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_confused, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 617);
                ks::SceneManager::show_dialog(&scene, "hi", 618);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_sad, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 619);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_frown, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_smile, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 620);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_basic, bn::sprite_items::shizu_spr_basic_angry, ks::sprite_metas::shizu_basic);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_sign, bn::sprite_items::misha_spr_sign_smile, ks::sprite_metas::misha_sign);
                ks::SceneManager::show_dialog(&scene, "mi", 621);
                ks::SceneManager::show_dialog(&scene, "hi", 622);
                ks::SceneManager::show_character(0, bn::regular_bg_items::shizu_bg_behind, bn::sprite_items::shizu_spr_behind_blank, ks::sprite_metas::shizu_behind);
                ks::SceneManager::show_dialog(&scene, "shi", 25);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_hips, bn::sprite_items::misha_spr_hips_grin, ks::sprite_metas::misha_hips);
                ks::SceneManager::show_dialog(&scene, "mi", 623);
                ks::SceneManager::show_dialog(&scene, "hi", 624);
                ks::SceneManager::show_character(1, bn::regular_bg_items::misha_bg_perky, bn::sprite_items::misha_spr_perky_sad, ks::sprite_metas::misha_perky);
                ks::SceneManager::show_dialog(&scene, "mi", 625);
                return;
            }
            static void a1c4o1(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "hi", 626);
                ks::SceneManager::show_dialog(&scene, "", 25);
                ks::SceneManager::show_dialog(&scene, "hi", 627);
                ks::SceneManager::show_dialog(&scene, "", 25);
                // bn::vector<ks::ConditionItem, 1> a1c4o1__condition_0;
                // a1c4o1__condition_0.push_back(ks::ConditionItem("wanted_introduce or _in_replay", &ScriptA1TuesdayEn::a1c4o1__condition_0_0));
                // scene.add_condition(a1c4o1__condition_0);
                ks::SceneManager::set_background(bn::regular_bg_items::hana_library);
                ks::SceneManager::show_dialog(&scene, "", 628);
                ks::SceneManager::show_dialog(&scene, "hi", 629);
                ks::SceneManager::show_dialog(&scene, "hi", 630);
                ks::SceneManager::show_dialog(&scene, "ha_", 631);
                ks::SceneManager::show_dialog(&scene, "", 632);
                ks::SceneManager::show_dialog(&scene, "", 633);
                ks::SceneManager::show_dialog(&scene, "hi", 634);
                ks::SceneManager::set_background(bn::regular_bg_items::school_library_ss);
                ks::SceneManager::show_dialog(&scene, "", 635);
                ks::SceneManager::show_dialog(&scene, "", 636);
                ks::SceneManager::show_dialog(&scene, "hi", 637);
                ks::SceneManager::show_dialog(&scene, "ha", 638);
                ks::SceneManager::show_dialog(&scene, "ha", 639);
                ks::SceneManager::show_dialog(&scene, "", 640);
                ks::SceneManager::show_dialog(&scene, "hi", 641);
                ks::SceneManager::show_dialog(&scene, "", 642);
                ks::SceneManager::show_dialog(&scene, "", 643);
                ks::SceneManager::show_dialog(&scene, "", 644);
                ks::SceneManager::show_dialog(&scene, "", 645);
                ks::SceneManager::show_dialog(&scene, "hi", 646);
                ks::SceneManager::show_dialog(&scene, "ha", 647);
                ks::SceneManager::show_dialog(&scene, "hi", 648);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "", 25);
                ks::SceneManager::show_dialog(&scene, "", 649);
                ks::SceneManager::show_dialog(&scene, "", 650);
                ks::SceneManager::show_dialog(&scene, "hi", 651);
                return;
            }
            static void a1c4o2(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "hi", 652);
                ks::SceneManager::show_dialog(&scene, "ha_", 653);
                ks::SceneManager::show_dialog(&scene, "", 654);
                ks::SceneManager::show_dialog(&scene, "hi", 655);
                ks::SceneManager::show_dialog(&scene, "", 656);
                ks::SceneManager::set_background(bn::regular_bg_items::hana_library);
                ks::SceneManager::show_dialog(&scene, "ha_", 657);
                ks::SceneManager::show_dialog(&scene, "", 658);
                ks::SceneManager::show_dialog(&scene, "", 659);
                ks::SceneManager::show_dialog(&scene, "hi", 660);
                ks::SceneManager::show_dialog(&scene, "", 661);
                ks::SceneManager::show_dialog(&scene, "ha_", 662);
                ks::SceneManager::show_dialog(&scene, "ha_", 663);
                ks::SceneManager::show_dialog(&scene, "", 664);
                ks::SceneManager::show_dialog(&scene, "", 633);
                ks::SceneManager::show_dialog(&scene, "ha_", 665);
                ks::SceneManager::music_stop();
                ks::SceneManager::show_dialog(&scene, "", 25);
                ks::SceneManager::show_dialog(&scene, "", 666);
                ks::SceneManager::show_dialog(&scene, "", 667);
                ks::SceneManager::show_dialog(&scene, "hi", 668);
                ks::SceneManager::show_dialog(&scene, "", 669);
                ks::SceneManager::show_dialog(&scene, "", 25);
                ks::SceneManager::show_dialog(&scene, "", 670);
                ks::SceneManager::show_dialog(&scene, "", 671);
                ks::SceneManager::show_dialog(&scene, "", 672);
                ks::SceneManager::show_dialog(&scene, "", 673);
                ks::SceneManager::show_dialog(&scene, "", 674);
                ks::SceneManager::show_dialog(&scene, "", 675);
                ks::SceneManager::set_background(bn::regular_bg_items::school_library_ss);
                ks::SceneManager::show_dialog(&scene, "", 676);
                return;
            }
            static void a1c5o1(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "hi", 677);
                ks::SceneManager::show_dialog(&scene, "ke", 678);
                return;
            }
            static void a1c5o2(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "hi", 679);
                ks::SceneManager::show_dialog(&scene, "ke", 680);
                return;
            }
            static void a1_tuesday_risk_vs_reward__menu_question_0(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "mi", 681);
                // bn::vector<ks::AnswerItem, 2> answers;
                // answers.push_back(ks::AnswerItem("She has a point. Attack aggressively!", &ScriptA1TuesdayEn::a1_tuesday_risk_vs_reward__menu_question_0_she_has_a_point_attack_aggressively));
                // answers.push_back(ks::AnswerItem("It's a trap, it's smarter to play defensively here.", &ScriptA1TuesdayEn::a1_tuesday_risk_vs_reward__menu_question_0_its_a_trap_its_smarter_to_play_defensively_here));
                // scene.add_sequence(ks::MenuItem(answers);
            }
            static void a1_tuesday_risk_vs_reward__menu_question_0_she_has_a_point_attack_aggressively(const ks::SceneManager scene) {
                // scene.add_sequence(ks::AssignmentItem("attraction_sc += 1"));
                ScriptA1TuesdayEn::a1c3o1(scene);
            }
            static void a1_tuesday_risk_vs_reward__menu_question_0_its_a_trap_its_smarter_to_play_defensively_here(const ks::SceneManager scene) {
                ScriptA1TuesdayEn::a1c3o2(scene);
            }
            static void a1_tuesday_shared_library__menu_question_0(const ks::SceneManager scene) {
                // bn::vector<ks::AnswerItem, 2> answers;
                // answers.push_back(ks::AnswerItem("Hi! I'm new here. Hisao Nakai. We're in the same class.", &ScriptA1TuesdayEn::a1_tuesday_shared_library__menu_question_0_hi_im_new_here_hisao_nakai_were_in_the_same_class));
                // answers.push_back(ks::AnswerItem("I'm sorry, I didn't mean to startle you.", &ScriptA1TuesdayEn::a1_tuesday_shared_library__menu_question_0_im_sorry_i_didnt_mean_to_startle_you));
                // scene.add_sequence(ks::MenuItem(answers);
            }
            static void a1_tuesday_shared_library__menu_question_0_hi_im_new_here_hisao_nakai_were_in_the_same_class(const ks::SceneManager scene) {
                ScriptA1TuesdayEn::a1c4o1(scene);
            }
            static void a1_tuesday_shared_library__menu_question_0_im_sorry_i_didnt_mean_to_startle_you(const ks::SceneManager scene) {
                // scene.add_sequence(ks::AssignmentItem("attraction_hanako += 1"));
                ScriptA1TuesdayEn::a1c4o2(scene);
            }
            static void a1_tuesday_bizarre_and_surreal__menu_question_0(const ks::SceneManager scene) {
                // bn::vector<ks::AnswerItem, 2> answers;
                // answers.push_back(ks::AnswerItem("She was cute.", &ScriptA1TuesdayEn::a1_tuesday_bizarre_and_surreal__menu_question_0_she_was_cute));
                // answers.push_back(ks::AnswerItem("She wasn't cute.", &ScriptA1TuesdayEn::a1_tuesday_bizarre_and_surreal__menu_question_0_she_wasnt_cute));
                // scene.add_sequence(ks::MenuItem(answers);
            }
            static void a1_tuesday_bizarre_and_surreal__menu_question_0_she_was_cute(const ks::SceneManager scene) {
                // scene.add_sequence(ks::AssignmentItem("attraction_hanako += 1"));
                ScriptA1TuesdayEn::a1c5o1(scene);
            }
            static void a1_tuesday_bizarre_and_surreal__menu_question_0_she_wasnt_cute(const ks::SceneManager scene) {
                ScriptA1TuesdayEn::a1c5o2(scene);
            }
            static void a1_tuesday_smalltalk__condition_0_0(const ks::SceneManager scene) {
                return;
            }
            static void a1_tuesday_risk_vs_reward__condition_0_0(const ks::SceneManager scene) {
                return;
            }
            static void a1_tuesday_pseudo_tea_cosy__condition_0_0(const ks::SceneManager scene) {
                return;
            }
            static void a1_tuesday_shared_library__condition_0_0(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "hi", 682);
                ks::SceneManager::show_dialog(&scene, "", 683);
                ks::SceneManager::show_dialog(&scene, "yu", 684);
                ks::SceneManager::show_dialog(&scene, "hi", 685);
                ks::SceneManager::show_dialog(&scene, "yu", 686);
                ks::SceneManager::show_dialog(&scene, "hi", 687);
                ks::SceneManager::show_dialog(&scene, "yu", 688);
                ks::SceneManager::show_dialog(&scene, "", 689);
                ks::SceneManager::show_dialog(&scene, "", 690);
                ks::SceneManager::show_dialog(&scene, "", 691);
            }
            static void a1_tuesday_shared_library__condition_0_1(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "hi", 692);
                ks::SceneManager::show_dialog(&scene, "hi", 693);
                ks::SceneManager::show_dialog(&scene, "yu", 694);
                ks::SceneManager::show_dialog(&scene, "yu", 695);
                ks::SceneManager::show_dialog(&scene, "hi", 687);
                ks::SceneManager::show_dialog(&scene, "yu", 688);
                ks::SceneManager::show_dialog(&scene, "", 689);
                ks::SceneManager::show_dialog(&scene, "", 690);
            }
            static void a1_tuesday_shared_library__condition_1_0(const ks::SceneManager scene) {
                return;
            }
            static void a1_tuesday_bizarre_and_surreal__condition_0_0(const ks::SceneManager scene) {
                return;
            }
            static void a1c4o1__condition_0_0(const ks::SceneManager scene) {
                ks::SceneManager::show_dialog(&scene, "hi", 696);
                ks::SceneManager::show_dialog(&scene, "", 25);
            }
    };
}