#include "script_a4_emi.h"
#include "a4_emi_tl.h"
#include "../scenemanager.h"
#include "../character.h"
#include "smart_characters/nurse.h"
#include "smart_characters/emi.h"
#include "smart_characters/rin.h"
#include "smart_characters/meiko.h"
#include "background_metas/school_dormhisao.h"
#include "background_metas/school_track.h"
#include "background_metas/school_track_on.h"
#include "background_metas/school_track_running.h"
#include "background_metas/school_nurseoffice.h"
#include "background_metas/school_nursehall.h"
#include "background_metas/school_scienceroom.h"
#include "background_metas/school_staircase1.h"
#include "background_metas/school_roof.h"
#include "background_metas/school_gate.h"
#include "background_metas/city_street4.h"
#include "background_metas/emi_houseext.h"
#include "background_metas/emi_dining.h"
#include "background_metas/city_graveyard.h"
#include "background_metas/emi_grave.h"
#include "background_metas/emi_cry_down.h"
#include "background_metas/school_gate_ss.h"
#include "background_metas/school_dormext_full_ss.h"
#include "background_metas/school_girlsdormhall.h"
#include "background_metas/school_dormemi.h"
#include "background_metas/emi_miss_closed.h"
#include "background_metas/emi_miss_open.h"
#include "background_metas/emi_ending_smile.h"
#include "background_metas/emi_ending_serious.h"
#include "background_metas/emi_ending_glad.h"
namespace ks {
        void ScriptA4Emi::a4_emi_a_swing_and_a_miss() {
            if (ks::globals::exit_scenario) return;
            ks::SceneManager::set_label(LABEL_A4_EMI_A_SWING_AND_A_MISS);
            ks::SceneManager::set_textdb(a4_emi_tl);
            ks::SceneManager::hide_background(SCENE_TRANSITION_NONE, 0);
            ks::SceneManager::enable_fill(ks::globals::colors::BLACK);
            ks::SceneManager::update_visuals();
            ks::SceneManager::pause(120);
            ks::SceneManager::sfx_play("sfx_alarmclock.8ad", SOUND_CHANNEL_SOUND);
            ks::SceneManager::pause(180);
            ks::SceneManager::set_background(ks::background_metas::school_dormhisao, 0, 0, SCENE_TRANSITION_OPENEYE, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::music_play(MUSIC_DREAMY, 240);
            ks::SceneManager::show_dialog(0x14A10593, ks::definitions::no_char, 0);
            ks::SceneManager::show_dialog(0x90508016, ks::definitions::no_char, 1);
            ks::SceneManager::show_dialog(0x087FA29E, ks::definitions::no_char, 2);
            ks::SceneManager::show_dialog(0x510DD499, ks::definitions::no_char, 3);
            ks::SceneManager::show_dialog(0x25EB7F87, ks::definitions::no_char, 4);
            ks::SceneManager::show_dialog(0x1EA5CB76, ks::definitions::no_char, 5);
            ks::SceneManager::set_background(ks::background_metas::school_track, 0, 0, SCENE_TRANSITION_LOCATIONSKIP, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x3E3B232D, ks::definitions::no_char, 6);
            ks::SceneManager::show_dialog(0x2F1201D2, ks::definitions::no_char, 7);
            ks::SceneManager::show_dialog(0xE770B443, ks::definitions::no_char, 8);
            ks::SceneManager::set_background(ks::background_metas::school_track_on, 0, 0, SCENE_TRANSITION_LOCATIONCHANGE, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::set_background(ks::background_metas::school_track_running, 0, 0, SCENE_TRANSITION_LOCATIONCHANGE, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x14F48605, ks::definitions::no_char, 9);
            ks::SceneManager::show_dialog(0x21299653, ks::definitions::no_char, 10);
            ks::SceneManager::set_background(ks::background_metas::school_track_on, 0, 0, SCENE_TRANSITION_LOCATIONCHANGE, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::music_stop(240);
            ks::SceneManager::show_dialog(0x767A23F6, ks::definitions::no_char, 11);
            ks::SceneManager::show_dialog(0x4BC9321E, ks::definitions::no_char, 12);
            ks::SceneManager::set_background(ks::background_metas::school_nurseoffice, 0, 0, SCENE_TRANSITION_LOCATIONSKIP, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::show_character(CHARACTER_NURSE, ks::smart_characters::nurse::nurse_default_grin, PALETTE_VARIANT_DEFAULT, bn::fixed(0.5), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::music_play(MUSIC_NURSE, 30);
            ks::SceneManager::show_dialog(0x49B8093E, ks::definitions::nk, 13);
            ks::SceneManager::show_dialog(0x95544298, ks::definitions::hi, 14);
            ks::SceneManager::show_dialog(0x81C41ACE, ks::definitions::nk, 15);
            ks::SceneManager::show_dialog(0xE0722069, ks::definitions::hi, 16);
            ks::SceneManager::show_character(CHARACTER_NURSE, ks::smart_characters::nurse::nurse_default_neutral, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x2C339F85, ks::definitions::nk, 17);
            ks::SceneManager::show_dialog(0x1FB0A24E, ks::definitions::hi, 18);
            ks::SceneManager::show_character(CHARACTER_NURSE, ks::smart_characters::nurse::nurse_default_fabulous, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x61336004, ks::definitions::nk, 19);
            ks::SceneManager::show_dialog(0x34C596DB, ks::definitions::no_char, 20);
            ks::SceneManager::show_dialog(0x48FF1F52, ks::definitions::no_char, 21);
            ks::SceneManager::show_character(CHARACTER_NURSE, ks::smart_characters::nurse::nurse_default_grin, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xB4BB0AD3, ks::definitions::nk, 22);
            ks::SceneManager::show_dialog(0x9B7C211E, ks::definitions::hi, 23);
            ks::SceneManager::show_dialog(0x58ADD1CA, ks::definitions::no_char, 24);
            ks::SceneManager::show_character(CHARACTER_NURSE, ks::smart_characters::nurse::nurse_default_fabulous, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xF2A1A7AA, ks::definitions::nk, 25);
            ks::SceneManager::show_dialog(0x157C2D20, ks::definitions::hi, 26);
            ks::SceneManager::show_dialog(0xC390EF99, ks::definitions::nk, 27);
            ks::SceneManager::show_dialog(0xD8EE4C4D, ks::definitions::no_char, 28);
            ks::SceneManager::show_dialog(0x112C794C, ks::definitions::hi, 29);
            ks::SceneManager::show_dialog(0xC0B41C16, ks::definitions::no_char, 30);
            ks::SceneManager::show_character(CHARACTER_NURSE, ks::smart_characters::nurse::nurse_default_grin, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x2217E7FB, ks::definitions::nk, 31);
            ks::SceneManager::show_character(CHARACTER_NURSE, ks::smart_characters::nurse::nurse_default_neutral, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xC3DCBE68, ks::definitions::nk, 32);
            ks::SceneManager::show_dialog(0xF88CDE61, ks::definitions::nk, 33);
            ks::SceneManager::show_dialog(0x7D1E13C7, ks::definitions::no_char, 34);
            ks::SceneManager::show_dialog(0x7426B546, ks::definitions::hi, 35);
            ks::SceneManager::show_character(CHARACTER_NURSE, ks::smart_characters::nurse::nurse_default_fabulous, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xB9B01002, ks::definitions::no_char, 36);
            ks::SceneManager::show_dialog(0x11AE0506, ks::definitions::nk, 37);
            ks::SceneManager::show_character(CHARACTER_NURSE, ks::smart_characters::nurse::nurse_default_neutral, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x73B1F55C, ks::definitions::nk, 38);
            ks::SceneManager::show_dialog(0x32C4F569, ks::definitions::no_char, 39);
            ks::SceneManager::music_stop(180);
            ks::SceneManager::set_background(ks::background_metas::school_nursehall, 0, 0, SCENE_TRANSITION_LOCATIONCHANGE, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x5A3284FA, ks::definitions::no_char, 40);
            ks::SceneManager::show_dialog(0xBDD3D349, ks::definitions::no_char, 41);
            ks::SceneManager::set_background(ks::background_metas::school_scienceroom, 0, 0, SCENE_TRANSITION_SHORTTIMESKIP, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x20533413, ks::definitions::no_char, 42);
            ks::SceneManager::sfx_play("sfx_normalbell.8ad", SOUND_CHANNEL_SOUND);
            ks::SceneManager::set_background(ks::background_metas::school_staircase1, 0, 0, SCENE_TRANSITION_LOCATIONSKIP, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x96A39EE4, ks::definitions::no_char, 43);
            // renpy.music.set_volume(0.5, 0.0, channel="ambient"); TODO: unknown assignment
            ks::SceneManager::sfx_play("sfx_rooftop.8ad", SOUND_CHANNEL_AMBIENT, 60);
            ks::SceneManager::sfx_play("sfx_door_creak.8ad", SOUND_CHANNEL_SOUND);
            ks::SceneManager::set_background(ks::background_metas::school_roof, 0, 0, SCENE_TRANSITION_SILENTWHITEOUT, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_basic_hes, PALETTE_VARIANT_DEFAULT, bn::fixed(0.3), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::show_character(CHARACTER_RIN, ks::smart_characters::rin::rin_basic_absent, PALETTE_VARIANT_DEFAULT, bn::fixed(0.7), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x50CE69D9, ks::definitions::emi, 44);
            ks::SceneManager::show_dialog(0xD8565FE7, ks::definitions::no_char, 45);
            ks::SceneManager::show_dialog(0x7361F3A8, ks::definitions::hi, 46);
            ks::SceneManager::show_dialog(0xA35CCC75, ks::definitions::no_char, 47);
            ks::SceneManager::show_dialog(0xBC4847A3, ks::definitions::emi, 48);
            ks::SceneManager::show_dialog(0x3A0FD497, ks::definitions::hi, 49);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_basic_happy, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x23B60143, ks::definitions::no_char, 50);
            ks::SceneManager::show_dialog(0xCD62171E, ks::definitions::no_char, 51);
            ks::SceneManager::show_dialog(0xAA47B1CD, ks::definitions::no_char, 52);
            ks::SceneManager::show_dialog(0x923A24E6, ks::definitions::no_char, 53);
            ks::SceneManager::show_dialog(0x5A324572, ks::definitions::hi, 54);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_sad_depressed, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x54448AA4, ks::definitions::no_char, 55);
            ks::SceneManager::show_dialog(0x1856815F, ks::definitions::emi, 56);
            ks::SceneManager::show_dialog(0xF3B39BD3, ks::definitions::hi, 57);
            ks::SceneManager::hide_background(SCENE_TRANSITION_LOCATIONCHANGE, 0);
            ks::SceneManager::enable_fill(ks::globals::colors::BLACK);
            // TODO: Show bg
            ks::SceneManager::update_visuals();
            ks::SceneManager::nvl_clear();
            ks::SceneManager::nvl_show(0x02E27D8D, 58);
            ks::SceneManager::nvl_show(0x6E2029ED, 59);
            // TODO: Show bg
            ks::SceneManager::update_visuals();
            ks::SceneManager::nvl_show(0xD1BD8DF2, 60);
            ks::SceneManager::nvl_show(0x223AAEB9, 61);
            ks::SceneManager::nvl_show(0x36288573, 62);
            ks::SceneManager::nvl_show(0xC39981C7, 63);
            ks::SceneManager::sfx_stop(SOUND_CHANNEL_AMBIENT, 120);
            ks::SceneManager::nvl_clear();
            ks::SceneManager::nvl_hide();
            ks::SceneManager::hide_background(SCENE_TRANSITION_NONE, 30);
            ks::SceneManager::enable_fill(ks::globals::colors::BLACK);
            ks::SceneManager::update_visuals();
            if (ks::in_replay) {
                return;
            }
        }
        void ScriptA4Emi::a4_emi_saving_throw() {
            if (ks::globals::exit_scenario) return;
            ks::SceneManager::set_label(LABEL_A4_EMI_SAVING_THROW);
            ks::SceneManager::set_textdb(a4_emi_tl);
            ks::SceneManager::set_background(ks::background_metas::school_staircase1, 0, 0, SCENE_TRANSITION_LOCATIONCHANGE, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x814CF8C5, ks::definitions::no_char, 64);
            ks::SceneManager::sfx_play("sfx_rooftop.8ad", SOUND_CHANNEL_AMBIENT, 60);
            ks::SceneManager::set_background(ks::background_metas::school_roof, 8, 0, SCENE_TRANSITION_LOCATIONCHANGE, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::show_character(CHARACTER_RIN, ks::smart_characters::rin::rin_basic_absent, PALETTE_VARIANT_DEFAULT, bn::fixed(0.5), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x4359284A, ks::definitions::no_char, 65);
            ks::SceneManager::show_dialog(0x523F035D, ks::definitions::no_char, 66);
            ks::SceneManager::show_dialog(0xEC3CA72E, ks::definitions::hi, 67);
            ks::SceneManager::show_character(CHARACTER_RIN, ks::smart_characters::rin::rin_basic_deadpancontemplation, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x35A39084, ks::definitions::no_char, 68);
            ks::SceneManager::show_dialog(0x9486389F, ks::definitions::rin, 69);
            ks::SceneManager::show_dialog(0x6C68407A, ks::definitions::hi, 70);
            ks::SceneManager::show_character(CHARACTER_RIN, ks::smart_characters::rin::rin_basic_awayabsent, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xB93E0693, ks::definitions::rin, 71);
            ks::SceneManager::show_dialog(0x325706C0, ks::definitions::hi, 72);
            ks::SceneManager::show_character(CHARACTER_RIN, ks::smart_characters::rin::rin_basic_deadpannormal, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x461EF5AB, ks::definitions::rin, 73);
            ks::SceneManager::show_dialog(0x93921999, ks::definitions::hi, 74);
            ks::SceneManager::show_character(CHARACTER_RIN, ks::smart_characters::rin::rin_basic_deadpancontemplation, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xF01CD33C, ks::definitions::rin, 75);
            ks::SceneManager::sfx_play("sfx_door_creak.8ad", SOUND_CHANNEL_SOUND);
            ks::SceneManager::pause(30);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_basic_closedhappy, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::set_character_position(CHARACTER_EMI, bn::fixed(0.1), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::set_background_position(0, 0);
            ks::SceneManager::set_character_position(CHARACTER_RIN, bn::fixed(0.7), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::set_character_position(CHARACTER_EMI, bn::fixed(0.3), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x1B5A3F84, ks::definitions::no_char, 76);
            ks::SceneManager::show_character(CHARACTER_RIN, ks::smart_characters::rin::rin_basic_deadpan, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x8F9A83C3, ks::definitions::rin, 77);
            ks::SceneManager::hide_character(CHARACTER_RIN);
            ks::SceneManager::update_visuals();
            ks::SceneManager::pause(30);
            ks::SceneManager::set_background_position(-8, 0);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_basic_confused, PALETTE_VARIANT_DEFAULT, bn::fixed(0.5), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xE5DFA3EC, ks::definitions::no_char, 78);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_basic_shock, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x9AB0FF53, ks::definitions::no_char, 79);
            ks::SceneManager::show_dialog(0x7A9B3A76, ks::definitions::hi, 80);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_basic_confused, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x02DAC250, ks::definitions::emi, 81);
            ks::SceneManager::show_dialog(0x9125DB01, ks::definitions::hi, 82);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_sad_grin, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x2D743DBF, ks::definitions::emi, 83);
            ks::SceneManager::show_dialog(0xC040D7E8, ks::definitions::hi, 84);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_basic_closedgrin, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xBC8B6681, ks::definitions::no_char, 85);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_basic_grin, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x4F77B863, ks::definitions::emi, 86);
            ks::SceneManager::show_dialog(0x1A1BE5E4, ks::definitions::no_char, 87);
            ks::SceneManager::music_play(MUSIC_INNOCENCE, 600);
            ks::SceneManager::show_dialog(0x22E1775E, ks::definitions::hi, 88);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_basic_hes, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xA64289A2, ks::definitions::no_char, 89);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_sad_shy, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xD527BCD8, ks::definitions::emi, 90);
            ks::SceneManager::show_dialog(0x550F3E63, ks::definitions::hi, 91);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_sad_annoyed, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x6E77D570, ks::definitions::emi, 92);
            ks::SceneManager::show_dialog(0x627FA6B3, ks::definitions::hi, 93);
            ks::SceneManager::show_dialog(0x62F1A741, ks::definitions::hi, 94);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_sad_pout, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xD2C8CA45, ks::definitions::emi, 95);
            ks::SceneManager::show_dialog(0x18C8359C, ks::definitions::hi, 96);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_sad_depressed, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xCC7D78D6, ks::definitions::emi, 97);
            ks::SceneManager::show_dialog(0x9C292287, ks::definitions::no_char, 98);
            ks::SceneManager::show_dialog(0x6FA70C86, ks::definitions::hi, 99);
            ks::SceneManager::show_dialog(0xB73943FB, ks::definitions::hi, 100);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_sad_angry, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xD68105F8, ks::definitions::emi, 101);
            ks::SceneManager::show_dialog(0xF6D19D60, ks::definitions::no_char, 102);
            ks::SceneManager::show_dialog(0xE8D06FCF, ks::definitions::hi, 103);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_basic_hes, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xE4723F0A, ks::definitions::no_char, 104);
            ks::SceneManager::show_dialog(0xF6EFA8C7, ks::definitions::hi, 105);
            ks::SceneManager::show_dialog(0xFDC12C57, ks::definitions::no_char, 106);
            ks::SceneManager::show_dialog(0x1A3641C8, ks::definitions::hi, 107);
            ks::SceneManager::show_dialog(0xCDED5A73, ks::definitions::hi, 108);
            ks::SceneManager::show_dialog(0x988FC826, ks::definitions::no_char, 109);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_sad_angry, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x0E2BA927, ks::definitions::emi, 110);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_sad_grit, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xA8059154, ks::definitions::emi, 111);
            ks::SceneManager::show_dialog(0x5D9196EF, ks::definitions::no_char, 112);
            ks::SceneManager::show_dialog(0x59928AE8, ks::definitions::hi, 113);
            ks::SceneManager::show_dialog(0xF37867A5, ks::definitions::hi, 114);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_sad_depressed, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xB2EE51DE, ks::definitions::no_char, 115);
            ks::SceneManager::show_dialog(0xA7AE6AD4, ks::definitions::emi, 116);
            ks::SceneManager::show_dialog(0x59DBD50E, ks::definitions::hi, 117);
            ks::SceneManager::music_stop(240);
            ks::SceneManager::show_dialog(0x23A095AE, ks::definitions::no_char, 118);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_sad_shyblush, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xFD832219, ks::definitions::emi, 119);
            ks::SceneManager::show_dialog(0x647CDB8E, ks::definitions::no_char, 120);
            ks::SceneManager::show_dialog(0xFB46483D, ks::definitions::hi, 121);
            ks::SceneManager::music_play(MUSIC_SERENE, 30);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_excited_close_sad, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x8843FDFE, ks::definitions::no_char, 122);
            ks::SceneManager::show_dialog(0x46C371D9, ks::definitions::emi, 123);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_sad_shy, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xC275E2F8, ks::definitions::no_char, 124);
            ks::SceneManager::show_dialog(0xE8267572, ks::definitions::emi, 125);
            ks::SceneManager::show_dialog(0x48872A75, ks::definitions::hi, 126);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_sad_grin, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x273007B2, ks::definitions::no_char, 127);
            ks::SceneManager::show_dialog(0x2850BF9D, ks::definitions::emi, 128);
            ks::SceneManager::sfx_play("sfx_warningbell.8ad", SOUND_CHANNEL_SOUND);
            ks::SceneManager::show_dialog(0x86725B1B, ks::definitions::no_char, 129);
            ks::SceneManager::show_dialog(0x5915D8C7, ks::definitions::hi, 130);
            ks::SceneManager::show_dialog(0x379C919E, ks::definitions::no_char, 131);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_sad_depressed, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xD3422BDE, ks::definitions::emi, 132);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_sad_shy, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x7B62882D, ks::definitions::emi, 133);
            ks::SceneManager::show_dialog(0xB9AE3F1F, ks::definitions::no_char, 134);
            ks::SceneManager::show_dialog(0xA2094A5A, ks::definitions::hi, 135);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_excited_close_amused, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x006DA595, ks::definitions::no_char, 136);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_sad_grin, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x390714B3, ks::definitions::emi, 137);
            ks::SceneManager::show_dialog(0x7978335C, ks::definitions::hi, 138);
            ks::SceneManager::hide_character(CHARACTER_EMI);
            ks::SceneManager::update_visuals();
            // renpy.music.set_volume(1.0, 2.0, channel="ambient"); TODO: unknown assignment
            ks::SceneManager::sfx_stop(SOUND_CHANNEL_AMBIENT, 120);
            ks::SceneManager::set_background(ks::background_metas::school_staircase1, 0, 0, SCENE_TRANSITION_LOCATIONCHANGE, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x8D2DE2E1, ks::definitions::no_char, 139);
            ks::SceneManager::show_dialog(0x02FFB522, ks::definitions::no_char, 140);
            ks::SceneManager::show_dialog(0x9B78F1A6, ks::definitions::no_char, 141);
            ks::SceneManager::show_dialog(0x5F1D8FAD, ks::definitions::no_char, 142);
            ks::SceneManager::music_stop(120);
            ks::SceneManager::hide_background(SCENE_TRANSITION_NONE, 30);
            ks::SceneManager::enable_fill(ks::globals::colors::BLACK);
            ks::SceneManager::update_visuals();
            if (ks::in_replay) {
                return;
            }
        }
        void ScriptA4Emi::a4_emi_whispers_of_the_past() {
            if (ks::globals::exit_scenario) return;
            ks::SceneManager::set_label(LABEL_A4_EMI_WHISPERS_OF_THE_PAST);
            ks::SceneManager::set_textdb(a4_emi_tl);
            ks::SceneManager::hide_background(SCENE_TRANSITION_NONE, 0);
            ks::SceneManager::enable_fill(ks::globals::colors::BLACK);
            ks::SceneManager::update_visuals();
            ks::SceneManager::pause(120);
            ks::SceneManager::sfx_play("sfx_alarmclock.8ad", SOUND_CHANNEL_SOUND);
            ks::SceneManager::pause(180);
            ks::SceneManager::set_background(ks::background_metas::school_dormhisao, 0, 0, SCENE_TRANSITION_OPENEYE, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x83B8B17D, ks::definitions::no_char, 143);
            ks::SceneManager::show_dialog(0xD178B99B, ks::definitions::no_char, 144);
            ks::SceneManager::show_dialog(0x8EB7541C, ks::definitions::no_char, 145);
            ks::SceneManager::show_dialog(0xE04946CA, ks::definitions::no_char, 146);
            if (ks::progress.have_a_minute && ks::progress.talk_to_her_mom || ks::in_replay) {
                ks::SceneManager::show_dialog(0x0E545946, ks::definitions::no_char, 147);
                ks::SceneManager::show_dialog(0xC2913E63, ks::definitions::no_char, 148);
                ks::SceneManager::show_dialog(0xD86A1EB3, ks::definitions::no_char, 149);
                ks::SceneManager::show_dialog(0x61E7C9E3, ks::definitions::no_char, 150);
            }
            ks::SceneManager::set_background(ks::background_metas::school_track, 0, 0, SCENE_TRANSITION_LOCATIONSKIP, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_basic_gym_grin, PALETTE_VARIANT_DEFAULT, bn::fixed(0.5), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xCDF1A33B, ks::definitions::no_char, 151);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_excited_gym_proud, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x4BB0D0A8, ks::definitions::emi, 152);
            ks::SceneManager::show_dialog(0x3252A30F, ks::definitions::no_char, 153);
            ks::SceneManager::show_dialog(0x5DE9D7D2, ks::definitions::hi, 154);
            ks::SceneManager::music_play(MUSIC_EMI, 120);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_basic_gym_closedgrin, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x5890B0EC, ks::definitions::no_char, 155);
            ks::SceneManager::show_dialog(0x6CCA6411, ks::definitions::no_char, 156);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_basic_gym_grin, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xCF4E5102, ks::definitions::emi, 157);
            ks::SceneManager::show_dialog(0x3D0EC53E, ks::definitions::hi, 158);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_sad_gym_grin, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            if (!ks::progress.have_a_minute || !ks::progress.talk_to_her_mom && !ks::in_replay) {
                ks::SceneManager::show_dialog(0x705DD504, ks::definitions::emi, 159);
                ks::SceneManager::show_dialog(0x8C60253E, ks::definitions::hi, 160);
                ks::SceneManager::show_dialog(0xA0163074, ks::definitions::no_char, 161);
                ks::SceneManager::show_dialog(0x1D9A5A63, ks::definitions::no_char, 162);
            } else {
                ks::SceneManager::show_dialog(0xE0AB5E39, ks::definitions::emi, 163);
                ks::SceneManager::show_dialog(0x308F46A1, ks::definitions::hi, 164);
                ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_basic_gym_closedgrin, PALETTE_VARIANT_DEFAULT);
                ks::SceneManager::update_visuals();
                ks::SceneManager::show_dialog(0x51086432, ks::definitions::emi, 165);
                ks::SceneManager::show_dialog(0xA95F252C, ks::definitions::hi, 166);
                ks::SceneManager::show_dialog(0x3C25613E, ks::definitions::no_char, 167);
            }
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_basic_gym_concentrate, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::sfx_play("sfx_gymbounce.8ad", SOUND_CHANNEL_SOUND);
            ks::SceneManager::show_dialog(0xD19D6687, ks::definitions::no_char, 168);
            ks::SceneManager::set_background(ks::background_metas::school_track_running, 0, 0, SCENE_TRANSITION_SHORTTIMESKIP, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x45D61086, ks::definitions::no_char, 169);
            ks::SceneManager::set_background(ks::background_metas::school_track_on, 0, 0, SCENE_TRANSITION_NONE, 60, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_basic_gym_grin, PALETTE_VARIANT_DEFAULT, bn::fixed(0.5), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xBAFD3FC6, ks::definitions::no_char, 170);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_basic_gym_close_closedgrin, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x8B00D59D, ks::definitions::emi, 171);
            ks::SceneManager::music_stop(120);
            ks::SceneManager::set_background(ks::background_metas::school_nursehall, 0, 0, SCENE_TRANSITION_LOCATIONSKIP, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x32218335, ks::definitions::no_char, 172);
            ks::SceneManager::music_play(MUSIC_NURSE, 30);
            ks::SceneManager::show_character(CHARACTER_NURSE, ks::smart_characters::nurse::nurse_default_neutral, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::set_character_position(CHARACTER_NURSE, bn::fixed(0.2), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::set_character_position(CHARACTER_NURSE, bn::fixed(0.3), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xAA4AE342, ks::definitions::nk, 173);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_basic_gym_grin, PALETTE_VARIANT_DEFAULT, bn::fixed(0.7), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x9BDFFA3D, ks::definitions::emi, 174);
            ks::SceneManager::show_character(CHARACTER_NURSE, ks::smart_characters::nurse::nurse_default_grin, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x590E31E7, ks::definitions::nk, 175);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_basic_gym_confused, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x1A44CC92, ks::definitions::emi, 176);
            ks::SceneManager::show_character(CHARACTER_NURSE, ks::smart_characters::nurse::nurse_default_fabulous, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x8214AB59, ks::definitions::no_char, 177);
            ks::SceneManager::show_dialog(0xBA8A657A, ks::definitions::nk, 178);
            ks::SceneManager::show_character(CHARACTER_EMI, ks::smart_characters::emi::emi_sad_gym_grin, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x8FB6114C, ks::definitions::no_char, 179);
            ks::SceneManager::show_character(CHARACTER_NURSE, ks::smart_characters::nurse::nurse_default_grin, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x383D91A1, ks::definitions::nk, 180);
            ks::SceneManager::hide_character(CHARACTER_NURSE);
            ks::SceneManager::hide_character(CHARACTER_EMI);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xEC60A0DC, ks::definitions::no_char, 181);
            ks::SceneManager::show_dialog(0xAC165D0E, ks::definitions::no_char, 182);
            ks::SceneManager::set_background(ks::background_metas::school_nurseoffice, 0, 0, SCENE_TRANSITION_SHORTTIMESKIP, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xD34088A7, ks::definitions::no_char, 183);
            ks::SceneManager::show_character(CHARACTER_NURSE, ks::smart_characters::nurse::nurse_default_fabulous, PALETTE_VARIANT_DEFAULT, bn::fixed(0.5), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x116E69A6, ks::definitions::nk, 184);
            ks::SceneManager::show_dialog(0x5014CBD2, ks::definitions::hi, 185);
            ks::SceneManager::show_character(CHARACTER_NURSE, ks::smart_characters::nurse::nurse_default_neutral, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x863117DB, ks::definitions::nk, 186);
            ks::SceneManager::show_dialog(0xEBE8A61F, ks::definitions::hi, 187);
            ks::SceneManager::show_character(CHARACTER_NURSE, ks::smart_characters::nurse::nurse_default_fabulous, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x7B99814C, ks::definitions::nk, 188);
            ks::SceneManager::show_dialog(0x7117E329, ks::definitions::hi, 189);
            ks::SceneManager::show_character(CHARACTER_NURSE, ks::smart_characters::nurse::nurse_default_grin, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xD9D0700C, ks::definitions::nk, 190);
            ks::SceneManager::show_character(CHARACTER_NURSE, ks::smart_characters::nurse::nurse_default_neutral, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xC792CA0C, ks::definitions::nk, 191);
            ks::SceneManager::show_dialog(0xE71E96C6, ks::definitions::hi, 192);
            ks::SceneManager::show_character(CHARACTER_NURSE, ks::smart_characters::nurse::nurse_default_grin, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x33056D1C, ks::definitions::nk, 193);
            ks::SceneManager::show_dialog(0xDB4363B1, ks::definitions::hi, 194);
            ks::SceneManager::show_character(CHARACTER_NURSE, ks::smart_characters::nurse::nurse_default_neutral, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xDB7F2B41, ks::definitions::nk, 195);
            ks::SceneManager::show_dialog(0xB02A8936, ks::definitions::no_char, 196);
            ks::SceneManager::show_dialog(0xCA2E8298, ks::definitions::no_char, 197);
            ks::SceneManager::music_stop(60);
            ks::SceneManager::set_background(ks::background_metas::school_dormhisao, 0, 0, SCENE_TRANSITION_LOCATIONSKIP, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xC0E550FF, ks::definitions::no_char, 198);
            ks::SceneManager::set_background(ks::background_metas::school_gate, 0, 0, SCENE_TRANSITION_LOCATIONSKIP, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_grin, PALETTE_VARIANT_DEFAULT, bn::fixed(0.5), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::music_play(MUSIC_DREAMY, 120);
            ks::SceneManager::show_dialog(0xAD5D00F1, ks::definitions::no_char, 199);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_smile, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xB27CBCE4, ks::definitions::emi, 200);
            ks::SceneManager::show_dialog(0x91D9EE02, ks::definitions::hi, 201);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_up_wink, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x14231135, ks::definitions::no_char, 202);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_closedsmile, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xE8C7B32B, ks::definitions::no_char, 203);
            ks::SceneManager::show_dialog(0xC64DA9EA, ks::definitions::no_char, 204);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_awayfrown, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xBC90EED2, ks::definitions::emi, 205);
            ks::SceneManager::show_dialog(0xB8CE6B0D, ks::definitions::hi, 206);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_close_blush, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x04464041, ks::definitions::no_char, 207);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_close_frown, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xCC2DD8F9, ks::definitions::emi, 208);
            ks::SceneManager::show_dialog(0x24920F0A, ks::definitions::hi, 209);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_close_neutral, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x5F429CD4, ks::definitions::emi, 210);
            ks::SceneManager::show_dialog(0xA7466305, ks::definitions::hi, 211);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_close_awayfrown, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xD56EAEF4, ks::definitions::no_char, 212);
            ks::SceneManager::show_dialog(0xFE28BA38, ks::definitions::no_char, 213);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_close_frown, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x8A3F9D40, ks::definitions::emi, 214);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_close_awayfrown, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x6CD99BD2, ks::definitions::no_char, 215);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_close_weaksmile, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::music_stop(60);
            ks::SceneManager::show_dialog(0xD0A5161A, ks::definitions::emi, 216);
            ks::SceneManager::show_dialog(0x7C6F032C, ks::definitions::no_char, 217);
            ks::SceneManager::show_dialog(0x9AC43FE1, ks::definitions::no_char, 218);
            ks::SceneManager::show_dialog(0xB2AFC09D, ks::definitions::no_char, 219);
            ks::SceneManager::show_dialog(0xCA543255, ks::definitions::no_char, 220);
            ks::SceneManager::music_play(MUSIC_DREAMY, 300);
            ks::SceneManager::show_dialog(0xB1B3BB9A, ks::definitions::hi, 221);
            ks::SceneManager::show_dialog(0x4623843F, ks::definitions::no_char, 222);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_close_neutral, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xEC0CD0BE, ks::definitions::emi, 223);
            ks::SceneManager::show_dialog(0x5E3F814C, ks::definitions::hi, 224);
            ks::SceneManager::show_dialog(0x48E86BD8, ks::definitions::emi, 225);
            ks::SceneManager::show_dialog(0xB25B29B1, ks::definitions::hi, 226);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_close_weaksmile, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x42E07E45, ks::definitions::no_char, 227);
            ks::SceneManager::show_dialog(0x6E6DA2C6, ks::definitions::emi, 228);
            ks::SceneManager::show_dialog(0x3EF77397, ks::definitions::no_char, 229);
            ks::SceneManager::set_background(ks::background_metas::city_street4, 0, 0, SCENE_TRANSITION_SHORTTIMESKIP, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            // renpy.music.set_volume(0.2, 0.0, channel="ambient"); TODO: unknown assignment
            ks::SceneManager::sfx_play("sfx_traffic.8ad", SOUND_CHANNEL_AMBIENT, 120);
            ks::SceneManager::show_dialog(0xED45E51B, ks::definitions::no_char, 230);
            ks::SceneManager::show_dialog(0xBDF1CA4F, ks::definitions::no_char, 231);
            // renpy.music.set_volume(1.0, 8.0, channel="ambient"); TODO: unknown assignment
            ks::SceneManager::sfx_stop(SOUND_CHANNEL_AMBIENT, 60);
            ks::SceneManager::set_background(ks::background_metas::emi_houseext, 0, 0, SCENE_TRANSITION_LOCATIONSKIP, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x46DEC971, ks::definitions::no_char, 232);
            ks::SceneManager::show_character(CHARACTER_MEIKO, ks::smart_characters::meiko::meiko_basic_smile, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::set_character_position(CHARACTER_MEIKO, bn::fixed(0.8), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::set_character_position(CHARACTER_MEIKO, bn::fixed(0.7), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xAAC76698, ks::definitions::no_char, 233);
            ks::SceneManager::show_character(CHARACTER_MEIKO, ks::smart_characters::meiko::meiko_basic_happy, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xFFC52101, ks::definitions::emm, 234);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_happy, PALETTE_VARIANT_DEFAULT, bn::fixed(0.3), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xE39EFA44, ks::definitions::emi, 235);
            ks::SceneManager::show_dialog(0x81D24CC6, ks::definitions::hi, 236);
            ks::SceneManager::show_character(CHARACTER_MEIKO, ks::smart_characters::meiko::meiko_basic_serious, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x2E1FC49D, ks::definitions::emm, 237);
            ks::SceneManager::show_dialog(0xFF7AF4E1, ks::definitions::hi, 238);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_up_pout, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x8E42F099, ks::definitions::no_char, 239);
            ks::SceneManager::show_dialog(0x90071B7F, ks::definitions::no_char, 240);
            ks::SceneManager::set_background(ks::background_metas::emi_dining, 0, 0, SCENE_TRANSITION_SHORTTIMESKIP, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x3923CADB, ks::definitions::no_char, 241);
            ks::SceneManager::show_character(CHARACTER_MEIKO, ks::smart_characters::meiko::meiko_basic_happy, PALETTE_VARIANT_DEFAULT, bn::fixed(0.7), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_closedsmile, PALETTE_VARIANT_DEFAULT, bn::fixed(0.3), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x4C2F3810, ks::definitions::emm, 242);
            ks::SceneManager::show_dialog(0x30FB4C83, ks::definitions::hi, 243);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_grin, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x8996A876, ks::definitions::emi, 244);
            ks::SceneManager::show_character(CHARACTER_MEIKO, ks::smart_characters::meiko::meiko_basic_smile, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x78C51D8D, ks::definitions::emm, 245);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_up_wink, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x92382A74, ks::definitions::emi, 246);
            ks::SceneManager::show_character(CHARACTER_MEIKO, ks::smart_characters::meiko::meiko_basic_wink, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x57F21C06, ks::definitions::emm, 247);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_up_grin, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x3646A05B, ks::definitions::no_char, 248);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_grin, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::show_character(CHARACTER_MEIKO, ks::smart_characters::meiko::meiko_basic_smile, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::set_background_transition(SCENE_TRANSITION_SHORTTIMESKIP);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x8B0EDACC, ks::definitions::no_char, 249);
            ks::SceneManager::show_character(CHARACTER_MEIKO, ks::smart_characters::meiko::meiko_basic_happy, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xB1A79020, ks::definitions::emm, 250);
            ks::SceneManager::show_dialog(0x520B94D1, ks::definitions::hi, 251);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_closedsmile, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x2EEDBF41, ks::definitions::emi, 252);
            ks::SceneManager::show_dialog(0x2015D371, ks::definitions::no_char, 253);
            ks::SceneManager::show_dialog(0x081C9F48, ks::definitions::hi, 254);
            ks::SceneManager::hide_character(CHARACTER_MEIKO);
            ks::SceneManager::update_visuals();
            ks::SceneManager::set_background_position(-8, 0);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_awayfrown, PALETTE_VARIANT_DEFAULT, bn::fixed(0.5), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xFDAFA1B2, ks::definitions::no_char, 255);
            ks::SceneManager::show_dialog(0x1F892149, ks::definitions::hi, 256);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_weaksmile, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x67EFE670, ks::definitions::no_char, 257);
            ks::SceneManager::show_dialog(0x76EA63AA, ks::definitions::no_char, 258);
            ks::SceneManager::show_dialog(0x31DE75F7, ks::definitions::no_char, 259);
            ks::SceneManager::show_dialog(0x3F7BA0B6, ks::definitions::no_char, 260);
            ks::SceneManager::set_background_position(0, 0);
            ks::SceneManager::set_character_position(CHARACTER_EMICAS, bn::fixed(0.3), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_character(CHARACTER_MEIKO, ks::smart_characters::meiko::meiko_basic_happy, PALETTE_VARIANT_DEFAULT, bn::fixed(0.7), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xE58AF29E, ks::definitions::emm, 261);
            ks::SceneManager::show_dialog(0xBC898B38, ks::definitions::no_char, 262);
            ks::SceneManager::music_stop(240);
            ks::SceneManager::set_background(ks::background_metas::city_graveyard, 0, 0, SCENE_TRANSITION_SHORTTIMESKIP, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x6A18242C, ks::definitions::no_char, 263);
            ks::SceneManager::show_dialog(0xC844D88C, ks::definitions::no_char, 264);
            ks::SceneManager::show_dialog(0x7D34CC9F, ks::definitions::no_char, 265);
            ks::SceneManager::show_dialog(0xA665B5C3, ks::definitions::no_char, 266);
            ks::SceneManager::show_dialog(0xF281EB48, ks::definitions::no_char, 267);
            ks::SceneManager::show_dialog(0xA753E5C7, ks::definitions::no_char, 268);
            ks::SceneManager::show_dialog(0x290EB79C, ks::definitions::no_char, 269);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_weaksmile, PALETTE_VARIANT_DEFAULT, bn::fixed(0.5), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xEA48601C, ks::definitions::emi, 270);
            ks::SceneManager::set_background(ks::background_metas::emi_grave, 0, 0, SCENE_TRANSITION_WHITEOUT, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            // renpy.music.set_volume(0.4, 0.0, channel="music"); TODO: unknown assignment
            ks::SceneManager::music_play(MUSIC_FRIENDSHIP, 60);
            ks::SceneManager::show_dialog(0xAA2053E6, ks::definitions::no_char, 271);
            ks::SceneManager::show_dialog(0x90B95FB9, ks::definitions::no_char, 272);
            ks::SceneManager::set_background(ks::background_metas::city_graveyard, 0, 0, SCENE_TRANSITION_LOCATIONCHANGE, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_neutral, PALETTE_VARIANT_DEFAULT, bn::fixed(0.5), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            // renpy.music.set_volume(1.0, 20.0, channel="music"); TODO: unknown assignment
            ks::SceneManager::show_dialog(0xBAF20AD1, ks::definitions::no_char, 273);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_awayfrown, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xE7515A19, ks::definitions::emi, 274);
            ks::SceneManager::show_dialog(0x00AD0833, ks::definitions::hi, 275);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_frown, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x03A8D4B1, ks::definitions::emi, 276);
            ks::SceneManager::show_dialog(0xAA3BC928, ks::definitions::hi, 277);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_neutral, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xC15BE98B, ks::definitions::emi, 278);
            ks::SceneManager::show_dialog(0x0FF3718C, ks::definitions::emi, 279);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_up_weaksmile, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x565058A7, ks::definitions::emi, 280);
            ks::SceneManager::show_dialog(0x7B1DD52C, ks::definitions::hi, 281);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_closedsmile, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xA6B59422, ks::definitions::emi, 282);
            ks::SceneManager::show_dialog(0x204A6D4B, ks::definitions::no_char, 283);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_neutral, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xAF2C45C0, ks::definitions::emi, 284);
            ks::SceneManager::show_dialog(0xB386B82F, ks::definitions::hi, 285);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_frown, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xE5BDEBC5, ks::definitions::emi, 286);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_awayfrown, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xD985AE03, ks::definitions::emi, 287);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_frown, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x06A06D18, ks::definitions::emi, 288);
            ks::SceneManager::show_dialog(0xEAA1B180, ks::definitions::emi, 289);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_neutral, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x7EB84057, ks::definitions::emi, 290);
            ks::SceneManager::show_dialog(0x8CDA591D, ks::definitions::no_char, 291);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_weaksmile, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x3F7B65A5, ks::definitions::emi, 292);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_neutral, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x05194E18, ks::definitions::emi, 293);
            ks::SceneManager::show_dialog(0x85209FDB, ks::definitions::emi, 294);
            ks::SceneManager::show_dialog(0x48BDD9C8, ks::definitions::emi, 295);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_awayfrown, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x04DD2384, ks::definitions::emi, 296);
            ks::SceneManager::show_dialog(0xF8CE321B, ks::definitions::no_char, 297);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_sad, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xD2C8685E, ks::definitions::emi, 298);
            ks::SceneManager::show_dialog(0xC4FFEB0E, ks::definitions::emi, 299);
            ks::SceneManager::show_dialog(0x0F5F12F0, ks::definitions::hi, 300);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_neutral, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x0830BCB4, ks::definitions::emi, 301);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_frown, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x1607ACAB, ks::definitions::emi, 302);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_sad, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xECF908CE, ks::definitions::emi, 303);
            ks::SceneManager::show_dialog(0xAA37EB70, ks::definitions::emi, 304);
            ks::SceneManager::show_dialog(0x6D3DB78A, ks::definitions::emi, 305);
            ks::SceneManager::show_dialog(0xBB9F6066, ks::definitions::no_char, 306);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_up_close_sad, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xF22FE368, ks::definitions::no_char, 307);
            ks::SceneManager::show_dialog(0xBDD99E49, ks::definitions::emi, 308);
            ks::SceneManager::show_dialog(0x206EC73B, ks::definitions::no_char, 309);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_close_sad, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x514072BA, ks::definitions::emi, 310);
            ks::SceneManager::hide_background(SCENE_TRANSITION_WHITEOUT, 0);
            ks::SceneManager::enable_fill(ks::globals::colors::BLACK);
            ks::SceneManager::set_background(ks::background_metas::emi_cry_down, 0, 0, SCENE_TRANSITION_NONE, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xD0E615A5, ks::definitions::no_char, 311);
            ks::SceneManager::show_dialog(0xA1B7753E, ks::definitions::emi, 312);
            ks::SceneManager::show_dialog(0x2146F9C7, ks::definitions::hi, 313);
            ks::SceneManager::show_dialog(0x13D97CF7, ks::definitions::no_char, 314);
            ks::SceneManager::show_dialog(0x517B58B9, ks::definitions::no_char, 315);
            ks::SceneManager::show_dialog(0x5465725D, ks::definitions::hi, 316);
            ks::SceneManager::set_background(ks::background_metas::city_graveyard, 0, 0, SCENE_TRANSITION_LOCATIONCHANGE, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_close_weaksmile, PALETTE_VARIANT_DEFAULT, bn::fixed(0.5), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x3EE0ED04, ks::definitions::no_char, 317);
            ks::SceneManager::show_dialog(0x57265DD5, ks::definitions::emi, 318);
            ks::SceneManager::show_dialog(0xBF9B558F, ks::definitions::hi, 319);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_close_closedsmile, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xCABAAF78, ks::definitions::emi, 320);
            ks::SceneManager::show_dialog(0xEAB476A1, ks::definitions::hi, 321);
            ks::SceneManager::show_dialog(0x31C97916, ks::definitions::no_char, 322);
            ks::SceneManager::music_stop(900);
            if (ks::in_replay) {
                return;
            }
        }
        void ScriptA4Emi::a4_emi_hooray_for_socks() {
            if (ks::globals::exit_scenario) return;
            ks::SceneManager::set_label(LABEL_A4_EMI_HOORAY_FOR_SOCKS);
            ks::SceneManager::set_textdb(a4_emi_tl);
            ks::SceneManager::set_background(ks::background_metas::school_gate_ss, 0, 0, SCENE_TRANSITION_SHORTTIMESKIP, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xAA06D4C4, ks::definitions::no_char, 323);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_close_neutral, PALETTE_VARIANT_SPRITE_SUNSET, bn::fixed(0.5), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xDCE178BD, ks::definitions::no_char, 324);
            ks::SceneManager::show_dialog(0xDACF0A0E, ks::definitions::hi, 325);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_close_awayfrown, PALETTE_VARIANT_SPRITE_SUNSET);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x29F08244, ks::definitions::no_char, 326);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_close_frown, PALETTE_VARIANT_SPRITE_SUNSET);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xFB668008, ks::definitions::emi, 327);
            ks::SceneManager::set_background(ks::background_metas::school_dormext_full_ss, 0, 0, SCENE_TRANSITION_LOCATIONSKIP, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x8A7B092D, ks::definitions::no_char, 328);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_close_weaksmile, PALETTE_VARIANT_SPRITE_SUNSET, bn::fixed(0.5), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x301ED532, ks::definitions::emi, 329);
            ks::SceneManager::show_dialog(0xC3B275F9, ks::definitions::hi, 330);
            ks::SceneManager::set_background(ks::background_metas::school_girlsdormhall, 0, 0, SCENE_TRANSITION_LOCATIONSKIP, 0, PALETTE_VARIANT_SUNSET);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x15D51760, ks::definitions::no_char, 331);
            ks::SceneManager::show_dialog(0xC1C1F14B, ks::definitions::no_char, 332);
            ks::SceneManager::show_dialog(0x95BDA868, ks::definitions::no_char, 333);
            ks::SceneManager::show_dialog(0x1FD8AAF3, ks::definitions::no_char, 334);
            ks::SceneManager::show_dialog(0x818D2E4C, ks::definitions::no_char, 335);
            ks::SceneManager::sfx_play("sfx_dooropen.8ad", SOUND_CHANNEL_SOUND);
            ks::SceneManager::show_dialog(0xF2D23F27, ks::definitions::no_char, 336);
            ks::SceneManager::set_background(ks::background_metas::school_dormemi, 8, 0, SCENE_TRANSITION_LOCATIONSKIP, 0, PALETTE_VARIANT_SUNSET);
            ks::SceneManager::update_visuals();
            ks::SceneManager::sfx_play("sfx_doorclose.8ad", SOUND_CHANNEL_SOUND);
            ks::SceneManager::show_dialog(0xC587A4CA, ks::definitions::no_char, 337);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_close_weaksmile, PALETTE_VARIANT_SPRITE_SUNSET, bn::fixed(0.5), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xA0EC08AA, ks::definitions::emi, 338);
            ks::SceneManager::show_dialog(0xAE2309EB, ks::definitions::hi, 339);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_close_closedsmile, PALETTE_VARIANT_SPRITE_SUNSET);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x7767EB07, ks::definitions::no_char, 340);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_close_smile, PALETTE_VARIANT_SPRITE_SUNSET);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x49959522, ks::definitions::emi, 341);
            ks::SceneManager::show_dialog(0xFDF32D1B, ks::definitions::no_char, 342);
            ks::SceneManager::show_dialog(0xC4842553, ks::definitions::no_char, 343);
            ks::SceneManager::show_dialog(0xA5E9F908, ks::definitions::no_char, 344);
            ks::SceneManager::show_dialog(0x9CC7A3E9, ks::definitions::no_char, 345);
            ks::SceneManager::show_dialog(0xC6BDBCBE, ks::definitions::no_char, 346);
            ks::SceneManager::show_dialog(0x5D4C85D9, ks::definitions::no_char, 347);
            ks::SceneManager::show_dialog(0x4D87714C, ks::definitions::no_char, 348);
            ks::SceneManager::show_dialog(0x1D1B4D9A, ks::definitions::hi, 349);
            ks::SceneManager::music_play(MUSIC_COMFORT, 240);
            ks::SceneManager::set_background_position(-8, 0);
            ks::SceneManager::show_character(CHARACTER_EMICAS, ks::smart_characters::emi::emicas_basic_close_closedsmile, PALETTE_VARIANT_SPRITE_SUNSET, bn::fixed(0.5), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xD9123401, ks::definitions::no_char, 350);
            ks::SceneManager::hide_character(CHARACTER_EMICAS);
            ks::SceneManager::show_character(CHARACTER_EMINUDE, ks::smart_characters::emi::eminude_basic_close_smile, PALETTE_VARIANT_SPRITE_SUNSET, bn::fixed(0.5), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x4D0A2B85, ks::definitions::no_char, 351);
            ks::SceneManager::show_dialog(0x68761DA1, ks::definitions::no_char, 352);
            ks::SceneManager::hide_character(CHARACTER_EMINUDE);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xDFCC05F7, ks::definitions::no_char, 353);
            ks::SceneManager::show_dialog(0xE5481868, ks::definitions::no_char, 354);
            ks::SceneManager::show_dialog(0xEFE001B6, ks::definitions::no_char, 355);
            ks::SceneManager::show_dialog(0xC1C9FD74, ks::definitions::no_char, 356);
            ks::SceneManager::show_dialog(0xC03C4A93, ks::definitions::no_char, 357);
            ks::SceneManager::show_dialog(0x1B9EA2B1, ks::definitions::no_char, 358);
            ks::SceneManager::show_character(CHARACTER_EMINUDE, ks::smart_characters::emi::eminude_basic_close_evil, PALETTE_VARIANT_SPRITE_SUNSET, bn::fixed(0.5), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xEFAB62D8, ks::definitions::emi, 359);
            ks::SceneManager::show_dialog(0x0ACCB84C, ks::definitions::no_char, 360);
            ks::SceneManager::show_dialog(0xB6F511CC, ks::definitions::hi, 361);
            ks::SceneManager::show_character(CHARACTER_EMINUDE, ks::smart_characters::emi::eminude_basic_close_frown, PALETTE_VARIANT_SPRITE_SUNSET);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xD5C80036, ks::definitions::emi, 362);
            ks::SceneManager::show_dialog(0xFD765596, ks::definitions::hi, 363);
            ks::SceneManager::show_character(CHARACTER_EMINUDE, ks::smart_characters::emi::eminude_basic_close_closedsmile, PALETTE_VARIANT_SPRITE_SUNSET);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xCC664F7F, ks::definitions::emi, 364);
            ks::SceneManager::show_dialog(0x0C8F4B95, ks::definitions::no_char, 365);
            ks::SceneManager::show_dialog(0x52FA9FF9, ks::definitions::no_char, 366);
            ks::SceneManager::set_background(ks::background_metas::emi_miss_closed, 0, 0, SCENE_TRANSITION_WHITEOUT, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x49D0FF83, ks::definitions::no_char, 367);
            ks::SceneManager::show_dialog(0xF0C3AF10, ks::definitions::no_char, 368);
            ks::SceneManager::show_dialog(0x7B476B95, ks::definitions::no_char, 369);
            ks::SceneManager::set_background(ks::background_metas::emi_miss_open, 0, 0, SCENE_TRANSITION_NONE, 30, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x190B3DCC, ks::definitions::no_char, 370);
            ks::SceneManager::show_dialog(0x745E59E3, ks::definitions::no_char, 371);
            ks::SceneManager::show_dialog(0x26F75925, ks::definitions::no_char, 372);
            ks::SceneManager::show_dialog(0x96CBDFEC, ks::definitions::no_char, 373);
            ks::SceneManager::set_background(ks::background_metas::school_dormemi, -8, 0, SCENE_TRANSITION_SHORTTIMESKIP, 0, PALETTE_VARIANT_SUNSET);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x1E1EF9B6, ks::definitions::no_char, 374);
            ks::SceneManager::show_dialog(0xA2056CE6, ks::definitions::no_char, 375);
            ks::SceneManager::show_dialog(0x4D5D61D9, ks::definitions::no_char, 376);
            ks::SceneManager::show_dialog(0xAC825D5F, ks::definitions::no_char, 377);
            ks::SceneManager::show_dialog(0x674ECF9F, ks::definitions::no_char, 378);
            ks::SceneManager::show_character(CHARACTER_EMINUDE, ks::smart_characters::emi::eminude_basic_close_smile, PALETTE_VARIANT_SPRITE_SUNSET, bn::fixed(0.5), bn::fixed(0.5), bn::fixed(1), bn::fixed(1));
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xD7172BFE, ks::definitions::emi, 379);
            ks::SceneManager::show_dialog(0x3AD032A4, ks::definitions::hi, 380);
            ks::SceneManager::show_character(CHARACTER_EMINUDE, ks::smart_characters::emi::eminude_basic_close_closedsmile, PALETTE_VARIANT_SPRITE_SUNSET);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x8658749F, ks::definitions::emi, 381);
            ks::SceneManager::show_dialog(0x0DD8286D, ks::definitions::no_char, 382);
            ks::SceneManager::show_character(CHARACTER_EMINUDE, ks::smart_characters::emi::eminude_basic_close_blush, PALETTE_VARIANT_SPRITE_SUNSET);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xE533F8A1, ks::definitions::hi, 383);
            ks::SceneManager::show_character(CHARACTER_EMINUDE, ks::smart_characters::emi::eminude_basic_close_closedsmile, PALETTE_VARIANT_SPRITE_SUNSET);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xCAE447EA, ks::definitions::no_char, 384);
            ks::SceneManager::show_dialog(0x82CB6698, ks::definitions::no_char, 385);
            ks::SceneManager::show_dialog(0x1DFFB76E, ks::definitions::emi, 386);
            ks::SceneManager::show_dialog(0x72933689, ks::definitions::no_char, 387);
            ks::SceneManager::show_dialog(0xBF234844, ks::definitions::no_char, 388);
            ks::SceneManager::music_stop(120);
            ks::SceneManager::hide_background(SCENE_TRANSITION_NONE, 30);
            ks::SceneManager::enable_fill(ks::globals::colors::BLACK);
            ks::SceneManager::update_visuals();
            if (ks::in_replay) {
                return;
            }
        }
        void ScriptA4Emi::a4_emi_clean_teeth() {
            if (ks::globals::exit_scenario) return;
            ks::SceneManager::set_label(LABEL_A4_EMI_CLEAN_TEETH);
            ks::SceneManager::set_textdb(a4_emi_tl);
            ks::SceneManager::hide_background(SCENE_TRANSITION_NONE, 30);
            ks::SceneManager::enable_fill(ks::globals::colors::BLACK);
            ks::SceneManager::update_visuals();
            ks::SceneManager::set_background(ks::background_metas::school_dormemi, 0, 0, SCENE_TRANSITION_OPENEYE, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xDB751F5E, ks::definitions::no_char, 389);
            ks::SceneManager::show_dialog(0x5A939417, ks::definitions::no_char, 390);
            ks::SceneManager::show_dialog(0x50A0E07B, ks::definitions::no_char, 391);
            ks::SceneManager::music_play(MUSIC_TWINKLE, 60);
            ks::SceneManager::show_dialog(0x090D3707, ks::definitions::no_char, 392);
            ks::SceneManager::show_dialog(0x69B4D16A, ks::definitions::no_char, 393);
            ks::SceneManager::show_dialog(0x91950013, ks::definitions::no_char, 394);
            ks::SceneManager::show_dialog(0x2E3FAB7E, ks::definitions::no_char, 395);
            ks::SceneManager::show_dialog(0x15390B9C, ks::definitions::no_char, 396);
            ks::SceneManager::show_dialog(0xBF131295, ks::definitions::no_char, 397);
            ks::SceneManager::show_dialog(0x2EBBE724, ks::definitions::no_char, 398);
            ks::SceneManager::show_dialog(0xDFB9C608, ks::definitions::no_char, 399);
            ks::SceneManager::show_dialog(0x92C5E6B3, ks::definitions::no_char, 400);
            ks::SceneManager::show_dialog(0x74DBF7EF, ks::definitions::no_char, 401);
            ks::SceneManager::show_dialog(0xE9F70A98, ks::definitions::no_char, 402);
            ks::SceneManager::show_dialog(0x009AF196, ks::definitions::no_char, 403);
            ks::SceneManager::show_dialog(0x54814DF8, ks::definitions::no_char, 404);
            ks::SceneManager::show_dialog(0xE2EB4E2D, ks::definitions::no_char, 405);
            ks::SceneManager::show_dialog(0x30F83828, ks::definitions::no_char, 406);
            ks::SceneManager::set_background(ks::background_metas::emi_ending_smile, 0, 0, SCENE_TRANSITION_WHITEOUT, 0, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x29EF96FA, ks::definitions::no_char, 407);
            ks::SceneManager::show_dialog(0x38AF871E, ks::definitions::emi, 408);
            ks::SceneManager::show_dialog(0xF1BFB0CA, ks::definitions::hi, 409);
            ks::SceneManager::show_dialog(0xBDECC821, ks::definitions::emi, 410);
            ks::SceneManager::show_dialog(0xF51923B9, ks::definitions::no_char, 411);
            ks::SceneManager::show_dialog(0xB6EA24BD, ks::definitions::hi, 412);
            ks::SceneManager::show_dialog(0xD53053CD, ks::definitions::emi, 413);
            ks::SceneManager::show_dialog(0xB5D291A8, ks::definitions::hi, 414);
            ks::SceneManager::show_dialog(0x09EB46A2, ks::definitions::no_char, 415);
            ks::SceneManager::show_dialog(0x4AA2FDA0, ks::definitions::no_char, 416);
            ks::SceneManager::show_dialog(0x95151825, ks::definitions::no_char, 417);
            ks::SceneManager::show_dialog(0xC44B4EDB, ks::definitions::emi, 418);
            ks::SceneManager::show_dialog(0x3AD032A4, ks::definitions::hi, 419);
            ks::SceneManager::show_dialog(0xB8CCE40F, ks::definitions::emi, 420);
            ks::SceneManager::show_dialog(0x3E98722E, ks::definitions::hi, 421);
            ks::SceneManager::set_background(ks::background_metas::emi_ending_serious, 0, 0, SCENE_TRANSITION_NONE, 30, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xB976557A, ks::definitions::no_char, 422);
            ks::SceneManager::show_dialog(0x25012C20, ks::definitions::emi, 423);
            ks::SceneManager::show_dialog(0xCFF553C8, ks::definitions::emi, 424);
            ks::SceneManager::show_dialog(0xB10E3333, ks::definitions::emi, 425);
            ks::SceneManager::set_background(ks::background_metas::emi_ending_smile, 0, 0, SCENE_TRANSITION_NONE, 30, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0x319FAB30, ks::definitions::no_char, 426);
            ks::SceneManager::show_dialog(0x1E0C4C29, ks::definitions::no_char, 427);
            ks::SceneManager::show_dialog(0x29F1EFD6, ks::definitions::hi, 428);
            ks::SceneManager::show_dialog(0xCE8C098F, ks::definitions::no_char, 429);
            ks::SceneManager::show_dialog(0xA00D7800, ks::definitions::hi, 430);
            ks::SceneManager::show_dialog(0x1983FA91, ks::definitions::emi, 431);
            ks::SceneManager::show_dialog(0x198CB1F0, ks::definitions::no_char, 432);
            ks::SceneManager::show_dialog(0x5D38D696, ks::definitions::no_char, 433);
            ks::SceneManager::show_dialog(0x0DD60746, ks::definitions::emi, 434);
            ks::SceneManager::show_dialog(0x9152328D, ks::definitions::hi, 435);
            ks::SceneManager::set_background(ks::background_metas::emi_ending_glad, 0, 0, SCENE_TRANSITION_NONE, 30, PALETTE_VARIANT_DEFAULT);
            ks::SceneManager::update_visuals();
            ks::SceneManager::show_dialog(0xEB67D7E8, ks::definitions::emi, 436);
            // ach("emigood_achieve"); TODO: unknown assignment
            ks::SceneManager::music_stop(180);
            if (ks::in_replay) {
                return;
            }
        }
        void ScriptA4Emi::a4_emi() {
            if (ks::globals::exit_scenario) return;
            SKIP_IF_LOAD_ANOTHER_SCENE(SCRIPT_A4_EMI);
            ks::SceneManager::set_script(SCRIPT_A4_EMI);
            ks::SceneManager::init_savedata(ks::progress);
            ks::SceneManager::set(ks::SceneManager("script_a4_emi"));
        
            if (ks::progress.have_a_minute && ks::progress.talk_to_her_mom) {
                ScriptA4Emi::a4_emi_a_swing_and_a_miss(); // INLINE CALL
                ks::SceneManager::timeskip();
                ScriptA4Emi::a4_emi_saving_throw(); // INLINE CALL
                ks::SceneManager::timeskip();
            }
            ScriptA4Emi::a4_emi_whispers_of_the_past(); // INLINE CALL
            ScriptA4Emi::a4_emi_hooray_for_socks(); // INLINE CALL
            ks::SceneManager::timeskip();
            ScriptA4Emi::a4_emi_clean_teeth(); // INLINE CALL
        }
}