#include "fonts/fonts_latin.h"
#include "bn_sprite_items_font_small_latin.h"

constexpr int8_t font_small_latin_character_widths[] = {
    3,    //  
    3,    // !
    4,    // "
    6,    // #
    6,    // $
    8,    // %
    8,    // &
    2,    // '
    4,    // (
    4,    // )
    4,    // *
    6,    // +
    3,    // ,
    4,    // -
    3,    // .
    5,    // /
    6,    // 0
    3,    // 1
    6,    // 2
    6,    // 3
    6,    // 4
    6,    // 5
    6,    // 6
    6,    // 7
    6,    // 8
    6,    // 9
    3,    // :
    3,    // ;
    6,    // <
    6,    // =
    6,    // >
    5,    // ?
    8,    // @
    6,    // A
    7,    // B
    7,    // C
    7,    // D
    6,    // E
    5,    // F
    8,    // G
    7,    // H
    3,    // I
    5,    // J
    6,    // K
    5,    // L
    9,    // M
    7,    // N
    8,    // O
    6,    // P
    8,    // Q
    6,    // R
    6,    // S
    5,    // T
    6,    // U
    6,    // V
    9,    // W
    7,    // X
    6,    // Y
    7,    // Z
    4,    // [
    5,    // Backslash
    4,    // ]
    6,    // ^
    4,    // _
    3,    // `
    5,    // a
    5,    // b
    5,    // c
    5,    // d
    5,    // e
    4,    // f
    5,    // g
    5,    // h
    2,    // i
    4,    // j
    5,    // k
    2,    // l
    7,    // m
    5,    // n
    5,    // o
    5,    // p
    5,    // q
    4,    // r
    5,    // s
    4,    // t
    5,    // u
    5,    // v
    6,    // w
    5,    // x
    5,    // y
    4,    // z
    4,    // {
    4,    // |
    4,    // }
    5,    // ~
    3,    // ¡
    5,    // ¿
    6,    // É
    6,    // Ú
    5,    // à
    5,    // á
    5,    // é
    5,    // ê
    2,    // í
    5,    // ñ
    5,    // ó
    5,    // ú
    5,    // ü
    6,    // ō
    8,    // —
    4,    // “
    4,    // ”
    8,    // …
};

constexpr bn::sprite_font font_small_latin_sprite_font(
    bn::sprite_items::font_small_latin,
    latin_utf8_characters_map.reference(),
    font_small_latin_character_widths);

