#ifndef DEFINITIONS_H
#define DEFINITIONS_H

typedef unsigned char gameState_t;
#define GS_INIT ((gameState_t)0)
#define GS_MENU_MAIN ((gameState_t)1)
#define GS_MENU_SAVES ((gameState_t)2)
#define GS_MENU_EXTRAS ((gameState_t)3)
#define GS_MENU_OPTIONS ((gameState_t)4)
#define GS_MENU_EXTRAS_CINEMA ((gameState_t)5)
#define GS_START_GAME ((gameState_t)6)
#define GS_LOAD_GAME ((gameState_t)7)
#define GS_GAME ((gameState_t)8)
#define GS_GAME_MENU ((gameState_t)9)
#define GS_GAME_MENU_SAVES ((gameState_t)10)
#define GS_RESET ((gameState_t)100)

typedef unsigned char forceRoute_t;
#define FR_NONE   ((forceRoute_t)0)
#define FR_EMI    ((forceRoute_t)1)
#define FR_HANAKO ((forceRoute_t)2)
#define FR_LILLY  ((forceRoute_t)3)
#define FR_RIN    ((forceRoute_t)4)
#define FR_SHIZU  ((forceRoute_t)5)
#define FR_KENJI  ((forceRoute_t)6)

typedef unsigned char language_t;
#define LANG_ENGLISH ((language_t)0)
#define LANG_RUSSIAN ((language_t)1)

typedef unsigned char sound_channel_t;
#define SOUND_CHANNEL_MUSIC ((sound_channel_t)0)
#define SOUND_CHANNEL_SOUND ((sound_channel_t)1)
#define SOUND_CHANNEL_AMBIENT ((sound_channel_t)2)
#define SOUND_CHANNEL_VIDEO ((sound_channel_t)0)

typedef unsigned char music_t;
#define MUSIC_NONE ((music_t)0)
#define MUSIC_TRANQUIL ((music_t)1)
#define MUSIC_NURSE ((music_t)2)
#define MUSIC_SOOTHING ((music_t)3)
#define MUSIC_TWINKLE ((music_t)4)
#define MUSIC_MOONLIGHT ((music_t)5)
#define MUSIC_RAIN ((music_t)6)
#define MUSIC_TRAGIC ((music_t)7)
#define MUSIC_COMFORT ((music_t)8)
#define MUSIC_LILLY ((music_t)9)
#define MUSIC_DAILY ((music_t)10)
#define MUSIC_EASE ((music_t)11)
#define MUSIC_ANOTHER ((music_t)12)
#define MUSIC_FRIENDSHIP ((music_t)13)
#define MUSIC_HAPPINESS ((music_t)14)
#define MUSIC_COMEDY ((music_t)15)
#define MUSIC_TENSION ((music_t)16)
#define MUSIC_RUNNING ((music_t)17)
#define MUSIC_INNOCENCE ((music_t)18)
#define MUSIC_HEART ((music_t)19)
#define MUSIC_SERENE ((music_t)20)
#define MUSIC_DRAMA ((music_t)21)
#define MUSIC_NIGHT ((music_t)22)
#define MUSIC_KENJI ((music_t)23)
#define MUSIC_HANAKO ((music_t)24)
#define MUSIC_RIN ((music_t)25)
#define MUSIC_TIMESKIP ((music_t)26)
#define MUSIC_DREAMY ((music_t)27)
#define MUSIC_JAZZ ((music_t)28)
#define MUSIC_ROMANCE ((music_t)29)
#define MUSIC_CREDITS ((music_t)30)
#define MUSIC_MUSICBOX ((music_t)31)
#define MUSIC_NORMAL ((music_t)32)
#define MUSIC_SADNESS ((music_t)33)
#define MUSIC_EMI ((music_t)34)
#define MUSIC_PEARLY ((music_t)35)
#define MUSIC_SHIZUNE ((music_t)36)
#define MUSIC_ONE ((music_t)37)
#define MUSIC_MENUS ((music_t)38)

typedef unsigned char scene_transition_t;
#define SCENE_TRANSITION_NONE ((scene_transition_t)0)
#define SCENE_TRANSITION_LOCATIONCHANGE ((scene_transition_t)1)
#define SCENE_TRANSITION_LOCATIONSKIP ((scene_transition_t)2)
#define SCENE_TRANSITION_SHORTTIMESKIP ((scene_transition_t)3)
#define SCENE_TRANSITION_SHORTTIMESKIPSILENT ((scene_transition_t)4)
#define SCENE_TRANSITION_OPENEYE ((scene_transition_t)5)
#define SCENE_TRANSITION_SHUTEYE ((scene_transition_t)6)
#define SCENE_TRANSITION_OPENEYEFAST ((scene_transition_t)7)
#define SCENE_TRANSITION_SHUTEYEFAST ((scene_transition_t)8)
#define SCENE_TRANSITION_OPENEYE_SHOCK ((scene_transition_t)9)
#define SCENE_TRANSITION_WHIP_RIGHT ((scene_transition_t)10)
#define SCENE_TRANSITION_WHIP_LEFT ((scene_transition_t)11)
#define SCENE_TRANSITION_FLASHBACK ((scene_transition_t)12) // TODO: Check the correctness (see: script-a2-emi)
#define SCENE_TRANSITION_DELAYBLINDS ((scene_transition_t)13)
#define SCENE_TRANSITION_HANDS_IN ((scene_transition_t)14)
#define SCENE_TRANSITION_HANDS_OUT ((scene_transition_t)15)
#define SCENE_TRANSITION_SOFTWIPEDOWN ((scene_transition_t)16)
#define SCENE_TRANSITION_SOFTWIPEUP ((scene_transition_t)17)
#define SCENE_TRANSITION_SILENTFLASH ((scene_transition_t)18)
#define SCENE_TRANSITION_FLASH ((scene_transition_t)19)
#define SCENE_TRANSITION_SILENTWHITEOUT ((scene_transition_t)20)
#define SCENE_TRANSITION_WHITEOUT ((scene_transition_t)21)
#define SCENE_TRANSITION_CAMERAFLASH ((scene_transition_t)22)
#define SCENE_TRANSITION_CAMERAFLASHLONG ((scene_transition_t)23)
#define SCENE_TRANSITION_PASSOUTOP1 ((scene_transition_t)24)
#define SCENE_TRANSITION_SHOWDOWN_THUNDER_LONG ((scene_transition_t)25)
#define SCENE_TRANSITION_SHOWDOWN_THUNDER_SHORT ((scene_transition_t)26)

typedef unsigned char character_t;
#define CHARACTER_NONE ((character_t)0)
#define CHARACTER_AKIRA ((character_t)1)
#define CHARACTER_EMI ((character_t)2)
#define CHARACTER_EMICAS ((character_t)3)
#define CHARACTER_EMINUDE ((character_t)4)
#define CHARACTER_EMIWHEEL ((character_t)5)
#define CHARACTER_HANAGOWN ((character_t)6)
#define CHARACTER_HANAKO ((character_t)7)
#define CHARACTER_HIDEAKI ((character_t)8)
#define CHARACTER_JIGORO ((character_t)9)
#define CHARACTER_KENJI ((character_t)10)
#define CHARACTER_LILLY ((character_t)11)
#define CHARACTER_MEIKO ((character_t)12)
#define CHARACTER_MIKI ((character_t)13)
#define CHARACTER_MISHA ((character_t)14)
#define CHARACTER_MISHASHORT ((character_t)15)
#define CHARACTER_MUTO ((character_t)16)
#define CHARACTER_NOMIYA ((character_t)17)
#define CHARACTER_NURSE ((character_t)18)
#define CHARACTER_RIN ((character_t)19)
#define CHARACTER_RINPAN ((character_t)20)
#define CHARACTER_SAE ((character_t)21)
#define CHARACTER_SHIZU ((character_t)22)
#define CHARACTER_SHIZUYU ((character_t)23)
#define CHARACTER_SHOPKEEP ((character_t)24)
#define CHARACTER_YUUKO ((character_t)25)
#define CHARACTER_YUUKOSHANG ((character_t)26)

typedef unsigned char script_t;
#define SCRIPT_A0_ACTNAME  ((script_t)0xFF)
#define SCRIPT_A1_MONDAY   ((script_t)0)
#define SCRIPT_A1_TUESDAY  ((script_t)1)
#define SCRIPT_A1_WEDNESDAY ((script_t)2)
#define SCRIPT_A1_THURSDAY ((script_t)3)

typedef unsigned short label_t;
#define LABEL_A0_ACTNAME_SCENE1  ((script_t)0xFFFF)
#define LABEL_A1_MONDAY_OUT_COLD ((label_t)0)
#define LABEL_A1_MONDAY_BUNDLE_OF_HISAO ((label_t)1)
#define LABEL_A1_MONDAY_GATEWAY_EFFECT ((label_t)2)
#define LABEL_A1_MONDAY_ENTER_STAGE_LEFT ((label_t)3)
#define LABEL_A1_MONDAY_IN_THE_NURSERY ((label_t)4)
#define LABEL_A1_MONDAY_NOBODYS_ROOM ((label_t)5)
#define LABEL_A1_TUESDAY_SMALLTALK ((label_t)6)
#define LABEL_A1_TUESDAY_RISK_VS_REWARD ((label_t)7)
#define LABEL_A1_TUESDAY_PSEUDO_TEA_COSY ((label_t)8)
#define LABEL_A1_TUESDAY_SHARED_LIBRARY ((label_t)9)
#define LABEL_A1_TUESDAY_BIZARRE_AND_SURREAL ((label_t)10)
#define LABEL_A1_WEDNESDAY_LUNCH_EVOLUTION_THEORY ((label_t)11)
#define LABEL_A1_WEDNESDAY_SHORT_SHARP_SHOCK ((label_t)12)
#define LABEL_A1_WEDNESDAY_MEET_CUTE ((label_t)13)
#define LABEL_A1_WEDNESDAY_DETOUR_AHEAD ((label_t)14)
#define LABEL_A1_WEDNESDAY_SIP_P1 ((label_t)15)
#define LABEL_A1_WEDNESDAY_IT_BUILDS_CHARACTER ((label_t)16)
#define LABEL_A1_WEDNESDAY_A_PRIVATE_LUNCH ((label_t)17)
#define LABEL_A1_WEDNESDAY_WAYLAY ((label_t)18)
#define LABEL_A1_WEDNESDAY_THE_OTHER_GREEN ((label_t)19)
#define LABEL_A1_THURSDAY_THE_RUNNING_GIRL ((label_t)20)
#define LABEL_A1_THURSDAY_SOAP ((label_t)21)
#define LABEL_A1_THURSDAY_COLD_WAR ((label_t)22)
#define LABEL_A1_THURSDAY_PROOF_OF_COMPETENCY ((label_t)23)
#define LABEL_A1_THURSDAY_EVENT_HORIZON ((label_t)24)
#define LABEL_A1_THURSDAY_ABOVE_AND_BEYOND ((label_t)25)
#define LABEL_A1_THURSDAY_PAINT_BY_NUMBERS ((label_t)26)
#define LABEL_A1_THURSDAY_THINGS_YOU_CAN_DO ((label_t)27)
#define LABEL_A1_FRIDAY_EXERCISE ((label_t)28)
#define LABEL_A1_FRIDAY_INVISIBLE_HAT ((label_t)29)
#define LABEL_A1_FRIDAY_HOME_FIELD_ADVANTAGE ((label_t)30)
#define LABEL_A1_FRIDAY_NO_RECOVERY ((label_t)31)
#define LABEL_A1_FRIDAY_SLOW_RECOVERY ((label_t)32)
#define LABEL_A1_FRIDAY_NO_FREE_LUNCH ((label_t)33)
#define LABEL_A1_FRIDAY_FOOT_AND_MOUTH ((label_t)34)
#define LABEL_A1_FRIDAY_MIND_YOUR_STEP ((label_t)35)
#define LABEL_A1_SATURDAY_SUPPORT ((label_t)36)
#define LABEL_A1_SATURDAY_AN_AESTHETICS ((label_t)37)
#define LABEL_A1_SATURDAY_CREATIVE_PAIN ((label_t)38)
#define LABEL_A1_SATURDAY_PROPER_EXERCISE ((label_t)39)
#define LABEL_A1_SATURDAY_SIP_P2 ((label_t)40)
#define LABEL_A1_SATURDAY_SHANGHAIED ((label_t)41)
#define LABEL_A1_SATURDAY_QUIET ((label_t)42)
#define LABEL_A1_SUNDAY_DONT_PANIC ((label_t)43)
#define LABEL_A1_SUNDAY_IS_CARNIVAL ((label_t)44)
#define LABEL_A1_SUNDAY_CLOUDS_IN_MY_HEAD ((label_t)45)
#define LABEL_A1_SUNDAY_PROMISE_OF_TIME ((label_t)46)
#define LABEL_A1_SUNDAY_NC5XB3 ((label_t)47)
#define LABEL_A1_SUNDAY_MOVEMENT ((label_t)48)
#define LABEL_A1_SUNDAY_THROWING_BALLS ((label_t)49)
#define LABEL_A1_SUNDAY_THE_DEEP_END ((label_t)50)

#define LABEL_A2_EMI_MORNING_RUN ((label_t)51)
#define LABEL_A2_EMI_CLOUDS_TIME_TRAVEL_AND_THOU ((label_t)52)
#define LABEL_A2_EMI_QUESTIONS_THAT_NEED_ANSWERING ((label_t)53)
#define LABEL_A2_EMI_SECOND_TIMES_THE_WORST ((label_t)54)
#define LABEL_A2_EMI_AN_APPLE_A_DAY ((label_t)55)
#define LABEL_A2_EMI_TRACK_MEETING ((label_t)56)
#define LABEL_A2_EMI_DOWN_THAT_MEDICINE_NOW ((label_t)57)
#define LABEL_A2_EMI_PIRACY_ON_THE_HIGH_SEAS ((label_t)58)
#define LABEL_A2_EMI_FAMOUS_LAST_WORDS ((label_t)59)
#define LABEL_A2_EMI_TRACKING_ABSENCES ((label_t)60)
#define LABEL_A2_EMI_DROPPING_BY ((label_t)61)
#define LABEL_A2_EMI_THE_FIRST_MORNING_AFTER ((label_t)62)
#define LABEL_A2_EMI_THE_REAL_BEGINNING ((label_t)63)
#define LABEL_A3_EMI_EET_EES_SCIENCA ((label_t)64)
#define LABEL_A3_EMI_DEFINITIONS ((label_t)65)
#define LABEL_A3_EMI_INVISIBLE_ROCK ((label_t)66)
#define LABEL_A3_EMI_LUNCH_AND_SCIENCE ((label_t)67)
#define LABEL_A3_EMI_UP_DOWN_AND_UP_AGAIN ((label_t)68)
#define LABEL_A3_EMI_STORAGE_SPACE ((label_t)69)
#define LABEL_A3_EMI_AFTER_SCHOOL_PLANS ((label_t)70)
#define LABEL_A3_EMI_DETACHED ((label_t)71)
#define LABEL_A3_EMI_PHANTOM_PAIN ((label_t)72)
#define LABEL_A3_EMI_DEBATE_EXPRESSES_DOUBT ((label_t)73)
#define LABEL_A3_EMI_GUESS_WHOS_COMING_NEVER_MIND ((label_t)74)
#define LABEL_A3_EMI_INSTANT_REPLAY ((label_t)75)
#define LABEL_A4_EMI_A_SWING_AND_A_MISS ((label_t)76)
#define LABEL_A4_EMI_SAVING_THROW ((label_t)77)
#define LABEL_A4_EMI_WHISPERS_OF_THE_PAST ((label_t)78)
#define LABEL_A4_EMI_HOORAY_FOR_SOCKS ((label_t)79)
#define LABEL_A4_EMI_CLEAN_TEETH ((label_t)80)


#endif //DEFINITIONS_H
