#ifndef DEFINITIONS_H
#define DEFINITIONS_H

typedef unsigned char forceRoute_t;
#define FR_NONE   ((forceRoute_t)0)
#define FR_EMI    ((forceRoute_t)1)
#define FR_HANAKO ((forceRoute_t)2)
#define FR_LILLY  ((forceRoute_t)3)
#define FR_RIN    ((forceRoute_t)4)
#define FR_SHIZU  ((forceRoute_t)5)
#define FR_KENJI  ((forceRoute_t)6)

typedef unsigned char language_t;
#define LANG_ENGLISH ((language_t)0)
#define LANG_RUSSIAN ((language_t)1)

typedef unsigned char sound_channel_t;
#define SOUND_CHANNEL_MUSIC ((sound_channel_t)0)
#define SOUND_CHANNEL_SOUND ((sound_channel_t)1)
#define SOUND_CHANNEL_AMBIENT ((sound_channel_t)2)
#define SOUND_CHANNEL_VIDEO ((sound_channel_t)0)

typedef unsigned char script_t;
#define SCRIPT_A0_ACTNAME  ((script_t)0xFF)
#define SCRIPT_A1_MONDAY   ((script_t)0)
#define SCRIPT_A1_TUESDAY  ((script_t)1)
#define SCRIPT_A1_WEDNESDAY ((script_t)2)
#define SCRIPT_A1_THURSDAY ((script_t)3)

typedef unsigned short label_t;
#define LABEL_A0_ACTNAME_SCENE1  ((script_t)0xFFFF)
#define LABEL_A1_MONDAY_OUT_COLD ((label_t)0)
#define LABEL_A1_MONDAY_BUNDLE_OF_HISAO ((label_t)1)
#define LABEL_A1_MONDAY_GATEWAY_EFFECT ((label_t)2)
#define LABEL_A1_MONDAY_ENTER_STAGE_LEFT ((label_t)3)
#define LABEL_A1_MONDAY_IN_THE_NURSERY ((label_t)4)
#define LABEL_A1_MONDAY_NOBODYS_ROOM ((label_t)5)
#define LABEL_A1_TUESDAY_SMALLTALK ((label_t)6)
#define LABEL_A1_TUESDAY_RISK_VS_REWARD ((label_t)7)
#define LABEL_A1_TUESDAY_PSEUDO_TEA_COSY ((label_t)8)
#define LABEL_A1_TUESDAY_SHARED_LIBRARY ((label_t)9)
#define LABEL_A1_TUESDAY_BIZARRE_AND_SURREAL ((label_t)10)
#define LABEL_A1_WEDNESDAY_LUNCH_EVOLUTION_THEORY ((label_t)11)
#define LABEL_A1_WEDNESDAY_SHORT_SHARP_SHOCK ((label_t)12)
#define LABEL_A1_WEDNESDAY_MEET_CUTE ((label_t)13)
#define LABEL_A1_WEDNESDAY_DETOUR_AHEAD ((label_t)14)
#define LABEL_A1_WEDNESDAY_SIP_P1 ((label_t)15)
#define LABEL_A1_WEDNESDAY_IT_BUILDS_CHARACTER ((label_t)16)
#define LABEL_A1_WEDNESDAY_A_PRIVATE_LUNCH ((label_t)17)
#define LABEL_A1_WEDNESDAY_WAYLAY ((label_t)18)
#define LABEL_A1_WEDNESDAY_THE_OTHER_GREEN ((label_t)19)
#define LABEL_A1_THURSDAY_THE_RUNNING_GIRL ((label_t)20)
#define LABEL_A1_THURSDAY_SOAP ((label_t)21)
#define LABEL_A1_THURSDAY_COLD_WAR ((label_t)22)
#define LABEL_A1_THURSDAY_PROOF_OF_COMPETENCY ((label_t)23)
#define LABEL_A1_THURSDAY_EVENT_HORIZON ((label_t)24)
#define LABEL_A1_THURSDAY_ABOVE_AND_BEYOND ((label_t)25)
#define LABEL_A1_THURSDAY_PAINT_BY_NUMBERS ((label_t)26)
#define LABEL_A1_THURSDAY_THINGS_YOU_CAN_DO ((label_t)27)
#define LABEL_A1_FRIDAY_EXERCISE ((label_t)28)
#define LABEL_A1_FRIDAY_INVISIBLE_HAT ((label_t)29)
#define LABEL_A1_FRIDAY_HOME_FIELD_ADVANTAGE ((label_t)30)
#define LABEL_A1_FRIDAY_NO_RECOVERY ((label_t)31)
#define LABEL_A1_FRIDAY_SLOW_RECOVERY ((label_t)32)
#define LABEL_A1_FRIDAY_NO_FREE_LUNCH ((label_t)33)
#define LABEL_A1_FRIDAY_FOOT_AND_MOUTH ((label_t)34)
#define LABEL_A1_FRIDAY_MIND_YOUR_STEP ((label_t)35)
#define LABEL_A1_SATURDAY_SUPPORT ((label_t)36)
#define LABEL_A1_SATURDAY_AN_AESTHETICS ((label_t)37)
#define LABEL_A1_SATURDAY_CREATIVE_PAIN ((label_t)38)
#define LABEL_A1_SATURDAY_PROPER_EXERCISE ((label_t)39)
#define LABEL_A1_SATURDAY_SIP_P2 ((label_t)40)
#define LABEL_A1_SATURDAY_SHANGHAIED ((label_t)41)
#define LABEL_A1_SATURDAY_QUIET ((label_t)42)
#define LABEL_A1_SUNDAY_DONT_PANIC ((label_t)43)
#define LABEL_A1_SUNDAY_IS_CARNIVAL ((label_t)44)
#define LABEL_A1_SUNDAY_CLOUDS_IN_MY_HEAD ((label_t)45)
#define LABEL_A1_SUNDAY_PROMISE_OF_TIME ((label_t)46)
#define LABEL_A1_SUNDAY_NC5XB3 ((label_t)47)
#define LABEL_A1_SUNDAY_MOVEMENT ((label_t)48)
#define LABEL_A1_SUNDAY_THROWING_BALLS ((label_t)49)
#define LABEL_A1_SUNDAY_THE_DEEP_END ((label_t)50)

#define LABEL_A2_EMI_MORNING_RUN ((label_t)51)
#define LABEL_A2_EMI_CLOUDS_TIME_TRAVEL_AND_THOU ((label_t)52)
#define LABEL_A2_EMI_QUESTIONS_THAT_NEED_ANSWERING ((label_t)53)
#define LABEL_A2_EMI_SECOND_TIMES_THE_WORST ((label_t)54)
#define LABEL_A2_EMI_AN_APPLE_A_DAY ((label_t)55)
#define LABEL_A2_EMI_TRACK_MEETING ((label_t)56)
#define LABEL_A2_EMI_DOWN_THAT_MEDICINE_NOW ((label_t)57)
#define LABEL_A2_EMI_PIRACY_ON_THE_HIGH_SEAS ((label_t)58)
#define LABEL_A2_EMI_FAMOUS_LAST_WORDS ((label_t)59)
#define LABEL_A2_EMI_TRACKING_ABSENCES ((label_t)60)
#define LABEL_A2_EMI_DROPPING_BY ((label_t)61)
#define LABEL_A2_EMI_THE_FIRST_MORNING_AFTER ((label_t)62)
#define LABEL_A2_EMI_THE_REAL_BEGINNING ((label_t)63)
#define LABEL_A3_EMI_EET_EES_SCIENCA ((label_t)64)
#define LABEL_A3_EMI_DEFINITIONS ((label_t)65)
#define LABEL_A3_EMI_INVISIBLE_ROCK ((label_t)66)
#define LABEL_A3_EMI_LUNCH_AND_SCIENCE ((label_t)67)
#define LABEL_A3_EMI_UP_DOWN_AND_UP_AGAIN ((label_t)68)
#define LABEL_A3_EMI_STORAGE_SPACE ((label_t)69)
#define LABEL_A3_EMI_AFTER_SCHOOL_PLANS ((label_t)70)
#define LABEL_A3_EMI_DETACHED ((label_t)71)
#define LABEL_A3_EMI_PHANTOM_PAIN ((label_t)72)
#define LABEL_A3_EMI_DEBATE_EXPRESSES_DOUBT ((label_t)73)
#define LABEL_A3_EMI_GUESS_WHOS_COMING_NEVER_MIND ((label_t)74)
#define LABEL_A3_EMI_INSTANT_REPLAY ((label_t)75)
#define LABEL_A4_EMI_A_SWING_AND_A_MISS ((label_t)76)
#define LABEL_A4_EMI_SAVING_THROW ((label_t)77)
#define LABEL_A4_EMI_WHISPERS_OF_THE_PAST ((label_t)78)
#define LABEL_A4_EMI_HOORAY_FOR_SOCKS ((label_t)79)
#define LABEL_A4_EMI_CLEAN_TEETH ((label_t)80)


#endif //DEFINITIONS_H
